// Code generated by ent, DO NOT EDIT.

package server

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/server/nodemanagementcandidate"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
)

// NodeManagementCandidateDelete is the builder for deleting a NodeManagementCandidate entity.
type NodeManagementCandidateDelete struct {
	config
	hooks    []Hook
	mutation *NodeManagementCandidateMutation
}

// Where appends a list predicates to the NodeManagementCandidateDelete builder.
func (_d *NodeManagementCandidateDelete) Where(ps ...predicate.NodeManagementCandidate) *NodeManagementCandidateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NodeManagementCandidateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NodeManagementCandidateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NodeManagementCandidateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nodemanagementcandidate.Table, sqlgraph.NewFieldSpec(nodemanagementcandidate.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NodeManagementCandidateDeleteOne is the builder for deleting a single NodeManagementCandidate entity.
type NodeManagementCandidateDeleteOne struct {
	_d *NodeManagementCandidateDelete
}

// Where appends a list predicates to the NodeManagementCandidateDelete builder.
func (_d *NodeManagementCandidateDeleteOne) Where(ps ...predicate.NodeManagementCandidate) *NodeManagementCandidateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NodeManagementCandidateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nodemanagementcandidate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NodeManagementCandidateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
