// Code generated by ent, DO NOT EDIT.

package server

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/server/node"
	"github.com/hackycy/hackycy-cli/ent/server/nodeportpool"
)

// NodePortPoolCreate is the builder for creating a NodePortPool entity.
type NodePortPoolCreate struct {
	config
	mutation *NodePortPoolMutation
	hooks    []Hook
}

// SetNodeID sets the "node_id" field.
func (_c *NodePortPoolCreate) SetNodeID(v string) *NodePortPoolCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetPortStart sets the "port_start" field.
func (_c *NodePortPoolCreate) SetPortStart(v int) *NodePortPoolCreate {
	_c.mutation.SetPortStart(v)
	return _c
}

// SetPortEnd sets the "port_end" field.
func (_c *NodePortPoolCreate) SetPortEnd(v int) *NodePortPoolCreate {
	_c.mutation.SetPortEnd(v)
	return _c
}

// SetNode sets the "node" edge to the Node entity.
func (_c *NodePortPoolCreate) SetNode(v *Node) *NodePortPoolCreate {
	return _c.SetNodeID(v.ID)
}

// Mutation returns the NodePortPoolMutation object of the builder.
func (_c *NodePortPoolCreate) Mutation() *NodePortPoolMutation {
	return _c.mutation
}

// Save creates the NodePortPool in the database.
func (_c *NodePortPoolCreate) Save(ctx context.Context) (*NodePortPool, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodePortPoolCreate) SaveX(ctx context.Context) *NodePortPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodePortPoolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodePortPoolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodePortPoolCreate) check() error {
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`server: missing required field "NodePortPool.node_id"`)}
	}
	if _, ok := _c.mutation.PortStart(); !ok {
		return &ValidationError{Name: "port_start", err: errors.New(`server: missing required field "NodePortPool.port_start"`)}
	}
	if _, ok := _c.mutation.PortEnd(); !ok {
		return &ValidationError{Name: "port_end", err: errors.New(`server: missing required field "NodePortPool.port_end"`)}
	}
	if len(_c.mutation.NodeIDs()) == 0 {
		return &ValidationError{Name: "node", err: errors.New(`server: missing required edge "NodePortPool.node"`)}
	}
	return nil
}

func (_c *NodePortPoolCreate) sqlSave(ctx context.Context) (*NodePortPool, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodePortPoolCreate) createSpec() (*NodePortPool, *sqlgraph.CreateSpec) {
	var (
		_node = &NodePortPool{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nodeportpool.Table, sqlgraph.NewFieldSpec(nodeportpool.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PortStart(); ok {
		_spec.SetField(nodeportpool.FieldPortStart, field.TypeInt, value)
		_node.PortStart = value
	}
	if value, ok := _c.mutation.PortEnd(); ok {
		_spec.SetField(nodeportpool.FieldPortEnd, field.TypeInt, value)
		_node.PortEnd = value
	}
	if nodes := _c.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   nodeportpool.NodeTable,
			Columns: []string{nodeportpool.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NodePortPoolCreateBulk is the builder for creating many NodePortPool entities in bulk.
type NodePortPoolCreateBulk struct {
	config
	err      error
	builders []*NodePortPoolCreate
}

// Save creates the NodePortPool entities in the database.
func (_c *NodePortPoolCreateBulk) Save(ctx context.Context) ([]*NodePortPool, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NodePortPool, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodePortPoolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodePortPoolCreateBulk) SaveX(ctx context.Context) []*NodePortPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodePortPoolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodePortPoolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
