// Code generated by ent, DO NOT EDIT.

package server

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/server/node"
	"github.com/hackycy/hackycy-cli/ent/server/nodemanagementcandidate"
	"github.com/hackycy/hackycy-cli/ent/server/nodeobservation"
	"github.com/hackycy/hackycy-cli/ent/server/nodeportpool"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
	"github.com/hackycy/hackycy-cli/ent/server/remotenode"
	"github.com/hackycy/hackycy-cli/ent/server/serverclient"
	"github.com/hackycy/hackycy-cli/ent/server/tunnel"
)

// NodeQuery is the builder for querying Node entities.
type NodeQuery struct {
	config
	ctx                     *QueryContext
	order                   []node.OrderOption
	inters                  []Interceptor
	predicates              []predicate.Node
	withClients             *ServerClientQuery
	withPendingClients      *ServerClientQuery
	withAppliedClients      *ServerClientQuery
	withTunnels             *TunnelQuery
	withRemoteNode          *RemoteNodeQuery
	withPortPool            *NodePortPoolQuery
	withManagementCandidate *NodeManagementCandidateQuery
	withObservation         *NodeObservationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NodeQuery builder.
func (_q *NodeQuery) Where(ps ...predicate.Node) *NodeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *NodeQuery) Limit(limit int) *NodeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *NodeQuery) Offset(offset int) *NodeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *NodeQuery) Unique(unique bool) *NodeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *NodeQuery) Order(o ...node.OrderOption) *NodeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryClients chains the current query on the "clients" edge.
func (_q *NodeQuery) QueryClients() *ServerClientQuery {
	query := (&ServerClientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(serverclient.Table, serverclient.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.ClientsTable, node.ClientsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPendingClients chains the current query on the "pending_clients" edge.
func (_q *NodeQuery) QueryPendingClients() *ServerClientQuery {
	query := (&ServerClientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(serverclient.Table, serverclient.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.PendingClientsTable, node.PendingClientsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAppliedClients chains the current query on the "applied_clients" edge.
func (_q *NodeQuery) QueryAppliedClients() *ServerClientQuery {
	query := (&ServerClientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(serverclient.Table, serverclient.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.AppliedClientsTable, node.AppliedClientsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTunnels chains the current query on the "tunnels" edge.
func (_q *NodeQuery) QueryTunnels() *TunnelQuery {
	query := (&TunnelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(tunnel.Table, tunnel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, node.TunnelsTable, node.TunnelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRemoteNode chains the current query on the "remote_node" edge.
func (_q *NodeQuery) QueryRemoteNode() *RemoteNodeQuery {
	query := (&RemoteNodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(remotenode.Table, remotenode.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, node.RemoteNodeTable, node.RemoteNodeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPortPool chains the current query on the "port_pool" edge.
func (_q *NodeQuery) QueryPortPool() *NodePortPoolQuery {
	query := (&NodePortPoolClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(nodeportpool.Table, nodeportpool.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, node.PortPoolTable, node.PortPoolColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryManagementCandidate chains the current query on the "management_candidate" edge.
func (_q *NodeQuery) QueryManagementCandidate() *NodeManagementCandidateQuery {
	query := (&NodeManagementCandidateClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(nodemanagementcandidate.Table, nodemanagementcandidate.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, node.ManagementCandidateTable, node.ManagementCandidateColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryObservation chains the current query on the "observation" edge.
func (_q *NodeQuery) QueryObservation() *NodeObservationQuery {
	query := (&NodeObservationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(node.Table, node.FieldID, selector),
			sqlgraph.To(nodeobservation.Table, nodeobservation.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, node.ObservationTable, node.ObservationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Node entity from the query.
// Returns a *NotFoundError when no Node was found.
func (_q *NodeQuery) First(ctx context.Context) (*Node, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{node.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *NodeQuery) FirstX(ctx context.Context) *Node {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Node ID from the query.
// Returns a *NotFoundError when no Node ID was found.
func (_q *NodeQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{node.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *NodeQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Node entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Node entity is found.
// Returns a *NotFoundError when no Node entities are found.
func (_q *NodeQuery) Only(ctx context.Context) (*Node, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{node.Label}
	default:
		return nil, &NotSingularError{node.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *NodeQuery) OnlyX(ctx context.Context) *Node {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Node ID in the query.
// Returns a *NotSingularError when more than one Node ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *NodeQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{node.Label}
	default:
		err = &NotSingularError{node.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *NodeQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Nodes.
func (_q *NodeQuery) All(ctx context.Context) ([]*Node, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Node, *NodeQuery]()
	return withInterceptors[[]*Node](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *NodeQuery) AllX(ctx context.Context) []*Node {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Node IDs.
func (_q *NodeQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(node.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *NodeQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *NodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*NodeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *NodeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *NodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("server: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *NodeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *NodeQuery) Clone() *NodeQuery {
	if _q == nil {
		return nil
	}
	return &NodeQuery{
		config:                  _q.config,
		ctx:                     _q.ctx.Clone(),
		order:                   append([]node.OrderOption{}, _q.order...),
		inters:                  append([]Interceptor{}, _q.inters...),
		predicates:              append([]predicate.Node{}, _q.predicates...),
		withClients:             _q.withClients.Clone(),
		withPendingClients:      _q.withPendingClients.Clone(),
		withAppliedClients:      _q.withAppliedClients.Clone(),
		withTunnels:             _q.withTunnels.Clone(),
		withRemoteNode:          _q.withRemoteNode.Clone(),
		withPortPool:            _q.withPortPool.Clone(),
		withManagementCandidate: _q.withManagementCandidate.Clone(),
		withObservation:         _q.withObservation.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithClients tells the query-builder to eager-load the nodes that are connected to
// the "clients" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithClients(opts ...func(*ServerClientQuery)) *NodeQuery {
	query := (&ServerClientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClients = query
	return _q
}

// WithPendingClients tells the query-builder to eager-load the nodes that are connected to
// the "pending_clients" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithPendingClients(opts ...func(*ServerClientQuery)) *NodeQuery {
	query := (&ServerClientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPendingClients = query
	return _q
}

// WithAppliedClients tells the query-builder to eager-load the nodes that are connected to
// the "applied_clients" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithAppliedClients(opts ...func(*ServerClientQuery)) *NodeQuery {
	query := (&ServerClientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAppliedClients = query
	return _q
}

// WithTunnels tells the query-builder to eager-load the nodes that are connected to
// the "tunnels" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithTunnels(opts ...func(*TunnelQuery)) *NodeQuery {
	query := (&TunnelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTunnels = query
	return _q
}

// WithRemoteNode tells the query-builder to eager-load the nodes that are connected to
// the "remote_node" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithRemoteNode(opts ...func(*RemoteNodeQuery)) *NodeQuery {
	query := (&RemoteNodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRemoteNode = query
	return _q
}

// WithPortPool tells the query-builder to eager-load the nodes that are connected to
// the "port_pool" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithPortPool(opts ...func(*NodePortPoolQuery)) *NodeQuery {
	query := (&NodePortPoolClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPortPool = query
	return _q
}

// WithManagementCandidate tells the query-builder to eager-load the nodes that are connected to
// the "management_candidate" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithManagementCandidate(opts ...func(*NodeManagementCandidateQuery)) *NodeQuery {
	query := (&NodeManagementCandidateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withManagementCandidate = query
	return _q
}

// WithObservation tells the query-builder to eager-load the nodes that are connected to
// the "observation" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NodeQuery) WithObservation(opts ...func(*NodeObservationQuery)) *NodeQuery {
	query := (&NodeObservationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withObservation = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Kind node.Kind `json:"kind,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Node.Query().
//		GroupBy(node.FieldKind).
//		Aggregate(server.Count()).
//		Scan(ctx, &v)
func (_q *NodeQuery) GroupBy(field string, fields ...string) *NodeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NodeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = node.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Kind node.Kind `json:"kind,omitempty"`
//	}
//
//	client.Node.Query().
//		Select(node.FieldKind).
//		Scan(ctx, &v)
func (_q *NodeQuery) Select(fields ...string) *NodeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &NodeSelect{NodeQuery: _q}
	sbuild.label = node.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NodeSelect configured with the given aggregations.
func (_q *NodeQuery) Aggregate(fns ...AggregateFunc) *NodeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *NodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("server: uninitialized interceptor (forgotten import server/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !node.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("server: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *NodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Node, error) {
	var (
		nodes       = []*Node{}
		_spec       = _q.querySpec()
		loadedTypes = [8]bool{
			_q.withClients != nil,
			_q.withPendingClients != nil,
			_q.withAppliedClients != nil,
			_q.withTunnels != nil,
			_q.withRemoteNode != nil,
			_q.withPortPool != nil,
			_q.withManagementCandidate != nil,
			_q.withObservation != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Node).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Node{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withClients; query != nil {
		if err := _q.loadClients(ctx, query, nodes,
			func(n *Node) { n.Edges.Clients = []*ServerClient{} },
			func(n *Node, e *ServerClient) { n.Edges.Clients = append(n.Edges.Clients, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPendingClients; query != nil {
		if err := _q.loadPendingClients(ctx, query, nodes,
			func(n *Node) { n.Edges.PendingClients = []*ServerClient{} },
			func(n *Node, e *ServerClient) { n.Edges.PendingClients = append(n.Edges.PendingClients, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAppliedClients; query != nil {
		if err := _q.loadAppliedClients(ctx, query, nodes,
			func(n *Node) { n.Edges.AppliedClients = []*ServerClient{} },
			func(n *Node, e *ServerClient) { n.Edges.AppliedClients = append(n.Edges.AppliedClients, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTunnels; query != nil {
		if err := _q.loadTunnels(ctx, query, nodes,
			func(n *Node) { n.Edges.Tunnels = []*Tunnel{} },
			func(n *Node, e *Tunnel) { n.Edges.Tunnels = append(n.Edges.Tunnels, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRemoteNode; query != nil {
		if err := _q.loadRemoteNode(ctx, query, nodes, nil,
			func(n *Node, e *RemoteNode) { n.Edges.RemoteNode = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPortPool; query != nil {
		if err := _q.loadPortPool(ctx, query, nodes, nil,
			func(n *Node, e *NodePortPool) { n.Edges.PortPool = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withManagementCandidate; query != nil {
		if err := _q.loadManagementCandidate(ctx, query, nodes, nil,
			func(n *Node, e *NodeManagementCandidate) { n.Edges.ManagementCandidate = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withObservation; query != nil {
		if err := _q.loadObservation(ctx, query, nodes, nil,
			func(n *Node, e *NodeObservation) { n.Edges.Observation = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *NodeQuery) loadClients(ctx context.Context, query *ServerClientQuery, nodes []*Node, init func(*Node), assign func(*Node, *ServerClient)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(serverclient.FieldNodeID)
	}
	query.Where(predicate.ServerClient(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.ClientsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NodeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadPendingClients(ctx context.Context, query *ServerClientQuery, nodes []*Node, init func(*Node), assign func(*Node, *ServerClient)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(serverclient.FieldPendingNodeID)
	}
	query.Where(predicate.ServerClient(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.PendingClientsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PendingNodeID
		if fk == nil {
			return fmt.Errorf(`foreign-key "pending_node_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "pending_node_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadAppliedClients(ctx context.Context, query *ServerClientQuery, nodes []*Node, init func(*Node), assign func(*Node, *ServerClient)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(serverclient.FieldLastAppliedNodeID)
	}
	query.Where(predicate.ServerClient(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.AppliedClientsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LastAppliedNodeID
		if fk == nil {
			return fmt.Errorf(`foreign-key "last_applied_node_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "last_applied_node_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadTunnels(ctx context.Context, query *TunnelQuery, nodes []*Node, init func(*Node), assign func(*Node, *Tunnel)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tunnel.FieldNodeID)
	}
	query.Where(predicate.Tunnel(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.TunnelsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NodeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadRemoteNode(ctx context.Context, query *RemoteNodeQuery, nodes []*Node, init func(*Node), assign func(*Node, *RemoteNode)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(remotenode.FieldNodeID)
	}
	query.Where(predicate.RemoteNode(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.RemoteNodeColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NodeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadPortPool(ctx context.Context, query *NodePortPoolQuery, nodes []*Node, init func(*Node), assign func(*Node, *NodePortPool)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(nodeportpool.FieldNodeID)
	}
	query.Where(predicate.NodePortPool(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.PortPoolColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NodeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadManagementCandidate(ctx context.Context, query *NodeManagementCandidateQuery, nodes []*Node, init func(*Node), assign func(*Node, *NodeManagementCandidate)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(nodemanagementcandidate.FieldNodeID)
	}
	query.Where(predicate.NodeManagementCandidate(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.ManagementCandidateColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NodeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *NodeQuery) loadObservation(ctx context.Context, query *NodeObservationQuery, nodes []*Node, init func(*Node), assign func(*Node, *NodeObservation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Node)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(nodeobservation.FieldNodeID)
	}
	query.Where(predicate.NodeObservation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(node.ObservationColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NodeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "node_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *NodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *NodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for i := range fields {
			if fields[i] != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *NodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(node.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = node.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NodeGroupBy is the group-by builder for Node entities.
type NodeGroupBy struct {
	selector
	build *NodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *NodeGroupBy) Aggregate(fns ...AggregateFunc) *NodeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *NodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NodeQuery, *NodeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *NodeGroupBy) sqlScan(ctx context.Context, root *NodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NodeSelect is the builder for selecting fields of Node entities.
type NodeSelect struct {
	*NodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *NodeSelect) Aggregate(fns ...AggregateFunc) *NodeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *NodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NodeQuery, *NodeSelect](ctx, _s.NodeQuery, _s, _s.inters, v)
}

func (_s *NodeSelect) sqlScan(ctx context.Context, root *NodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
