// Code generated by ent, DO NOT EDIT.

package server

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/server/nodeportpool"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
)

// NodePortPoolDelete is the builder for deleting a NodePortPool entity.
type NodePortPoolDelete struct {
	config
	hooks    []Hook
	mutation *NodePortPoolMutation
}

// Where appends a list predicates to the NodePortPoolDelete builder.
func (_d *NodePortPoolDelete) Where(ps ...predicate.NodePortPool) *NodePortPoolDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NodePortPoolDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NodePortPoolDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NodePortPoolDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nodeportpool.Table, sqlgraph.NewFieldSpec(nodeportpool.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NodePortPoolDeleteOne is the builder for deleting a single NodePortPool entity.
type NodePortPoolDeleteOne struct {
	_d *NodePortPoolDelete
}

// Where appends a list predicates to the NodePortPoolDelete builder.
func (_d *NodePortPoolDeleteOne) Where(ps ...predicate.NodePortPool) *NodePortPoolDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NodePortPoolDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nodeportpool.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NodePortPoolDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
