// Code generated by ent, DO NOT EDIT.

package server

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/server/node"
	"github.com/hackycy/hackycy-cli/ent/server/nodemanagementcandidate"
	"github.com/hackycy/hackycy-cli/ent/server/nodeobservation"
	"github.com/hackycy/hackycy-cli/ent/server/nodeportpool"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
	"github.com/hackycy/hackycy-cli/ent/server/remotenode"
	"github.com/hackycy/hackycy-cli/ent/server/serverclient"
	"github.com/hackycy/hackycy-cli/ent/server/tunnel"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *NodeUpdate) SetKind(v node.Kind) *NodeUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableKind(v *node.Kind) *NodeUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *NodeUpdate) SetName(v string) *NodeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableName(v *string) *NodeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLifecycle sets the "lifecycle" field.
func (_u *NodeUpdate) SetLifecycle(v node.Lifecycle) *NodeUpdate {
	_u.mutation.SetLifecycle(v)
	return _u
}

// SetNillableLifecycle sets the "lifecycle" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLifecycle(v *node.Lifecycle) *NodeUpdate {
	if v != nil {
		_u.SetLifecycle(*v)
	}
	return _u
}

// SetAdvertisedFrpHost sets the "advertised_frp_host" field.
func (_u *NodeUpdate) SetAdvertisedFrpHost(v string) *NodeUpdate {
	_u.mutation.SetAdvertisedFrpHost(v)
	return _u
}

// SetNillableAdvertisedFrpHost sets the "advertised_frp_host" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableAdvertisedFrpHost(v *string) *NodeUpdate {
	if v != nil {
		_u.SetAdvertisedFrpHost(*v)
	}
	return _u
}

// ClearAdvertisedFrpHost clears the value of the "advertised_frp_host" field.
func (_u *NodeUpdate) ClearAdvertisedFrpHost() *NodeUpdate {
	_u.mutation.ClearAdvertisedFrpHost()
	return _u
}

// SetAdvertisedFrpPort sets the "advertised_frp_port" field.
func (_u *NodeUpdate) SetAdvertisedFrpPort(v int) *NodeUpdate {
	_u.mutation.ResetAdvertisedFrpPort()
	_u.mutation.SetAdvertisedFrpPort(v)
	return _u
}

// SetNillableAdvertisedFrpPort sets the "advertised_frp_port" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableAdvertisedFrpPort(v *int) *NodeUpdate {
	if v != nil {
		_u.SetAdvertisedFrpPort(*v)
	}
	return _u
}

// AddAdvertisedFrpPort adds value to the "advertised_frp_port" field.
func (_u *NodeUpdate) AddAdvertisedFrpPort(v int) *NodeUpdate {
	_u.mutation.AddAdvertisedFrpPort(v)
	return _u
}

// ClearAdvertisedFrpPort clears the value of the "advertised_frp_port" field.
func (_u *NodeUpdate) ClearAdvertisedFrpPort() *NodeUpdate {
	_u.mutation.ClearAdvertisedFrpPort()
	return _u
}

// SetHTTPIngressHost sets the "http_ingress_host" field.
func (_u *NodeUpdate) SetHTTPIngressHost(v string) *NodeUpdate {
	_u.mutation.SetHTTPIngressHost(v)
	return _u
}

// SetNillableHTTPIngressHost sets the "http_ingress_host" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableHTTPIngressHost(v *string) *NodeUpdate {
	if v != nil {
		_u.SetHTTPIngressHost(*v)
	}
	return _u
}

// ClearHTTPIngressHost clears the value of the "http_ingress_host" field.
func (_u *NodeUpdate) ClearHTTPIngressHost() *NodeUpdate {
	_u.mutation.ClearHTTPIngressHost()
	return _u
}

// SetHTTPIngressPort sets the "http_ingress_port" field.
func (_u *NodeUpdate) SetHTTPIngressPort(v int) *NodeUpdate {
	_u.mutation.ResetHTTPIngressPort()
	_u.mutation.SetHTTPIngressPort(v)
	return _u
}

// SetNillableHTTPIngressPort sets the "http_ingress_port" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableHTTPIngressPort(v *int) *NodeUpdate {
	if v != nil {
		_u.SetHTTPIngressPort(*v)
	}
	return _u
}

// AddHTTPIngressPort adds value to the "http_ingress_port" field.
func (_u *NodeUpdate) AddHTTPIngressPort(v int) *NodeUpdate {
	_u.mutation.AddHTTPIngressPort(v)
	return _u
}

// ClearHTTPIngressPort clears the value of the "http_ingress_port" field.
func (_u *NodeUpdate) ClearHTTPIngressPort() *NodeUpdate {
	_u.mutation.ClearHTTPIngressPort()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NodeUpdate) SetCreatedAt(v string) *NodeUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableCreatedAt(v *string) *NodeUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdate) SetUpdatedAt(v string) *NodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableUpdatedAt(v *string) *NodeUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddClientIDs adds the "clients" edge to the ServerClient entity by IDs.
func (_u *NodeUpdate) AddClientIDs(ids ...string) *NodeUpdate {
	_u.mutation.AddClientIDs(ids...)
	return _u
}

// AddClients adds the "clients" edges to the ServerClient entity.
func (_u *NodeUpdate) AddClients(v ...*ServerClient) *NodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientIDs(ids...)
}

// AddPendingClientIDs adds the "pending_clients" edge to the ServerClient entity by IDs.
func (_u *NodeUpdate) AddPendingClientIDs(ids ...string) *NodeUpdate {
	_u.mutation.AddPendingClientIDs(ids...)
	return _u
}

// AddPendingClients adds the "pending_clients" edges to the ServerClient entity.
func (_u *NodeUpdate) AddPendingClients(v ...*ServerClient) *NodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPendingClientIDs(ids...)
}

// AddAppliedClientIDs adds the "applied_clients" edge to the ServerClient entity by IDs.
func (_u *NodeUpdate) AddAppliedClientIDs(ids ...string) *NodeUpdate {
	_u.mutation.AddAppliedClientIDs(ids...)
	return _u
}

// AddAppliedClients adds the "applied_clients" edges to the ServerClient entity.
func (_u *NodeUpdate) AddAppliedClients(v ...*ServerClient) *NodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAppliedClientIDs(ids...)
}

// AddTunnelIDs adds the "tunnels" edge to the Tunnel entity by IDs.
func (_u *NodeUpdate) AddTunnelIDs(ids ...string) *NodeUpdate {
	_u.mutation.AddTunnelIDs(ids...)
	return _u
}

// AddTunnels adds the "tunnels" edges to the Tunnel entity.
func (_u *NodeUpdate) AddTunnels(v ...*Tunnel) *NodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTunnelIDs(ids...)
}

// SetRemoteNodeID sets the "remote_node" edge to the RemoteNode entity by ID.
func (_u *NodeUpdate) SetRemoteNodeID(id int) *NodeUpdate {
	_u.mutation.SetRemoteNodeID(id)
	return _u
}

// SetNillableRemoteNodeID sets the "remote_node" edge to the RemoteNode entity by ID if the given value is not nil.
func (_u *NodeUpdate) SetNillableRemoteNodeID(id *int) *NodeUpdate {
	if id != nil {
		_u = _u.SetRemoteNodeID(*id)
	}
	return _u
}

// SetRemoteNode sets the "remote_node" edge to the RemoteNode entity.
func (_u *NodeUpdate) SetRemoteNode(v *RemoteNode) *NodeUpdate {
	return _u.SetRemoteNodeID(v.ID)
}

// SetPortPoolID sets the "port_pool" edge to the NodePortPool entity by ID.
func (_u *NodeUpdate) SetPortPoolID(id int) *NodeUpdate {
	_u.mutation.SetPortPoolID(id)
	return _u
}

// SetNillablePortPoolID sets the "port_pool" edge to the NodePortPool entity by ID if the given value is not nil.
func (_u *NodeUpdate) SetNillablePortPoolID(id *int) *NodeUpdate {
	if id != nil {
		_u = _u.SetPortPoolID(*id)
	}
	return _u
}

// SetPortPool sets the "port_pool" edge to the NodePortPool entity.
func (_u *NodeUpdate) SetPortPool(v *NodePortPool) *NodeUpdate {
	return _u.SetPortPoolID(v.ID)
}

// SetManagementCandidateID sets the "management_candidate" edge to the NodeManagementCandidate entity by ID.
func (_u *NodeUpdate) SetManagementCandidateID(id int) *NodeUpdate {
	_u.mutation.SetManagementCandidateID(id)
	return _u
}

// SetNillableManagementCandidateID sets the "management_candidate" edge to the NodeManagementCandidate entity by ID if the given value is not nil.
func (_u *NodeUpdate) SetNillableManagementCandidateID(id *int) *NodeUpdate {
	if id != nil {
		_u = _u.SetManagementCandidateID(*id)
	}
	return _u
}

// SetManagementCandidate sets the "management_candidate" edge to the NodeManagementCandidate entity.
func (_u *NodeUpdate) SetManagementCandidate(v *NodeManagementCandidate) *NodeUpdate {
	return _u.SetManagementCandidateID(v.ID)
}

// SetObservationID sets the "observation" edge to the NodeObservation entity by ID.
func (_u *NodeUpdate) SetObservationID(id int) *NodeUpdate {
	_u.mutation.SetObservationID(id)
	return _u
}

// SetNillableObservationID sets the "observation" edge to the NodeObservation entity by ID if the given value is not nil.
func (_u *NodeUpdate) SetNillableObservationID(id *int) *NodeUpdate {
	if id != nil {
		_u = _u.SetObservationID(*id)
	}
	return _u
}

// SetObservation sets the "observation" edge to the NodeObservation entity.
func (_u *NodeUpdate) SetObservation(v *NodeObservation) *NodeUpdate {
	return _u.SetObservationID(v.ID)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearClients clears all "clients" edges to the ServerClient entity.
func (_u *NodeUpdate) ClearClients() *NodeUpdate {
	_u.mutation.ClearClients()
	return _u
}

// RemoveClientIDs removes the "clients" edge to ServerClient entities by IDs.
func (_u *NodeUpdate) RemoveClientIDs(ids ...string) *NodeUpdate {
	_u.mutation.RemoveClientIDs(ids...)
	return _u
}

// RemoveClients removes "clients" edges to ServerClient entities.
func (_u *NodeUpdate) RemoveClients(v ...*ServerClient) *NodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientIDs(ids...)
}

// ClearPendingClients clears all "pending_clients" edges to the ServerClient entity.
func (_u *NodeUpdate) ClearPendingClients() *NodeUpdate {
	_u.mutation.ClearPendingClients()
	return _u
}

// RemovePendingClientIDs removes the "pending_clients" edge to ServerClient entities by IDs.
func (_u *NodeUpdate) RemovePendingClientIDs(ids ...string) *NodeUpdate {
	_u.mutation.RemovePendingClientIDs(ids...)
	return _u
}

// RemovePendingClients removes "pending_clients" edges to ServerClient entities.
func (_u *NodeUpdate) RemovePendingClients(v ...*ServerClient) *NodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePendingClientIDs(ids...)
}

// ClearAppliedClients clears all "applied_clients" edges to the ServerClient entity.
func (_u *NodeUpdate) ClearAppliedClients() *NodeUpdate {
	_u.mutation.ClearAppliedClients()
	return _u
}

// RemoveAppliedClientIDs removes the "applied_clients" edge to ServerClient entities by IDs.
func (_u *NodeUpdate) RemoveAppliedClientIDs(ids ...string) *NodeUpdate {
	_u.mutation.RemoveAppliedClientIDs(ids...)
	return _u
}

// RemoveAppliedClients removes "applied_clients" edges to ServerClient entities.
func (_u *NodeUpdate) RemoveAppliedClients(v ...*ServerClient) *NodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAppliedClientIDs(ids...)
}

// ClearTunnels clears all "tunnels" edges to the Tunnel entity.
func (_u *NodeUpdate) ClearTunnels() *NodeUpdate {
	_u.mutation.ClearTunnels()
	return _u
}

// RemoveTunnelIDs removes the "tunnels" edge to Tunnel entities by IDs.
func (_u *NodeUpdate) RemoveTunnelIDs(ids ...string) *NodeUpdate {
	_u.mutation.RemoveTunnelIDs(ids...)
	return _u
}

// RemoveTunnels removes "tunnels" edges to Tunnel entities.
func (_u *NodeUpdate) RemoveTunnels(v ...*Tunnel) *NodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTunnelIDs(ids...)
}

// ClearRemoteNode clears the "remote_node" edge to the RemoteNode entity.
func (_u *NodeUpdate) ClearRemoteNode() *NodeUpdate {
	_u.mutation.ClearRemoteNode()
	return _u
}

// ClearPortPool clears the "port_pool" edge to the NodePortPool entity.
func (_u *NodeUpdate) ClearPortPool() *NodeUpdate {
	_u.mutation.ClearPortPool()
	return _u
}

// ClearManagementCandidate clears the "management_candidate" edge to the NodeManagementCandidate entity.
func (_u *NodeUpdate) ClearManagementCandidate() *NodeUpdate {
	_u.mutation.ClearManagementCandidate()
	return _u
}

// ClearObservation clears the "observation" edge to the NodeObservation entity.
func (_u *NodeUpdate) ClearObservation() *NodeUpdate {
	_u.mutation.ClearObservation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := node.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`server: validator failed for field "Node.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lifecycle(); ok {
		if err := node.LifecycleValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle", err: fmt.Errorf(`server: validator failed for field "Node.lifecycle": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(node.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Lifecycle(); ok {
		_spec.SetField(node.FieldLifecycle, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AdvertisedFrpHost(); ok {
		_spec.SetField(node.FieldAdvertisedFrpHost, field.TypeString, value)
	}
	if _u.mutation.AdvertisedFrpHostCleared() {
		_spec.ClearField(node.FieldAdvertisedFrpHost, field.TypeString)
	}
	if value, ok := _u.mutation.AdvertisedFrpPort(); ok {
		_spec.SetField(node.FieldAdvertisedFrpPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdvertisedFrpPort(); ok {
		_spec.AddField(node.FieldAdvertisedFrpPort, field.TypeInt, value)
	}
	if _u.mutation.AdvertisedFrpPortCleared() {
		_spec.ClearField(node.FieldAdvertisedFrpPort, field.TypeInt)
	}
	if value, ok := _u.mutation.HTTPIngressHost(); ok {
		_spec.SetField(node.FieldHTTPIngressHost, field.TypeString, value)
	}
	if _u.mutation.HTTPIngressHostCleared() {
		_spec.ClearField(node.FieldHTTPIngressHost, field.TypeString)
	}
	if value, ok := _u.mutation.HTTPIngressPort(); ok {
		_spec.SetField(node.FieldHTTPIngressPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPIngressPort(); ok {
		_spec.AddField(node.FieldHTTPIngressPort, field.TypeInt, value)
	}
	if _u.mutation.HTTPIngressPortCleared() {
		_spec.ClearField(node.FieldHTTPIngressPort, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeString, value)
	}
	if _u.mutation.ClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ClientsTable,
			Columns: []string{node.ClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientsIDs(); len(nodes) > 0 && !_u.mutation.ClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ClientsTable,
			Columns: []string{node.ClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ClientsTable,
			Columns: []string{node.ClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PendingClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.PendingClientsTable,
			Columns: []string{node.PendingClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPendingClientsIDs(); len(nodes) > 0 && !_u.mutation.PendingClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.PendingClientsTable,
			Columns: []string{node.PendingClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PendingClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.PendingClientsTable,
			Columns: []string{node.PendingClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AppliedClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AppliedClientsTable,
			Columns: []string{node.AppliedClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAppliedClientsIDs(); len(nodes) > 0 && !_u.mutation.AppliedClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AppliedClientsTable,
			Columns: []string{node.AppliedClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppliedClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AppliedClientsTable,
			Columns: []string{node.AppliedClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TunnelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TunnelsTable,
			Columns: []string{node.TunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTunnelsIDs(); len(nodes) > 0 && !_u.mutation.TunnelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TunnelsTable,
			Columns: []string{node.TunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TunnelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TunnelsTable,
			Columns: []string{node.TunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RemoteNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.RemoteNodeTable,
			Columns: []string{node.RemoteNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remotenode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemoteNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.RemoteNodeTable,
			Columns: []string{node.RemoteNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remotenode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PortPoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.PortPoolTable,
			Columns: []string{node.PortPoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeportpool.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PortPoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.PortPoolTable,
			Columns: []string{node.PortPoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeportpool.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagementCandidateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.ManagementCandidateTable,
			Columns: []string{node.ManagementCandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodemanagementcandidate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagementCandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.ManagementCandidateTable,
			Columns: []string{node.ManagementCandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodemanagementcandidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ObservationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.ObservationTable,
			Columns: []string{node.ObservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeobservation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ObservationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.ObservationTable,
			Columns: []string{node.ObservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeobservation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetKind sets the "kind" field.
func (_u *NodeUpdateOne) SetKind(v node.Kind) *NodeUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableKind(v *node.Kind) *NodeUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *NodeUpdateOne) SetName(v string) *NodeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableName(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLifecycle sets the "lifecycle" field.
func (_u *NodeUpdateOne) SetLifecycle(v node.Lifecycle) *NodeUpdateOne {
	_u.mutation.SetLifecycle(v)
	return _u
}

// SetNillableLifecycle sets the "lifecycle" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLifecycle(v *node.Lifecycle) *NodeUpdateOne {
	if v != nil {
		_u.SetLifecycle(*v)
	}
	return _u
}

// SetAdvertisedFrpHost sets the "advertised_frp_host" field.
func (_u *NodeUpdateOne) SetAdvertisedFrpHost(v string) *NodeUpdateOne {
	_u.mutation.SetAdvertisedFrpHost(v)
	return _u
}

// SetNillableAdvertisedFrpHost sets the "advertised_frp_host" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableAdvertisedFrpHost(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetAdvertisedFrpHost(*v)
	}
	return _u
}

// ClearAdvertisedFrpHost clears the value of the "advertised_frp_host" field.
func (_u *NodeUpdateOne) ClearAdvertisedFrpHost() *NodeUpdateOne {
	_u.mutation.ClearAdvertisedFrpHost()
	return _u
}

// SetAdvertisedFrpPort sets the "advertised_frp_port" field.
func (_u *NodeUpdateOne) SetAdvertisedFrpPort(v int) *NodeUpdateOne {
	_u.mutation.ResetAdvertisedFrpPort()
	_u.mutation.SetAdvertisedFrpPort(v)
	return _u
}

// SetNillableAdvertisedFrpPort sets the "advertised_frp_port" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableAdvertisedFrpPort(v *int) *NodeUpdateOne {
	if v != nil {
		_u.SetAdvertisedFrpPort(*v)
	}
	return _u
}

// AddAdvertisedFrpPort adds value to the "advertised_frp_port" field.
func (_u *NodeUpdateOne) AddAdvertisedFrpPort(v int) *NodeUpdateOne {
	_u.mutation.AddAdvertisedFrpPort(v)
	return _u
}

// ClearAdvertisedFrpPort clears the value of the "advertised_frp_port" field.
func (_u *NodeUpdateOne) ClearAdvertisedFrpPort() *NodeUpdateOne {
	_u.mutation.ClearAdvertisedFrpPort()
	return _u
}

// SetHTTPIngressHost sets the "http_ingress_host" field.
func (_u *NodeUpdateOne) SetHTTPIngressHost(v string) *NodeUpdateOne {
	_u.mutation.SetHTTPIngressHost(v)
	return _u
}

// SetNillableHTTPIngressHost sets the "http_ingress_host" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableHTTPIngressHost(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetHTTPIngressHost(*v)
	}
	return _u
}

// ClearHTTPIngressHost clears the value of the "http_ingress_host" field.
func (_u *NodeUpdateOne) ClearHTTPIngressHost() *NodeUpdateOne {
	_u.mutation.ClearHTTPIngressHost()
	return _u
}

// SetHTTPIngressPort sets the "http_ingress_port" field.
func (_u *NodeUpdateOne) SetHTTPIngressPort(v int) *NodeUpdateOne {
	_u.mutation.ResetHTTPIngressPort()
	_u.mutation.SetHTTPIngressPort(v)
	return _u
}

// SetNillableHTTPIngressPort sets the "http_ingress_port" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableHTTPIngressPort(v *int) *NodeUpdateOne {
	if v != nil {
		_u.SetHTTPIngressPort(*v)
	}
	return _u
}

// AddHTTPIngressPort adds value to the "http_ingress_port" field.
func (_u *NodeUpdateOne) AddHTTPIngressPort(v int) *NodeUpdateOne {
	_u.mutation.AddHTTPIngressPort(v)
	return _u
}

// ClearHTTPIngressPort clears the value of the "http_ingress_port" field.
func (_u *NodeUpdateOne) ClearHTTPIngressPort() *NodeUpdateOne {
	_u.mutation.ClearHTTPIngressPort()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NodeUpdateOne) SetCreatedAt(v string) *NodeUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableCreatedAt(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdateOne) SetUpdatedAt(v string) *NodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableUpdatedAt(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddClientIDs adds the "clients" edge to the ServerClient entity by IDs.
func (_u *NodeUpdateOne) AddClientIDs(ids ...string) *NodeUpdateOne {
	_u.mutation.AddClientIDs(ids...)
	return _u
}

// AddClients adds the "clients" edges to the ServerClient entity.
func (_u *NodeUpdateOne) AddClients(v ...*ServerClient) *NodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientIDs(ids...)
}

// AddPendingClientIDs adds the "pending_clients" edge to the ServerClient entity by IDs.
func (_u *NodeUpdateOne) AddPendingClientIDs(ids ...string) *NodeUpdateOne {
	_u.mutation.AddPendingClientIDs(ids...)
	return _u
}

// AddPendingClients adds the "pending_clients" edges to the ServerClient entity.
func (_u *NodeUpdateOne) AddPendingClients(v ...*ServerClient) *NodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPendingClientIDs(ids...)
}

// AddAppliedClientIDs adds the "applied_clients" edge to the ServerClient entity by IDs.
func (_u *NodeUpdateOne) AddAppliedClientIDs(ids ...string) *NodeUpdateOne {
	_u.mutation.AddAppliedClientIDs(ids...)
	return _u
}

// AddAppliedClients adds the "applied_clients" edges to the ServerClient entity.
func (_u *NodeUpdateOne) AddAppliedClients(v ...*ServerClient) *NodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAppliedClientIDs(ids...)
}

// AddTunnelIDs adds the "tunnels" edge to the Tunnel entity by IDs.
func (_u *NodeUpdateOne) AddTunnelIDs(ids ...string) *NodeUpdateOne {
	_u.mutation.AddTunnelIDs(ids...)
	return _u
}

// AddTunnels adds the "tunnels" edges to the Tunnel entity.
func (_u *NodeUpdateOne) AddTunnels(v ...*Tunnel) *NodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTunnelIDs(ids...)
}

// SetRemoteNodeID sets the "remote_node" edge to the RemoteNode entity by ID.
func (_u *NodeUpdateOne) SetRemoteNodeID(id int) *NodeUpdateOne {
	_u.mutation.SetRemoteNodeID(id)
	return _u
}

// SetNillableRemoteNodeID sets the "remote_node" edge to the RemoteNode entity by ID if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableRemoteNodeID(id *int) *NodeUpdateOne {
	if id != nil {
		_u = _u.SetRemoteNodeID(*id)
	}
	return _u
}

// SetRemoteNode sets the "remote_node" edge to the RemoteNode entity.
func (_u *NodeUpdateOne) SetRemoteNode(v *RemoteNode) *NodeUpdateOne {
	return _u.SetRemoteNodeID(v.ID)
}

// SetPortPoolID sets the "port_pool" edge to the NodePortPool entity by ID.
func (_u *NodeUpdateOne) SetPortPoolID(id int) *NodeUpdateOne {
	_u.mutation.SetPortPoolID(id)
	return _u
}

// SetNillablePortPoolID sets the "port_pool" edge to the NodePortPool entity by ID if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePortPoolID(id *int) *NodeUpdateOne {
	if id != nil {
		_u = _u.SetPortPoolID(*id)
	}
	return _u
}

// SetPortPool sets the "port_pool" edge to the NodePortPool entity.
func (_u *NodeUpdateOne) SetPortPool(v *NodePortPool) *NodeUpdateOne {
	return _u.SetPortPoolID(v.ID)
}

// SetManagementCandidateID sets the "management_candidate" edge to the NodeManagementCandidate entity by ID.
func (_u *NodeUpdateOne) SetManagementCandidateID(id int) *NodeUpdateOne {
	_u.mutation.SetManagementCandidateID(id)
	return _u
}

// SetNillableManagementCandidateID sets the "management_candidate" edge to the NodeManagementCandidate entity by ID if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableManagementCandidateID(id *int) *NodeUpdateOne {
	if id != nil {
		_u = _u.SetManagementCandidateID(*id)
	}
	return _u
}

// SetManagementCandidate sets the "management_candidate" edge to the NodeManagementCandidate entity.
func (_u *NodeUpdateOne) SetManagementCandidate(v *NodeManagementCandidate) *NodeUpdateOne {
	return _u.SetManagementCandidateID(v.ID)
}

// SetObservationID sets the "observation" edge to the NodeObservation entity by ID.
func (_u *NodeUpdateOne) SetObservationID(id int) *NodeUpdateOne {
	_u.mutation.SetObservationID(id)
	return _u
}

// SetNillableObservationID sets the "observation" edge to the NodeObservation entity by ID if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableObservationID(id *int) *NodeUpdateOne {
	if id != nil {
		_u = _u.SetObservationID(*id)
	}
	return _u
}

// SetObservation sets the "observation" edge to the NodeObservation entity.
func (_u *NodeUpdateOne) SetObservation(v *NodeObservation) *NodeUpdateOne {
	return _u.SetObservationID(v.ID)
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// ClearClients clears all "clients" edges to the ServerClient entity.
func (_u *NodeUpdateOne) ClearClients() *NodeUpdateOne {
	_u.mutation.ClearClients()
	return _u
}

// RemoveClientIDs removes the "clients" edge to ServerClient entities by IDs.
func (_u *NodeUpdateOne) RemoveClientIDs(ids ...string) *NodeUpdateOne {
	_u.mutation.RemoveClientIDs(ids...)
	return _u
}

// RemoveClients removes "clients" edges to ServerClient entities.
func (_u *NodeUpdateOne) RemoveClients(v ...*ServerClient) *NodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientIDs(ids...)
}

// ClearPendingClients clears all "pending_clients" edges to the ServerClient entity.
func (_u *NodeUpdateOne) ClearPendingClients() *NodeUpdateOne {
	_u.mutation.ClearPendingClients()
	return _u
}

// RemovePendingClientIDs removes the "pending_clients" edge to ServerClient entities by IDs.
func (_u *NodeUpdateOne) RemovePendingClientIDs(ids ...string) *NodeUpdateOne {
	_u.mutation.RemovePendingClientIDs(ids...)
	return _u
}

// RemovePendingClients removes "pending_clients" edges to ServerClient entities.
func (_u *NodeUpdateOne) RemovePendingClients(v ...*ServerClient) *NodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePendingClientIDs(ids...)
}

// ClearAppliedClients clears all "applied_clients" edges to the ServerClient entity.
func (_u *NodeUpdateOne) ClearAppliedClients() *NodeUpdateOne {
	_u.mutation.ClearAppliedClients()
	return _u
}

// RemoveAppliedClientIDs removes the "applied_clients" edge to ServerClient entities by IDs.
func (_u *NodeUpdateOne) RemoveAppliedClientIDs(ids ...string) *NodeUpdateOne {
	_u.mutation.RemoveAppliedClientIDs(ids...)
	return _u
}

// RemoveAppliedClients removes "applied_clients" edges to ServerClient entities.
func (_u *NodeUpdateOne) RemoveAppliedClients(v ...*ServerClient) *NodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAppliedClientIDs(ids...)
}

// ClearTunnels clears all "tunnels" edges to the Tunnel entity.
func (_u *NodeUpdateOne) ClearTunnels() *NodeUpdateOne {
	_u.mutation.ClearTunnels()
	return _u
}

// RemoveTunnelIDs removes the "tunnels" edge to Tunnel entities by IDs.
func (_u *NodeUpdateOne) RemoveTunnelIDs(ids ...string) *NodeUpdateOne {
	_u.mutation.RemoveTunnelIDs(ids...)
	return _u
}

// RemoveTunnels removes "tunnels" edges to Tunnel entities.
func (_u *NodeUpdateOne) RemoveTunnels(v ...*Tunnel) *NodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTunnelIDs(ids...)
}

// ClearRemoteNode clears the "remote_node" edge to the RemoteNode entity.
func (_u *NodeUpdateOne) ClearRemoteNode() *NodeUpdateOne {
	_u.mutation.ClearRemoteNode()
	return _u
}

// ClearPortPool clears the "port_pool" edge to the NodePortPool entity.
func (_u *NodeUpdateOne) ClearPortPool() *NodeUpdateOne {
	_u.mutation.ClearPortPool()
	return _u
}

// ClearManagementCandidate clears the "management_candidate" edge to the NodeManagementCandidate entity.
func (_u *NodeUpdateOne) ClearManagementCandidate() *NodeUpdateOne {
	_u.mutation.ClearManagementCandidate()
	return _u
}

// ClearObservation clears the "observation" edge to the NodeObservation entity.
func (_u *NodeUpdateOne) ClearObservation() *NodeUpdateOne {
	_u.mutation.ClearObservation()
	return _u
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := node.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`server: validator failed for field "Node.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lifecycle(); ok {
		if err := node.LifecycleValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle", err: fmt.Errorf(`server: validator failed for field "Node.lifecycle": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`server: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("server: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(node.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Lifecycle(); ok {
		_spec.SetField(node.FieldLifecycle, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AdvertisedFrpHost(); ok {
		_spec.SetField(node.FieldAdvertisedFrpHost, field.TypeString, value)
	}
	if _u.mutation.AdvertisedFrpHostCleared() {
		_spec.ClearField(node.FieldAdvertisedFrpHost, field.TypeString)
	}
	if value, ok := _u.mutation.AdvertisedFrpPort(); ok {
		_spec.SetField(node.FieldAdvertisedFrpPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdvertisedFrpPort(); ok {
		_spec.AddField(node.FieldAdvertisedFrpPort, field.TypeInt, value)
	}
	if _u.mutation.AdvertisedFrpPortCleared() {
		_spec.ClearField(node.FieldAdvertisedFrpPort, field.TypeInt)
	}
	if value, ok := _u.mutation.HTTPIngressHost(); ok {
		_spec.SetField(node.FieldHTTPIngressHost, field.TypeString, value)
	}
	if _u.mutation.HTTPIngressHostCleared() {
		_spec.ClearField(node.FieldHTTPIngressHost, field.TypeString)
	}
	if value, ok := _u.mutation.HTTPIngressPort(); ok {
		_spec.SetField(node.FieldHTTPIngressPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPIngressPort(); ok {
		_spec.AddField(node.FieldHTTPIngressPort, field.TypeInt, value)
	}
	if _u.mutation.HTTPIngressPortCleared() {
		_spec.ClearField(node.FieldHTTPIngressPort, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeString, value)
	}
	if _u.mutation.ClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ClientsTable,
			Columns: []string{node.ClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientsIDs(); len(nodes) > 0 && !_u.mutation.ClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ClientsTable,
			Columns: []string{node.ClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.ClientsTable,
			Columns: []string{node.ClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PendingClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.PendingClientsTable,
			Columns: []string{node.PendingClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPendingClientsIDs(); len(nodes) > 0 && !_u.mutation.PendingClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.PendingClientsTable,
			Columns: []string{node.PendingClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PendingClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.PendingClientsTable,
			Columns: []string{node.PendingClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AppliedClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AppliedClientsTable,
			Columns: []string{node.AppliedClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAppliedClientsIDs(); len(nodes) > 0 && !_u.mutation.AppliedClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AppliedClientsTable,
			Columns: []string{node.AppliedClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppliedClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.AppliedClientsTable,
			Columns: []string{node.AppliedClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serverclient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TunnelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TunnelsTable,
			Columns: []string{node.TunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTunnelsIDs(); len(nodes) > 0 && !_u.mutation.TunnelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TunnelsTable,
			Columns: []string{node.TunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TunnelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TunnelsTable,
			Columns: []string{node.TunnelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RemoteNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.RemoteNodeTable,
			Columns: []string{node.RemoteNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remotenode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemoteNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.RemoteNodeTable,
			Columns: []string{node.RemoteNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(remotenode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PortPoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.PortPoolTable,
			Columns: []string{node.PortPoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeportpool.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PortPoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.PortPoolTable,
			Columns: []string{node.PortPoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeportpool.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagementCandidateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.ManagementCandidateTable,
			Columns: []string{node.ManagementCandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodemanagementcandidate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagementCandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.ManagementCandidateTable,
			Columns: []string{node.ManagementCandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodemanagementcandidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ObservationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.ObservationTable,
			Columns: []string{node.ObservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeobservation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ObservationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   node.ObservationTable,
			Columns: []string{node.ObservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeobservation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
