// Code generated by ent, DO NOT EDIT.

package server

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/server/node"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
	"github.com/hackycy/hackycy-cli/ent/server/remotenode"
)

// RemoteNodeUpdate is the builder for updating RemoteNode entities.
type RemoteNodeUpdate struct {
	config
	hooks    []Hook
	mutation *RemoteNodeMutation
}

// Where appends a list predicates to the RemoteNodeUpdate builder.
func (_u *RemoteNodeUpdate) Where(ps ...predicate.RemoteNode) *RemoteNodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *RemoteNodeUpdate) SetNodeID(v string) *RemoteNodeUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableNodeID(v *string) *RemoteNodeUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetNodePublicKey sets the "node_public_key" field.
func (_u *RemoteNodeUpdate) SetNodePublicKey(v string) *RemoteNodeUpdate {
	_u.mutation.SetNodePublicKey(v)
	return _u
}

// SetNillableNodePublicKey sets the "node_public_key" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableNodePublicKey(v *string) *RemoteNodeUpdate {
	if v != nil {
		_u.SetNodePublicKey(*v)
	}
	return _u
}

// SetManagementAddress sets the "management_address" field.
func (_u *RemoteNodeUpdate) SetManagementAddress(v string) *RemoteNodeUpdate {
	_u.mutation.SetManagementAddress(v)
	return _u
}

// SetNillableManagementAddress sets the "management_address" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableManagementAddress(v *string) *RemoteNodeUpdate {
	if v != nil {
		_u.SetManagementAddress(*v)
	}
	return _u
}

// SetFrpBindPort sets the "frp_bind_port" field.
func (_u *RemoteNodeUpdate) SetFrpBindPort(v int) *RemoteNodeUpdate {
	_u.mutation.ResetFrpBindPort()
	_u.mutation.SetFrpBindPort(v)
	return _u
}

// SetNillableFrpBindPort sets the "frp_bind_port" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableFrpBindPort(v *int) *RemoteNodeUpdate {
	if v != nil {
		_u.SetFrpBindPort(*v)
	}
	return _u
}

// AddFrpBindPort adds value to the "frp_bind_port" field.
func (_u *RemoteNodeUpdate) AddFrpBindPort(v int) *RemoteNodeUpdate {
	_u.mutation.AddFrpBindPort(v)
	return _u
}

// SetHTTPVhostPort sets the "http_vhost_port" field.
func (_u *RemoteNodeUpdate) SetHTTPVhostPort(v int) *RemoteNodeUpdate {
	_u.mutation.ResetHTTPVhostPort()
	_u.mutation.SetHTTPVhostPort(v)
	return _u
}

// SetNillableHTTPVhostPort sets the "http_vhost_port" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableHTTPVhostPort(v *int) *RemoteNodeUpdate {
	if v != nil {
		_u.SetHTTPVhostPort(*v)
	}
	return _u
}

// AddHTTPVhostPort adds value to the "http_vhost_port" field.
func (_u *RemoteNodeUpdate) AddHTTPVhostPort(v int) *RemoteNodeUpdate {
	_u.mutation.AddHTTPVhostPort(v)
	return _u
}

// SetPortStart sets the "port_start" field.
func (_u *RemoteNodeUpdate) SetPortStart(v int) *RemoteNodeUpdate {
	_u.mutation.ResetPortStart()
	_u.mutation.SetPortStart(v)
	return _u
}

// SetNillablePortStart sets the "port_start" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillablePortStart(v *int) *RemoteNodeUpdate {
	if v != nil {
		_u.SetPortStart(*v)
	}
	return _u
}

// AddPortStart adds value to the "port_start" field.
func (_u *RemoteNodeUpdate) AddPortStart(v int) *RemoteNodeUpdate {
	_u.mutation.AddPortStart(v)
	return _u
}

// SetPortEnd sets the "port_end" field.
func (_u *RemoteNodeUpdate) SetPortEnd(v int) *RemoteNodeUpdate {
	_u.mutation.ResetPortEnd()
	_u.mutation.SetPortEnd(v)
	return _u
}

// SetNillablePortEnd sets the "port_end" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillablePortEnd(v *int) *RemoteNodeUpdate {
	if v != nil {
		_u.SetPortEnd(*v)
	}
	return _u
}

// AddPortEnd adds value to the "port_end" field.
func (_u *RemoteNodeUpdate) AddPortEnd(v int) *RemoteNodeUpdate {
	_u.mutation.AddPortEnd(v)
	return _u
}

// SetDesiredRevision sets the "desired_revision" field.
func (_u *RemoteNodeUpdate) SetDesiredRevision(v int64) *RemoteNodeUpdate {
	_u.mutation.ResetDesiredRevision()
	_u.mutation.SetDesiredRevision(v)
	return _u
}

// SetNillableDesiredRevision sets the "desired_revision" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableDesiredRevision(v *int64) *RemoteNodeUpdate {
	if v != nil {
		_u.SetDesiredRevision(*v)
	}
	return _u
}

// AddDesiredRevision adds value to the "desired_revision" field.
func (_u *RemoteNodeUpdate) AddDesiredRevision(v int64) *RemoteNodeUpdate {
	_u.mutation.AddDesiredRevision(v)
	return _u
}

// SetDesiredHash sets the "desired_hash" field.
func (_u *RemoteNodeUpdate) SetDesiredHash(v string) *RemoteNodeUpdate {
	_u.mutation.SetDesiredHash(v)
	return _u
}

// SetNillableDesiredHash sets the "desired_hash" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableDesiredHash(v *string) *RemoteNodeUpdate {
	if v != nil {
		_u.SetDesiredHash(*v)
	}
	return _u
}

// ClearDesiredHash clears the value of the "desired_hash" field.
func (_u *RemoteNodeUpdate) ClearDesiredHash() *RemoteNodeUpdate {
	_u.mutation.ClearDesiredHash()
	return _u
}

// SetDesiredSnapshot sets the "desired_snapshot" field.
func (_u *RemoteNodeUpdate) SetDesiredSnapshot(v string) *RemoteNodeUpdate {
	_u.mutation.SetDesiredSnapshot(v)
	return _u
}

// SetNillableDesiredSnapshot sets the "desired_snapshot" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableDesiredSnapshot(v *string) *RemoteNodeUpdate {
	if v != nil {
		_u.SetDesiredSnapshot(*v)
	}
	return _u
}

// ClearDesiredSnapshot clears the value of the "desired_snapshot" field.
func (_u *RemoteNodeUpdate) ClearDesiredSnapshot() *RemoteNodeUpdate {
	_u.mutation.ClearDesiredSnapshot()
	return _u
}

// SetActiveToken sets the "active_token" field.
func (_u *RemoteNodeUpdate) SetActiveToken(v string) *RemoteNodeUpdate {
	_u.mutation.SetActiveToken(v)
	return _u
}

// SetNillableActiveToken sets the "active_token" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableActiveToken(v *string) *RemoteNodeUpdate {
	if v != nil {
		_u.SetActiveToken(*v)
	}
	return _u
}

// SetStagedToken sets the "staged_token" field.
func (_u *RemoteNodeUpdate) SetStagedToken(v string) *RemoteNodeUpdate {
	_u.mutation.SetStagedToken(v)
	return _u
}

// SetNillableStagedToken sets the "staged_token" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableStagedToken(v *string) *RemoteNodeUpdate {
	if v != nil {
		_u.SetStagedToken(*v)
	}
	return _u
}

// ClearStagedToken clears the value of the "staged_token" field.
func (_u *RemoteNodeUpdate) ClearStagedToken() *RemoteNodeUpdate {
	_u.mutation.ClearStagedToken()
	return _u
}

// SetStagedTokenRevision sets the "staged_token_revision" field.
func (_u *RemoteNodeUpdate) SetStagedTokenRevision(v int64) *RemoteNodeUpdate {
	_u.mutation.ResetStagedTokenRevision()
	_u.mutation.SetStagedTokenRevision(v)
	return _u
}

// SetNillableStagedTokenRevision sets the "staged_token_revision" field if the given value is not nil.
func (_u *RemoteNodeUpdate) SetNillableStagedTokenRevision(v *int64) *RemoteNodeUpdate {
	if v != nil {
		_u.SetStagedTokenRevision(*v)
	}
	return _u
}

// AddStagedTokenRevision adds value to the "staged_token_revision" field.
func (_u *RemoteNodeUpdate) AddStagedTokenRevision(v int64) *RemoteNodeUpdate {
	_u.mutation.AddStagedTokenRevision(v)
	return _u
}

// ClearStagedTokenRevision clears the value of the "staged_token_revision" field.
func (_u *RemoteNodeUpdate) ClearStagedTokenRevision() *RemoteNodeUpdate {
	_u.mutation.ClearStagedTokenRevision()
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *RemoteNodeUpdate) SetNode(v *Node) *RemoteNodeUpdate {
	return _u.SetNodeID(v.ID)
}

// Mutation returns the RemoteNodeMutation object of the builder.
func (_u *RemoteNodeUpdate) Mutation() *RemoteNodeMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *RemoteNodeUpdate) ClearNode() *RemoteNodeUpdate {
	_u.mutation.ClearNode()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RemoteNodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RemoteNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RemoteNodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RemoteNodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RemoteNodeUpdate) check() error {
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`server: clearing a required unique edge "RemoteNode.node"`)
	}
	return nil
}

func (_u *RemoteNodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(remotenode.Table, remotenode.Columns, sqlgraph.NewFieldSpec(remotenode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodePublicKey(); ok {
		_spec.SetField(remotenode.FieldNodePublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManagementAddress(); ok {
		_spec.SetField(remotenode.FieldManagementAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.FrpBindPort(); ok {
		_spec.SetField(remotenode.FieldFrpBindPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFrpBindPort(); ok {
		_spec.AddField(remotenode.FieldFrpBindPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HTTPVhostPort(); ok {
		_spec.SetField(remotenode.FieldHTTPVhostPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPVhostPort(); ok {
		_spec.AddField(remotenode.FieldHTTPVhostPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PortStart(); ok {
		_spec.SetField(remotenode.FieldPortStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPortStart(); ok {
		_spec.AddField(remotenode.FieldPortStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PortEnd(); ok {
		_spec.SetField(remotenode.FieldPortEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPortEnd(); ok {
		_spec.AddField(remotenode.FieldPortEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DesiredRevision(); ok {
		_spec.SetField(remotenode.FieldDesiredRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDesiredRevision(); ok {
		_spec.AddField(remotenode.FieldDesiredRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DesiredHash(); ok {
		_spec.SetField(remotenode.FieldDesiredHash, field.TypeString, value)
	}
	if _u.mutation.DesiredHashCleared() {
		_spec.ClearField(remotenode.FieldDesiredHash, field.TypeString)
	}
	if value, ok := _u.mutation.DesiredSnapshot(); ok {
		_spec.SetField(remotenode.FieldDesiredSnapshot, field.TypeString, value)
	}
	if _u.mutation.DesiredSnapshotCleared() {
		_spec.ClearField(remotenode.FieldDesiredSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.ActiveToken(); ok {
		_spec.SetField(remotenode.FieldActiveToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.StagedToken(); ok {
		_spec.SetField(remotenode.FieldStagedToken, field.TypeString, value)
	}
	if _u.mutation.StagedTokenCleared() {
		_spec.ClearField(remotenode.FieldStagedToken, field.TypeString)
	}
	if value, ok := _u.mutation.StagedTokenRevision(); ok {
		_spec.SetField(remotenode.FieldStagedTokenRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStagedTokenRevision(); ok {
		_spec.AddField(remotenode.FieldStagedTokenRevision, field.TypeInt64, value)
	}
	if _u.mutation.StagedTokenRevisionCleared() {
		_spec.ClearField(remotenode.FieldStagedTokenRevision, field.TypeInt64)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   remotenode.NodeTable,
			Columns: []string{remotenode.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   remotenode.NodeTable,
			Columns: []string{remotenode.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remotenode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RemoteNodeUpdateOne is the builder for updating a single RemoteNode entity.
type RemoteNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RemoteNodeMutation
}

// SetNodeID sets the "node_id" field.
func (_u *RemoteNodeUpdateOne) SetNodeID(v string) *RemoteNodeUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableNodeID(v *string) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetNodePublicKey sets the "node_public_key" field.
func (_u *RemoteNodeUpdateOne) SetNodePublicKey(v string) *RemoteNodeUpdateOne {
	_u.mutation.SetNodePublicKey(v)
	return _u
}

// SetNillableNodePublicKey sets the "node_public_key" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableNodePublicKey(v *string) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetNodePublicKey(*v)
	}
	return _u
}

// SetManagementAddress sets the "management_address" field.
func (_u *RemoteNodeUpdateOne) SetManagementAddress(v string) *RemoteNodeUpdateOne {
	_u.mutation.SetManagementAddress(v)
	return _u
}

// SetNillableManagementAddress sets the "management_address" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableManagementAddress(v *string) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetManagementAddress(*v)
	}
	return _u
}

// SetFrpBindPort sets the "frp_bind_port" field.
func (_u *RemoteNodeUpdateOne) SetFrpBindPort(v int) *RemoteNodeUpdateOne {
	_u.mutation.ResetFrpBindPort()
	_u.mutation.SetFrpBindPort(v)
	return _u
}

// SetNillableFrpBindPort sets the "frp_bind_port" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableFrpBindPort(v *int) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetFrpBindPort(*v)
	}
	return _u
}

// AddFrpBindPort adds value to the "frp_bind_port" field.
func (_u *RemoteNodeUpdateOne) AddFrpBindPort(v int) *RemoteNodeUpdateOne {
	_u.mutation.AddFrpBindPort(v)
	return _u
}

// SetHTTPVhostPort sets the "http_vhost_port" field.
func (_u *RemoteNodeUpdateOne) SetHTTPVhostPort(v int) *RemoteNodeUpdateOne {
	_u.mutation.ResetHTTPVhostPort()
	_u.mutation.SetHTTPVhostPort(v)
	return _u
}

// SetNillableHTTPVhostPort sets the "http_vhost_port" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableHTTPVhostPort(v *int) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetHTTPVhostPort(*v)
	}
	return _u
}

// AddHTTPVhostPort adds value to the "http_vhost_port" field.
func (_u *RemoteNodeUpdateOne) AddHTTPVhostPort(v int) *RemoteNodeUpdateOne {
	_u.mutation.AddHTTPVhostPort(v)
	return _u
}

// SetPortStart sets the "port_start" field.
func (_u *RemoteNodeUpdateOne) SetPortStart(v int) *RemoteNodeUpdateOne {
	_u.mutation.ResetPortStart()
	_u.mutation.SetPortStart(v)
	return _u
}

// SetNillablePortStart sets the "port_start" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillablePortStart(v *int) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetPortStart(*v)
	}
	return _u
}

// AddPortStart adds value to the "port_start" field.
func (_u *RemoteNodeUpdateOne) AddPortStart(v int) *RemoteNodeUpdateOne {
	_u.mutation.AddPortStart(v)
	return _u
}

// SetPortEnd sets the "port_end" field.
func (_u *RemoteNodeUpdateOne) SetPortEnd(v int) *RemoteNodeUpdateOne {
	_u.mutation.ResetPortEnd()
	_u.mutation.SetPortEnd(v)
	return _u
}

// SetNillablePortEnd sets the "port_end" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillablePortEnd(v *int) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetPortEnd(*v)
	}
	return _u
}

// AddPortEnd adds value to the "port_end" field.
func (_u *RemoteNodeUpdateOne) AddPortEnd(v int) *RemoteNodeUpdateOne {
	_u.mutation.AddPortEnd(v)
	return _u
}

// SetDesiredRevision sets the "desired_revision" field.
func (_u *RemoteNodeUpdateOne) SetDesiredRevision(v int64) *RemoteNodeUpdateOne {
	_u.mutation.ResetDesiredRevision()
	_u.mutation.SetDesiredRevision(v)
	return _u
}

// SetNillableDesiredRevision sets the "desired_revision" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableDesiredRevision(v *int64) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetDesiredRevision(*v)
	}
	return _u
}

// AddDesiredRevision adds value to the "desired_revision" field.
func (_u *RemoteNodeUpdateOne) AddDesiredRevision(v int64) *RemoteNodeUpdateOne {
	_u.mutation.AddDesiredRevision(v)
	return _u
}

// SetDesiredHash sets the "desired_hash" field.
func (_u *RemoteNodeUpdateOne) SetDesiredHash(v string) *RemoteNodeUpdateOne {
	_u.mutation.SetDesiredHash(v)
	return _u
}

// SetNillableDesiredHash sets the "desired_hash" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableDesiredHash(v *string) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetDesiredHash(*v)
	}
	return _u
}

// ClearDesiredHash clears the value of the "desired_hash" field.
func (_u *RemoteNodeUpdateOne) ClearDesiredHash() *RemoteNodeUpdateOne {
	_u.mutation.ClearDesiredHash()
	return _u
}

// SetDesiredSnapshot sets the "desired_snapshot" field.
func (_u *RemoteNodeUpdateOne) SetDesiredSnapshot(v string) *RemoteNodeUpdateOne {
	_u.mutation.SetDesiredSnapshot(v)
	return _u
}

// SetNillableDesiredSnapshot sets the "desired_snapshot" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableDesiredSnapshot(v *string) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetDesiredSnapshot(*v)
	}
	return _u
}

// ClearDesiredSnapshot clears the value of the "desired_snapshot" field.
func (_u *RemoteNodeUpdateOne) ClearDesiredSnapshot() *RemoteNodeUpdateOne {
	_u.mutation.ClearDesiredSnapshot()
	return _u
}

// SetActiveToken sets the "active_token" field.
func (_u *RemoteNodeUpdateOne) SetActiveToken(v string) *RemoteNodeUpdateOne {
	_u.mutation.SetActiveToken(v)
	return _u
}

// SetNillableActiveToken sets the "active_token" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableActiveToken(v *string) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetActiveToken(*v)
	}
	return _u
}

// SetStagedToken sets the "staged_token" field.
func (_u *RemoteNodeUpdateOne) SetStagedToken(v string) *RemoteNodeUpdateOne {
	_u.mutation.SetStagedToken(v)
	return _u
}

// SetNillableStagedToken sets the "staged_token" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableStagedToken(v *string) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetStagedToken(*v)
	}
	return _u
}

// ClearStagedToken clears the value of the "staged_token" field.
func (_u *RemoteNodeUpdateOne) ClearStagedToken() *RemoteNodeUpdateOne {
	_u.mutation.ClearStagedToken()
	return _u
}

// SetStagedTokenRevision sets the "staged_token_revision" field.
func (_u *RemoteNodeUpdateOne) SetStagedTokenRevision(v int64) *RemoteNodeUpdateOne {
	_u.mutation.ResetStagedTokenRevision()
	_u.mutation.SetStagedTokenRevision(v)
	return _u
}

// SetNillableStagedTokenRevision sets the "staged_token_revision" field if the given value is not nil.
func (_u *RemoteNodeUpdateOne) SetNillableStagedTokenRevision(v *int64) *RemoteNodeUpdateOne {
	if v != nil {
		_u.SetStagedTokenRevision(*v)
	}
	return _u
}

// AddStagedTokenRevision adds value to the "staged_token_revision" field.
func (_u *RemoteNodeUpdateOne) AddStagedTokenRevision(v int64) *RemoteNodeUpdateOne {
	_u.mutation.AddStagedTokenRevision(v)
	return _u
}

// ClearStagedTokenRevision clears the value of the "staged_token_revision" field.
func (_u *RemoteNodeUpdateOne) ClearStagedTokenRevision() *RemoteNodeUpdateOne {
	_u.mutation.ClearStagedTokenRevision()
	return _u
}

// SetNode sets the "node" edge to the Node entity.
func (_u *RemoteNodeUpdateOne) SetNode(v *Node) *RemoteNodeUpdateOne {
	return _u.SetNodeID(v.ID)
}

// Mutation returns the RemoteNodeMutation object of the builder.
func (_u *RemoteNodeUpdateOne) Mutation() *RemoteNodeMutation {
	return _u.mutation
}

// ClearNode clears the "node" edge to the Node entity.
func (_u *RemoteNodeUpdateOne) ClearNode() *RemoteNodeUpdateOne {
	_u.mutation.ClearNode()
	return _u
}

// Where appends a list predicates to the RemoteNodeUpdate builder.
func (_u *RemoteNodeUpdateOne) Where(ps ...predicate.RemoteNode) *RemoteNodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RemoteNodeUpdateOne) Select(field string, fields ...string) *RemoteNodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RemoteNode entity.
func (_u *RemoteNodeUpdateOne) Save(ctx context.Context) (*RemoteNode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RemoteNodeUpdateOne) SaveX(ctx context.Context) *RemoteNode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RemoteNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RemoteNodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RemoteNodeUpdateOne) check() error {
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`server: clearing a required unique edge "RemoteNode.node"`)
	}
	return nil
}

func (_u *RemoteNodeUpdateOne) sqlSave(ctx context.Context) (_node *RemoteNode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(remotenode.Table, remotenode.Columns, sqlgraph.NewFieldSpec(remotenode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`server: missing "RemoteNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, remotenode.FieldID)
		for _, f := range fields {
			if !remotenode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("server: invalid field %q for query", f)}
			}
			if f != remotenode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodePublicKey(); ok {
		_spec.SetField(remotenode.FieldNodePublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManagementAddress(); ok {
		_spec.SetField(remotenode.FieldManagementAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.FrpBindPort(); ok {
		_spec.SetField(remotenode.FieldFrpBindPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFrpBindPort(); ok {
		_spec.AddField(remotenode.FieldFrpBindPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HTTPVhostPort(); ok {
		_spec.SetField(remotenode.FieldHTTPVhostPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPVhostPort(); ok {
		_spec.AddField(remotenode.FieldHTTPVhostPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PortStart(); ok {
		_spec.SetField(remotenode.FieldPortStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPortStart(); ok {
		_spec.AddField(remotenode.FieldPortStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PortEnd(); ok {
		_spec.SetField(remotenode.FieldPortEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPortEnd(); ok {
		_spec.AddField(remotenode.FieldPortEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DesiredRevision(); ok {
		_spec.SetField(remotenode.FieldDesiredRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDesiredRevision(); ok {
		_spec.AddField(remotenode.FieldDesiredRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DesiredHash(); ok {
		_spec.SetField(remotenode.FieldDesiredHash, field.TypeString, value)
	}
	if _u.mutation.DesiredHashCleared() {
		_spec.ClearField(remotenode.FieldDesiredHash, field.TypeString)
	}
	if value, ok := _u.mutation.DesiredSnapshot(); ok {
		_spec.SetField(remotenode.FieldDesiredSnapshot, field.TypeString, value)
	}
	if _u.mutation.DesiredSnapshotCleared() {
		_spec.ClearField(remotenode.FieldDesiredSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.ActiveToken(); ok {
		_spec.SetField(remotenode.FieldActiveToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.StagedToken(); ok {
		_spec.SetField(remotenode.FieldStagedToken, field.TypeString, value)
	}
	if _u.mutation.StagedTokenCleared() {
		_spec.ClearField(remotenode.FieldStagedToken, field.TypeString)
	}
	if value, ok := _u.mutation.StagedTokenRevision(); ok {
		_spec.SetField(remotenode.FieldStagedTokenRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStagedTokenRevision(); ok {
		_spec.AddField(remotenode.FieldStagedTokenRevision, field.TypeInt64, value)
	}
	if _u.mutation.StagedTokenRevisionCleared() {
		_spec.ClearField(remotenode.FieldStagedTokenRevision, field.TypeInt64)
	}
	if _u.mutation.NodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   remotenode.NodeTable,
			Columns: []string{remotenode.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   remotenode.NodeTable,
			Columns: []string{remotenode.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RemoteNode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remotenode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
