// Code generated by ent, DO NOT EDIT.

package server

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hackycy/hackycy-cli/ent/server/node"
	"github.com/hackycy/hackycy-cli/ent/server/remotenode"
)

// RemoteNode is the model entity for the RemoteNode schema.
type RemoteNode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID string `json:"node_id,omitempty"`
	// NodePublicKey holds the value of the "node_public_key" field.
	NodePublicKey string `json:"node_public_key,omitempty"`
	// ManagementAddress holds the value of the "management_address" field.
	ManagementAddress string `json:"management_address,omitempty"`
	// FrpBindPort holds the value of the "frp_bind_port" field.
	FrpBindPort int `json:"frp_bind_port,omitempty"`
	// HTTPVhostPort holds the value of the "http_vhost_port" field.
	HTTPVhostPort int `json:"http_vhost_port,omitempty"`
	// PortStart holds the value of the "port_start" field.
	PortStart int `json:"port_start,omitempty"`
	// PortEnd holds the value of the "port_end" field.
	PortEnd int `json:"port_end,omitempty"`
	// DesiredRevision holds the value of the "desired_revision" field.
	DesiredRevision int64 `json:"desired_revision,omitempty"`
	// DesiredHash holds the value of the "desired_hash" field.
	DesiredHash *string `json:"desired_hash,omitempty"`
	// DesiredSnapshot holds the value of the "desired_snapshot" field.
	DesiredSnapshot *string `json:"desired_snapshot,omitempty"`
	// ActiveToken holds the value of the "active_token" field.
	ActiveToken string `json:"active_token,omitempty"`
	// StagedToken holds the value of the "staged_token" field.
	StagedToken *string `json:"staged_token,omitempty"`
	// StagedTokenRevision holds the value of the "staged_token_revision" field.
	StagedTokenRevision *int64 `json:"staged_token_revision,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RemoteNodeQuery when eager-loading is set.
	Edges        RemoteNodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RemoteNodeEdges holds the relations/edges for other nodes in the graph.
type RemoteNodeEdges struct {
	// Node holds the value of the node edge.
	Node *Node `json:"node,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NodeOrErr returns the Node value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RemoteNodeEdges) NodeOrErr() (*Node, error) {
	if e.Node != nil {
		return e.Node, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "node"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RemoteNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case remotenode.FieldID, remotenode.FieldFrpBindPort, remotenode.FieldHTTPVhostPort, remotenode.FieldPortStart, remotenode.FieldPortEnd, remotenode.FieldDesiredRevision, remotenode.FieldStagedTokenRevision:
			values[i] = new(sql.NullInt64)
		case remotenode.FieldNodeID, remotenode.FieldNodePublicKey, remotenode.FieldManagementAddress, remotenode.FieldDesiredHash, remotenode.FieldDesiredSnapshot, remotenode.FieldActiveToken, remotenode.FieldStagedToken:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RemoteNode fields.
func (_m *RemoteNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case remotenode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case remotenode.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case remotenode.FieldNodePublicKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_public_key", values[i])
			} else if value.Valid {
				_m.NodePublicKey = value.String
			}
		case remotenode.FieldManagementAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field management_address", values[i])
			} else if value.Valid {
				_m.ManagementAddress = value.String
			}
		case remotenode.FieldFrpBindPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field frp_bind_port", values[i])
			} else if value.Valid {
				_m.FrpBindPort = int(value.Int64)
			}
		case remotenode.FieldHTTPVhostPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_vhost_port", values[i])
			} else if value.Valid {
				_m.HTTPVhostPort = int(value.Int64)
			}
		case remotenode.FieldPortStart:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port_start", values[i])
			} else if value.Valid {
				_m.PortStart = int(value.Int64)
			}
		case remotenode.FieldPortEnd:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port_end", values[i])
			} else if value.Valid {
				_m.PortEnd = int(value.Int64)
			}
		case remotenode.FieldDesiredRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field desired_revision", values[i])
			} else if value.Valid {
				_m.DesiredRevision = value.Int64
			}
		case remotenode.FieldDesiredHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field desired_hash", values[i])
			} else if value.Valid {
				_m.DesiredHash = new(string)
				*_m.DesiredHash = value.String
			}
		case remotenode.FieldDesiredSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field desired_snapshot", values[i])
			} else if value.Valid {
				_m.DesiredSnapshot = new(string)
				*_m.DesiredSnapshot = value.String
			}
		case remotenode.FieldActiveToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field active_token", values[i])
			} else if value.Valid {
				_m.ActiveToken = value.String
			}
		case remotenode.FieldStagedToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field staged_token", values[i])
			} else if value.Valid {
				_m.StagedToken = new(string)
				*_m.StagedToken = value.String
			}
		case remotenode.FieldStagedTokenRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field staged_token_revision", values[i])
			} else if value.Valid {
				_m.StagedTokenRevision = new(int64)
				*_m.StagedTokenRevision = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RemoteNode.
// This includes values selected through modifiers, order, etc.
func (_m *RemoteNode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNode queries the "node" edge of the RemoteNode entity.
func (_m *RemoteNode) QueryNode() *NodeQuery {
	return NewRemoteNodeClient(_m.config).QueryNode(_m)
}

// Update returns a builder for updating this RemoteNode.
// Note that you need to call RemoteNode.Unwrap() before calling this method if this RemoteNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RemoteNode) Update() *RemoteNodeUpdateOne {
	return NewRemoteNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RemoteNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RemoteNode) Unwrap() *RemoteNode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("server: RemoteNode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RemoteNode) String() string {
	var builder strings.Builder
	builder.WriteString("RemoteNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	builder.WriteString("node_public_key=")
	builder.WriteString(_m.NodePublicKey)
	builder.WriteString(", ")
	builder.WriteString("management_address=")
	builder.WriteString(_m.ManagementAddress)
	builder.WriteString(", ")
	builder.WriteString("frp_bind_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.FrpBindPort))
	builder.WriteString(", ")
	builder.WriteString("http_vhost_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.HTTPVhostPort))
	builder.WriteString(", ")
	builder.WriteString("port_start=")
	builder.WriteString(fmt.Sprintf("%v", _m.PortStart))
	builder.WriteString(", ")
	builder.WriteString("port_end=")
	builder.WriteString(fmt.Sprintf("%v", _m.PortEnd))
	builder.WriteString(", ")
	builder.WriteString("desired_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.DesiredRevision))
	builder.WriteString(", ")
	if v := _m.DesiredHash; v != nil {
		builder.WriteString("desired_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DesiredSnapshot; v != nil {
		builder.WriteString("desired_snapshot=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("active_token=")
	builder.WriteString(_m.ActiveToken)
	builder.WriteString(", ")
	if v := _m.StagedToken; v != nil {
		builder.WriteString("staged_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StagedTokenRevision; v != nil {
		builder.WriteString("staged_token_revision=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RemoteNodes is a parsable slice of RemoteNode.
type RemoteNodes []*RemoteNode
