// Code generated by ent, DO NOT EDIT.

package server

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/server/node"
	"github.com/hackycy/hackycy-cli/ent/server/remotenode"
)

// RemoteNodeCreate is the builder for creating a RemoteNode entity.
type RemoteNodeCreate struct {
	config
	mutation *RemoteNodeMutation
	hooks    []Hook
}

// SetNodeID sets the "node_id" field.
func (_c *RemoteNodeCreate) SetNodeID(v string) *RemoteNodeCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetNodePublicKey sets the "node_public_key" field.
func (_c *RemoteNodeCreate) SetNodePublicKey(v string) *RemoteNodeCreate {
	_c.mutation.SetNodePublicKey(v)
	return _c
}

// SetManagementAddress sets the "management_address" field.
func (_c *RemoteNodeCreate) SetManagementAddress(v string) *RemoteNodeCreate {
	_c.mutation.SetManagementAddress(v)
	return _c
}

// SetFrpBindPort sets the "frp_bind_port" field.
func (_c *RemoteNodeCreate) SetFrpBindPort(v int) *RemoteNodeCreate {
	_c.mutation.SetFrpBindPort(v)
	return _c
}

// SetHTTPVhostPort sets the "http_vhost_port" field.
func (_c *RemoteNodeCreate) SetHTTPVhostPort(v int) *RemoteNodeCreate {
	_c.mutation.SetHTTPVhostPort(v)
	return _c
}

// SetPortStart sets the "port_start" field.
func (_c *RemoteNodeCreate) SetPortStart(v int) *RemoteNodeCreate {
	_c.mutation.SetPortStart(v)
	return _c
}

// SetPortEnd sets the "port_end" field.
func (_c *RemoteNodeCreate) SetPortEnd(v int) *RemoteNodeCreate {
	_c.mutation.SetPortEnd(v)
	return _c
}

// SetDesiredRevision sets the "desired_revision" field.
func (_c *RemoteNodeCreate) SetDesiredRevision(v int64) *RemoteNodeCreate {
	_c.mutation.SetDesiredRevision(v)
	return _c
}

// SetNillableDesiredRevision sets the "desired_revision" field if the given value is not nil.
func (_c *RemoteNodeCreate) SetNillableDesiredRevision(v *int64) *RemoteNodeCreate {
	if v != nil {
		_c.SetDesiredRevision(*v)
	}
	return _c
}

// SetDesiredHash sets the "desired_hash" field.
func (_c *RemoteNodeCreate) SetDesiredHash(v string) *RemoteNodeCreate {
	_c.mutation.SetDesiredHash(v)
	return _c
}

// SetNillableDesiredHash sets the "desired_hash" field if the given value is not nil.
func (_c *RemoteNodeCreate) SetNillableDesiredHash(v *string) *RemoteNodeCreate {
	if v != nil {
		_c.SetDesiredHash(*v)
	}
	return _c
}

// SetDesiredSnapshot sets the "desired_snapshot" field.
func (_c *RemoteNodeCreate) SetDesiredSnapshot(v string) *RemoteNodeCreate {
	_c.mutation.SetDesiredSnapshot(v)
	return _c
}

// SetNillableDesiredSnapshot sets the "desired_snapshot" field if the given value is not nil.
func (_c *RemoteNodeCreate) SetNillableDesiredSnapshot(v *string) *RemoteNodeCreate {
	if v != nil {
		_c.SetDesiredSnapshot(*v)
	}
	return _c
}

// SetActiveToken sets the "active_token" field.
func (_c *RemoteNodeCreate) SetActiveToken(v string) *RemoteNodeCreate {
	_c.mutation.SetActiveToken(v)
	return _c
}

// SetStagedToken sets the "staged_token" field.
func (_c *RemoteNodeCreate) SetStagedToken(v string) *RemoteNodeCreate {
	_c.mutation.SetStagedToken(v)
	return _c
}

// SetNillableStagedToken sets the "staged_token" field if the given value is not nil.
func (_c *RemoteNodeCreate) SetNillableStagedToken(v *string) *RemoteNodeCreate {
	if v != nil {
		_c.SetStagedToken(*v)
	}
	return _c
}

// SetStagedTokenRevision sets the "staged_token_revision" field.
func (_c *RemoteNodeCreate) SetStagedTokenRevision(v int64) *RemoteNodeCreate {
	_c.mutation.SetStagedTokenRevision(v)
	return _c
}

// SetNillableStagedTokenRevision sets the "staged_token_revision" field if the given value is not nil.
func (_c *RemoteNodeCreate) SetNillableStagedTokenRevision(v *int64) *RemoteNodeCreate {
	if v != nil {
		_c.SetStagedTokenRevision(*v)
	}
	return _c
}

// SetNode sets the "node" edge to the Node entity.
func (_c *RemoteNodeCreate) SetNode(v *Node) *RemoteNodeCreate {
	return _c.SetNodeID(v.ID)
}

// Mutation returns the RemoteNodeMutation object of the builder.
func (_c *RemoteNodeCreate) Mutation() *RemoteNodeMutation {
	return _c.mutation
}

// Save creates the RemoteNode in the database.
func (_c *RemoteNodeCreate) Save(ctx context.Context) (*RemoteNode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RemoteNodeCreate) SaveX(ctx context.Context) *RemoteNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemoteNodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemoteNodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RemoteNodeCreate) defaults() {
	if _, ok := _c.mutation.DesiredRevision(); !ok {
		v := remotenode.DefaultDesiredRevision
		_c.mutation.SetDesiredRevision(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RemoteNodeCreate) check() error {
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`server: missing required field "RemoteNode.node_id"`)}
	}
	if _, ok := _c.mutation.NodePublicKey(); !ok {
		return &ValidationError{Name: "node_public_key", err: errors.New(`server: missing required field "RemoteNode.node_public_key"`)}
	}
	if _, ok := _c.mutation.ManagementAddress(); !ok {
		return &ValidationError{Name: "management_address", err: errors.New(`server: missing required field "RemoteNode.management_address"`)}
	}
	if _, ok := _c.mutation.FrpBindPort(); !ok {
		return &ValidationError{Name: "frp_bind_port", err: errors.New(`server: missing required field "RemoteNode.frp_bind_port"`)}
	}
	if _, ok := _c.mutation.HTTPVhostPort(); !ok {
		return &ValidationError{Name: "http_vhost_port", err: errors.New(`server: missing required field "RemoteNode.http_vhost_port"`)}
	}
	if _, ok := _c.mutation.PortStart(); !ok {
		return &ValidationError{Name: "port_start", err: errors.New(`server: missing required field "RemoteNode.port_start"`)}
	}
	if _, ok := _c.mutation.PortEnd(); !ok {
		return &ValidationError{Name: "port_end", err: errors.New(`server: missing required field "RemoteNode.port_end"`)}
	}
	if _, ok := _c.mutation.DesiredRevision(); !ok {
		return &ValidationError{Name: "desired_revision", err: errors.New(`server: missing required field "RemoteNode.desired_revision"`)}
	}
	if _, ok := _c.mutation.ActiveToken(); !ok {
		return &ValidationError{Name: "active_token", err: errors.New(`server: missing required field "RemoteNode.active_token"`)}
	}
	if len(_c.mutation.NodeIDs()) == 0 {
		return &ValidationError{Name: "node", err: errors.New(`server: missing required edge "RemoteNode.node"`)}
	}
	return nil
}

func (_c *RemoteNodeCreate) sqlSave(ctx context.Context) (*RemoteNode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RemoteNodeCreate) createSpec() (*RemoteNode, *sqlgraph.CreateSpec) {
	var (
		_node = &RemoteNode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(remotenode.Table, sqlgraph.NewFieldSpec(remotenode.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.NodePublicKey(); ok {
		_spec.SetField(remotenode.FieldNodePublicKey, field.TypeString, value)
		_node.NodePublicKey = value
	}
	if value, ok := _c.mutation.ManagementAddress(); ok {
		_spec.SetField(remotenode.FieldManagementAddress, field.TypeString, value)
		_node.ManagementAddress = value
	}
	if value, ok := _c.mutation.FrpBindPort(); ok {
		_spec.SetField(remotenode.FieldFrpBindPort, field.TypeInt, value)
		_node.FrpBindPort = value
	}
	if value, ok := _c.mutation.HTTPVhostPort(); ok {
		_spec.SetField(remotenode.FieldHTTPVhostPort, field.TypeInt, value)
		_node.HTTPVhostPort = value
	}
	if value, ok := _c.mutation.PortStart(); ok {
		_spec.SetField(remotenode.FieldPortStart, field.TypeInt, value)
		_node.PortStart = value
	}
	if value, ok := _c.mutation.PortEnd(); ok {
		_spec.SetField(remotenode.FieldPortEnd, field.TypeInt, value)
		_node.PortEnd = value
	}
	if value, ok := _c.mutation.DesiredRevision(); ok {
		_spec.SetField(remotenode.FieldDesiredRevision, field.TypeInt64, value)
		_node.DesiredRevision = value
	}
	if value, ok := _c.mutation.DesiredHash(); ok {
		_spec.SetField(remotenode.FieldDesiredHash, field.TypeString, value)
		_node.DesiredHash = &value
	}
	if value, ok := _c.mutation.DesiredSnapshot(); ok {
		_spec.SetField(remotenode.FieldDesiredSnapshot, field.TypeString, value)
		_node.DesiredSnapshot = &value
	}
	if value, ok := _c.mutation.ActiveToken(); ok {
		_spec.SetField(remotenode.FieldActiveToken, field.TypeString, value)
		_node.ActiveToken = value
	}
	if value, ok := _c.mutation.StagedToken(); ok {
		_spec.SetField(remotenode.FieldStagedToken, field.TypeString, value)
		_node.StagedToken = &value
	}
	if value, ok := _c.mutation.StagedTokenRevision(); ok {
		_spec.SetField(remotenode.FieldStagedTokenRevision, field.TypeInt64, value)
		_node.StagedTokenRevision = &value
	}
	if nodes := _c.mutation.NodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   remotenode.NodeTable,
			Columns: []string{remotenode.NodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RemoteNodeCreateBulk is the builder for creating many RemoteNode entities in bulk.
type RemoteNodeCreateBulk struct {
	config
	err      error
	builders []*RemoteNodeCreate
}

// Save creates the RemoteNode entities in the database.
func (_c *RemoteNodeCreateBulk) Save(ctx context.Context) ([]*RemoteNode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RemoteNode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RemoteNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RemoteNodeCreateBulk) SaveX(ctx context.Context) []*RemoteNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemoteNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemoteNodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
