// Code generated by ent, DO NOT EDIT.

package server

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hackycy/hackycy-cli/ent/server/account"
	"github.com/hackycy/hackycy-cli/ent/server/node"
	"github.com/hackycy/hackycy-cli/ent/server/serverclient"
)

// ServerClient is the model entity for the ServerClient schema.
type ServerClient struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OwnerAccountID holds the value of the "owner_account_id" field.
	OwnerAccountID string `json:"owner_account_id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID string `json:"node_id,omitempty"`
	// PendingNodeID holds the value of the "pending_node_id" field.
	PendingNodeID *string `json:"pending_node_id,omitempty"`
	// PendingSince holds the value of the "pending_since" field.
	PendingSince *string `json:"pending_since,omitempty"`
	// LastAppliedNodeID holds the value of the "last_applied_node_id" field.
	LastAppliedNodeID *string `json:"last_applied_node_id,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// DesiredRevision holds the value of the "desired_revision" field.
	DesiredRevision int64 `json:"desired_revision,omitempty"`
	// LastAppliedRevision holds the value of the "last_applied_revision" field.
	LastAppliedRevision int64 `json:"last_applied_revision,omitempty"`
	// RevocationPending holds the value of the "revocation_pending" field.
	RevocationPending bool `json:"revocation_pending,omitempty"`
	// DesiredRestartGeneration holds the value of the "desired_restart_generation" field.
	DesiredRestartGeneration int64 `json:"desired_restart_generation,omitempty"`
	// CompletedRestartGeneration holds the value of the "completed_restart_generation" field.
	CompletedRestartGeneration int64 `json:"completed_restart_generation,omitempty"`
	// RestartErrorGeneration holds the value of the "restart_error_generation" field.
	RestartErrorGeneration *int64 `json:"restart_error_generation,omitempty"`
	// RestartErrorCode holds the value of the "restart_error_code" field.
	RestartErrorCode *string `json:"restart_error_code,omitempty"`
	// RestartErrorMessage holds the value of the "restart_error_message" field.
	RestartErrorMessage *string `json:"restart_error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// RotatedAt holds the value of the "rotated_at" field.
	RotatedAt *string `json:"rotated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServerClientQuery when eager-loading is set.
	Edges        ServerClientEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServerClientEdges holds the relations/edges for other nodes in the graph.
type ServerClientEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Account `json:"owner,omitempty"`
	// Node holds the value of the node edge.
	Node *Node `json:"node,omitempty"`
	// PendingNode holds the value of the pending_node edge.
	PendingNode *Node `json:"pending_node,omitempty"`
	// LastAppliedNode holds the value of the last_applied_node edge.
	LastAppliedNode *Node `json:"last_applied_node,omitempty"`
	// Tunnels holds the value of the tunnels edge.
	Tunnels []*Tunnel `json:"tunnels,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServerClientEdges) OwnerOrErr() (*Account, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// NodeOrErr returns the Node value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServerClientEdges) NodeOrErr() (*Node, error) {
	if e.Node != nil {
		return e.Node, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "node"}
}

// PendingNodeOrErr returns the PendingNode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServerClientEdges) PendingNodeOrErr() (*Node, error) {
	if e.PendingNode != nil {
		return e.PendingNode, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "pending_node"}
}

// LastAppliedNodeOrErr returns the LastAppliedNode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServerClientEdges) LastAppliedNodeOrErr() (*Node, error) {
	if e.LastAppliedNode != nil {
		return e.LastAppliedNode, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "last_applied_node"}
}

// TunnelsOrErr returns the Tunnels value or an error if the edge
// was not loaded in eager-loading.
func (e ServerClientEdges) TunnelsOrErr() ([]*Tunnel, error) {
	if e.loadedTypes[4] {
		return e.Tunnels, nil
	}
	return nil, &NotLoadedError{edge: "tunnels"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServerClient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serverclient.FieldRevocationPending:
			values[i] = new(sql.NullBool)
		case serverclient.FieldDesiredRevision, serverclient.FieldLastAppliedRevision, serverclient.FieldDesiredRestartGeneration, serverclient.FieldCompletedRestartGeneration, serverclient.FieldRestartErrorGeneration:
			values[i] = new(sql.NullInt64)
		case serverclient.FieldID, serverclient.FieldOwnerAccountID, serverclient.FieldNodeID, serverclient.FieldPendingNodeID, serverclient.FieldPendingSince, serverclient.FieldLastAppliedNodeID, serverclient.FieldRemark, serverclient.FieldToken, serverclient.FieldRestartErrorCode, serverclient.FieldRestartErrorMessage, serverclient.FieldCreatedAt, serverclient.FieldRotatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServerClient fields.
func (_m *ServerClient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serverclient.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case serverclient.FieldOwnerAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_account_id", values[i])
			} else if value.Valid {
				_m.OwnerAccountID = value.String
			}
		case serverclient.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case serverclient.FieldPendingNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pending_node_id", values[i])
			} else if value.Valid {
				_m.PendingNodeID = new(string)
				*_m.PendingNodeID = value.String
			}
		case serverclient.FieldPendingSince:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pending_since", values[i])
			} else if value.Valid {
				_m.PendingSince = new(string)
				*_m.PendingSince = value.String
			}
		case serverclient.FieldLastAppliedNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_applied_node_id", values[i])
			} else if value.Valid {
				_m.LastAppliedNodeID = new(string)
				*_m.LastAppliedNodeID = value.String
			}
		case serverclient.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case serverclient.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case serverclient.FieldDesiredRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field desired_revision", values[i])
			} else if value.Valid {
				_m.DesiredRevision = value.Int64
			}
		case serverclient.FieldLastAppliedRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_applied_revision", values[i])
			} else if value.Valid {
				_m.LastAppliedRevision = value.Int64
			}
		case serverclient.FieldRevocationPending:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field revocation_pending", values[i])
			} else if value.Valid {
				_m.RevocationPending = value.Bool
			}
		case serverclient.FieldDesiredRestartGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field desired_restart_generation", values[i])
			} else if value.Valid {
				_m.DesiredRestartGeneration = value.Int64
			}
		case serverclient.FieldCompletedRestartGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completed_restart_generation", values[i])
			} else if value.Valid {
				_m.CompletedRestartGeneration = value.Int64
			}
		case serverclient.FieldRestartErrorGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field restart_error_generation", values[i])
			} else if value.Valid {
				_m.RestartErrorGeneration = new(int64)
				*_m.RestartErrorGeneration = value.Int64
			}
		case serverclient.FieldRestartErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field restart_error_code", values[i])
			} else if value.Valid {
				_m.RestartErrorCode = new(string)
				*_m.RestartErrorCode = value.String
			}
		case serverclient.FieldRestartErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field restart_error_message", values[i])
			} else if value.Valid {
				_m.RestartErrorMessage = new(string)
				*_m.RestartErrorMessage = value.String
			}
		case serverclient.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		case serverclient.FieldRotatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rotated_at", values[i])
			} else if value.Valid {
				_m.RotatedAt = new(string)
				*_m.RotatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServerClient.
// This includes values selected through modifiers, order, etc.
func (_m *ServerClient) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the ServerClient entity.
func (_m *ServerClient) QueryOwner() *AccountQuery {
	return NewServerClientClient(_m.config).QueryOwner(_m)
}

// QueryNode queries the "node" edge of the ServerClient entity.
func (_m *ServerClient) QueryNode() *NodeQuery {
	return NewServerClientClient(_m.config).QueryNode(_m)
}

// QueryPendingNode queries the "pending_node" edge of the ServerClient entity.
func (_m *ServerClient) QueryPendingNode() *NodeQuery {
	return NewServerClientClient(_m.config).QueryPendingNode(_m)
}

// QueryLastAppliedNode queries the "last_applied_node" edge of the ServerClient entity.
func (_m *ServerClient) QueryLastAppliedNode() *NodeQuery {
	return NewServerClientClient(_m.config).QueryLastAppliedNode(_m)
}

// QueryTunnels queries the "tunnels" edge of the ServerClient entity.
func (_m *ServerClient) QueryTunnels() *TunnelQuery {
	return NewServerClientClient(_m.config).QueryTunnels(_m)
}

// Update returns a builder for updating this ServerClient.
// Note that you need to call ServerClient.Unwrap() before calling this method if this ServerClient
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServerClient) Update() *ServerClientUpdateOne {
	return NewServerClientClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServerClient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServerClient) Unwrap() *ServerClient {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("server: ServerClient is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServerClient) String() string {
	var builder strings.Builder
	builder.WriteString("ServerClient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_account_id=")
	builder.WriteString(_m.OwnerAccountID)
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	if v := _m.PendingNodeID; v != nil {
		builder.WriteString("pending_node_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PendingSince; v != nil {
		builder.WriteString("pending_since=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastAppliedNodeID; v != nil {
		builder.WriteString("last_applied_node_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("desired_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.DesiredRevision))
	builder.WriteString(", ")
	builder.WriteString("last_applied_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastAppliedRevision))
	builder.WriteString(", ")
	builder.WriteString("revocation_pending=")
	builder.WriteString(fmt.Sprintf("%v", _m.RevocationPending))
	builder.WriteString(", ")
	builder.WriteString("desired_restart_generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.DesiredRestartGeneration))
	builder.WriteString(", ")
	builder.WriteString("completed_restart_generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletedRestartGeneration))
	builder.WriteString(", ")
	if v := _m.RestartErrorGeneration; v != nil {
		builder.WriteString("restart_error_generation=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RestartErrorCode; v != nil {
		builder.WriteString("restart_error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RestartErrorMessage; v != nil {
		builder.WriteString("restart_error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteString(", ")
	if v := _m.RotatedAt; v != nil {
		builder.WriteString("rotated_at=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ServerClients is a parsable slice of ServerClient.
type ServerClients []*ServerClient
