// Code generated by ent, DO NOT EDIT.

package server

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
	"github.com/hackycy/hackycy-cli/ent/server/tunnel"
	"github.com/hackycy/hackycy-cli/ent/server/tunnelhttproute"
)

// TunnelHTTPRouteUpdate is the builder for updating TunnelHTTPRoute entities.
type TunnelHTTPRouteUpdate struct {
	config
	hooks    []Hook
	mutation *TunnelHTTPRouteMutation
}

// Where appends a list predicates to the TunnelHTTPRouteUpdate builder.
func (_u *TunnelHTTPRouteUpdate) Where(ps ...predicate.TunnelHTTPRoute) *TunnelHTTPRouteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTunnelID sets the "tunnel_id" field.
func (_u *TunnelHTTPRouteUpdate) SetTunnelID(v string) *TunnelHTTPRouteUpdate {
	_u.mutation.SetTunnelID(v)
	return _u
}

// SetNillableTunnelID sets the "tunnel_id" field if the given value is not nil.
func (_u *TunnelHTTPRouteUpdate) SetNillableTunnelID(v *string) *TunnelHTTPRouteUpdate {
	if v != nil {
		_u.SetTunnelID(*v)
	}
	return _u
}

// SetHostname sets the "hostname" field.
func (_u *TunnelHTTPRouteUpdate) SetHostname(v string) *TunnelHTTPRouteUpdate {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *TunnelHTTPRouteUpdate) SetNillableHostname(v *string) *TunnelHTTPRouteUpdate {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *TunnelHTTPRouteUpdate) SetLocation(v string) *TunnelHTTPRouteUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *TunnelHTTPRouteUpdate) SetNillableLocation(v *string) *TunnelHTTPRouteUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetTunnel sets the "tunnel" edge to the Tunnel entity.
func (_u *TunnelHTTPRouteUpdate) SetTunnel(v *Tunnel) *TunnelHTTPRouteUpdate {
	return _u.SetTunnelID(v.ID)
}

// Mutation returns the TunnelHTTPRouteMutation object of the builder.
func (_u *TunnelHTTPRouteUpdate) Mutation() *TunnelHTTPRouteMutation {
	return _u.mutation
}

// ClearTunnel clears the "tunnel" edge to the Tunnel entity.
func (_u *TunnelHTTPRouteUpdate) ClearTunnel() *TunnelHTTPRouteUpdate {
	_u.mutation.ClearTunnel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TunnelHTTPRouteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelHTTPRouteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TunnelHTTPRouteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelHTTPRouteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelHTTPRouteUpdate) check() error {
	if _u.mutation.TunnelCleared() && len(_u.mutation.TunnelIDs()) > 0 {
		return errors.New(`server: clearing a required unique edge "TunnelHTTPRoute.tunnel"`)
	}
	return nil
}

func (_u *TunnelHTTPRouteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnelhttproute.Table, tunnelhttproute.Columns, sqlgraph.NewFieldSpec(tunnelhttproute.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(tunnelhttproute.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(tunnelhttproute.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.TunnelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tunnelhttproute.TunnelTable,
			Columns: []string{tunnelhttproute.TunnelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TunnelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tunnelhttproute.TunnelTable,
			Columns: []string{tunnelhttproute.TunnelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnelhttproute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TunnelHTTPRouteUpdateOne is the builder for updating a single TunnelHTTPRoute entity.
type TunnelHTTPRouteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TunnelHTTPRouteMutation
}

// SetTunnelID sets the "tunnel_id" field.
func (_u *TunnelHTTPRouteUpdateOne) SetTunnelID(v string) *TunnelHTTPRouteUpdateOne {
	_u.mutation.SetTunnelID(v)
	return _u
}

// SetNillableTunnelID sets the "tunnel_id" field if the given value is not nil.
func (_u *TunnelHTTPRouteUpdateOne) SetNillableTunnelID(v *string) *TunnelHTTPRouteUpdateOne {
	if v != nil {
		_u.SetTunnelID(*v)
	}
	return _u
}

// SetHostname sets the "hostname" field.
func (_u *TunnelHTTPRouteUpdateOne) SetHostname(v string) *TunnelHTTPRouteUpdateOne {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *TunnelHTTPRouteUpdateOne) SetNillableHostname(v *string) *TunnelHTTPRouteUpdateOne {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *TunnelHTTPRouteUpdateOne) SetLocation(v string) *TunnelHTTPRouteUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *TunnelHTTPRouteUpdateOne) SetNillableLocation(v *string) *TunnelHTTPRouteUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetTunnel sets the "tunnel" edge to the Tunnel entity.
func (_u *TunnelHTTPRouteUpdateOne) SetTunnel(v *Tunnel) *TunnelHTTPRouteUpdateOne {
	return _u.SetTunnelID(v.ID)
}

// Mutation returns the TunnelHTTPRouteMutation object of the builder.
func (_u *TunnelHTTPRouteUpdateOne) Mutation() *TunnelHTTPRouteMutation {
	return _u.mutation
}

// ClearTunnel clears the "tunnel" edge to the Tunnel entity.
func (_u *TunnelHTTPRouteUpdateOne) ClearTunnel() *TunnelHTTPRouteUpdateOne {
	_u.mutation.ClearTunnel()
	return _u
}

// Where appends a list predicates to the TunnelHTTPRouteUpdate builder.
func (_u *TunnelHTTPRouteUpdateOne) Where(ps ...predicate.TunnelHTTPRoute) *TunnelHTTPRouteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TunnelHTTPRouteUpdateOne) Select(field string, fields ...string) *TunnelHTTPRouteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TunnelHTTPRoute entity.
func (_u *TunnelHTTPRouteUpdateOne) Save(ctx context.Context) (*TunnelHTTPRoute, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelHTTPRouteUpdateOne) SaveX(ctx context.Context) *TunnelHTTPRoute {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TunnelHTTPRouteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelHTTPRouteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelHTTPRouteUpdateOne) check() error {
	if _u.mutation.TunnelCleared() && len(_u.mutation.TunnelIDs()) > 0 {
		return errors.New(`server: clearing a required unique edge "TunnelHTTPRoute.tunnel"`)
	}
	return nil
}

func (_u *TunnelHTTPRouteUpdateOne) sqlSave(ctx context.Context) (_node *TunnelHTTPRoute, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnelhttproute.Table, tunnelhttproute.Columns, sqlgraph.NewFieldSpec(tunnelhttproute.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`server: missing "TunnelHTTPRoute.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tunnelhttproute.FieldID)
		for _, f := range fields {
			if !tunnelhttproute.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("server: invalid field %q for query", f)}
			}
			if f != tunnelhttproute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(tunnelhttproute.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(tunnelhttproute.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.TunnelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tunnelhttproute.TunnelTable,
			Columns: []string{tunnelhttproute.TunnelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TunnelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tunnelhttproute.TunnelTable,
			Columns: []string{tunnelhttproute.TunnelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TunnelHTTPRoute{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnelhttproute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
