// Code generated by ent, DO NOT EDIT.

package server

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hackycy/hackycy-cli/ent/server/node"
	"github.com/hackycy/hackycy-cli/ent/server/serverclient"
	"github.com/hackycy/hackycy-cli/ent/server/tunnel"
)

// Tunnel is the model entity for the Tunnel schema.
type Tunnel struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ClientInternalID holds the value of the "client_internal_id" field.
	ClientInternalID string `json:"client_internal_id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID string `json:"node_id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol tunnel.Protocol `json:"protocol,omitempty"`
	// CustomDomains holds the value of the "custom_domains" field.
	CustomDomains *string `json:"custom_domains,omitempty"`
	// Location holds the value of the "location" field.
	Location *string `json:"location,omitempty"`
	// ServerPort holds the value of the "server_port" field.
	ServerPort *int `json:"server_port,omitempty"`
	// LocalHost holds the value of the "local_host" field.
	LocalHost string `json:"local_host,omitempty"`
	// LocalPort holds the value of the "local_port" field.
	LocalPort int `json:"local_port,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// OptionsJSON holds the value of the "options_json" field.
	OptionsJSON string `json:"options_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt string `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TunnelQuery when eager-loading is set.
	Edges        TunnelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TunnelEdges holds the relations/edges for other nodes in the graph.
type TunnelEdges struct {
	// Client holds the value of the client edge.
	Client *ServerClient `json:"client,omitempty"`
	// Node holds the value of the node edge.
	Node *Node `json:"node,omitempty"`
	// Routes holds the value of the routes edge.
	Routes []*TunnelHTTPRoute `json:"routes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TunnelEdges) ClientOrErr() (*ServerClient, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: serverclient.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// NodeOrErr returns the Node value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TunnelEdges) NodeOrErr() (*Node, error) {
	if e.Node != nil {
		return e.Node, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "node"}
}

// RoutesOrErr returns the Routes value or an error if the edge
// was not loaded in eager-loading.
func (e TunnelEdges) RoutesOrErr() ([]*TunnelHTTPRoute, error) {
	if e.loadedTypes[2] {
		return e.Routes, nil
	}
	return nil, &NotLoadedError{edge: "routes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tunnel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tunnel.FieldEnabled:
			values[i] = new(sql.NullBool)
		case tunnel.FieldServerPort, tunnel.FieldLocalPort:
			values[i] = new(sql.NullInt64)
		case tunnel.FieldID, tunnel.FieldClientInternalID, tunnel.FieldNodeID, tunnel.FieldLabel, tunnel.FieldProtocol, tunnel.FieldCustomDomains, tunnel.FieldLocation, tunnel.FieldLocalHost, tunnel.FieldOptionsJSON, tunnel.FieldCreatedAt, tunnel.FieldUpdatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tunnel fields.
func (_m *Tunnel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tunnel.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case tunnel.FieldClientInternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_internal_id", values[i])
			} else if value.Valid {
				_m.ClientInternalID = value.String
			}
		case tunnel.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case tunnel.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case tunnel.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = tunnel.Protocol(value.String)
			}
		case tunnel.FieldCustomDomains:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_domains", values[i])
			} else if value.Valid {
				_m.CustomDomains = new(string)
				*_m.CustomDomains = value.String
			}
		case tunnel.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = new(string)
				*_m.Location = value.String
			}
		case tunnel.FieldServerPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field server_port", values[i])
			} else if value.Valid {
				_m.ServerPort = new(int)
				*_m.ServerPort = int(value.Int64)
			}
		case tunnel.FieldLocalHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_host", values[i])
			} else if value.Valid {
				_m.LocalHost = value.String
			}
		case tunnel.FieldLocalPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field local_port", values[i])
			} else if value.Valid {
				_m.LocalPort = int(value.Int64)
			}
		case tunnel.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case tunnel.FieldOptionsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field options_json", values[i])
			} else if value.Valid {
				_m.OptionsJSON = value.String
			}
		case tunnel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		case tunnel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tunnel.
// This includes values selected through modifiers, order, etc.
func (_m *Tunnel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClient queries the "client" edge of the Tunnel entity.
func (_m *Tunnel) QueryClient() *ServerClientQuery {
	return NewTunnelClient(_m.config).QueryClient(_m)
}

// QueryNode queries the "node" edge of the Tunnel entity.
func (_m *Tunnel) QueryNode() *NodeQuery {
	return NewTunnelClient(_m.config).QueryNode(_m)
}

// QueryRoutes queries the "routes" edge of the Tunnel entity.
func (_m *Tunnel) QueryRoutes() *TunnelHTTPRouteQuery {
	return NewTunnelClient(_m.config).QueryRoutes(_m)
}

// Update returns a builder for updating this Tunnel.
// Note that you need to call Tunnel.Unwrap() before calling this method if this Tunnel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tunnel) Update() *TunnelUpdateOne {
	return NewTunnelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tunnel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tunnel) Unwrap() *Tunnel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("server: Tunnel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tunnel) String() string {
	var builder strings.Builder
	builder.WriteString("Tunnel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("client_internal_id=")
	builder.WriteString(_m.ClientInternalID)
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocol))
	builder.WriteString(", ")
	if v := _m.CustomDomains; v != nil {
		builder.WriteString("custom_domains=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Location; v != nil {
		builder.WriteString("location=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ServerPort; v != nil {
		builder.WriteString("server_port=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("local_host=")
	builder.WriteString(_m.LocalHost)
	builder.WriteString(", ")
	builder.WriteString("local_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.LocalPort))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("options_json=")
	builder.WriteString(_m.OptionsJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt)
	builder.WriteByte(')')
	return builder.String()
}

// Tunnels is a parsable slice of Tunnel.
type Tunnels []*Tunnel
