// Code generated by ent, DO NOT EDIT.

package node

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "node_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLifecycle holds the string denoting the lifecycle field in the database.
	FieldLifecycle = "lifecycle"
	// FieldAdvertisedFrpHost holds the string denoting the advertised_frp_host field in the database.
	FieldAdvertisedFrpHost = "advertised_frp_host"
	// FieldAdvertisedFrpPort holds the string denoting the advertised_frp_port field in the database.
	FieldAdvertisedFrpPort = "advertised_frp_port"
	// FieldHTTPIngressHost holds the string denoting the http_ingress_host field in the database.
	FieldHTTPIngressHost = "http_ingress_host"
	// FieldHTTPIngressPort holds the string denoting the http_ingress_port field in the database.
	FieldHTTPIngressPort = "http_ingress_port"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeClients holds the string denoting the clients edge name in mutations.
	EdgeClients = "clients"
	// EdgePendingClients holds the string denoting the pending_clients edge name in mutations.
	EdgePendingClients = "pending_clients"
	// EdgeAppliedClients holds the string denoting the applied_clients edge name in mutations.
	EdgeAppliedClients = "applied_clients"
	// EdgeTunnels holds the string denoting the tunnels edge name in mutations.
	EdgeTunnels = "tunnels"
	// EdgeRemoteNode holds the string denoting the remote_node edge name in mutations.
	EdgeRemoteNode = "remote_node"
	// EdgePortPool holds the string denoting the port_pool edge name in mutations.
	EdgePortPool = "port_pool"
	// EdgeManagementCandidate holds the string denoting the management_candidate edge name in mutations.
	EdgeManagementCandidate = "management_candidate"
	// EdgeObservation holds the string denoting the observation edge name in mutations.
	EdgeObservation = "observation"
	// ServerClientFieldID holds the string denoting the ID field of the ServerClient.
	ServerClientFieldID = "internal_id"
	// TunnelFieldID holds the string denoting the ID field of the Tunnel.
	TunnelFieldID = "id"
	// RemoteNodeFieldID holds the string denoting the ID field of the RemoteNode.
	RemoteNodeFieldID = "id"
	// NodePortPoolFieldID holds the string denoting the ID field of the NodePortPool.
	NodePortPoolFieldID = "id"
	// NodeManagementCandidateFieldID holds the string denoting the ID field of the NodeManagementCandidate.
	NodeManagementCandidateFieldID = "id"
	// NodeObservationFieldID holds the string denoting the ID field of the NodeObservation.
	NodeObservationFieldID = "id"
	// Table holds the table name of the node in the database.
	Table = "nodes"
	// ClientsTable is the table that holds the clients relation/edge.
	ClientsTable = "clients"
	// ClientsInverseTable is the table name for the ServerClient entity.
	// It exists in this package in order to avoid circular dependency with the "serverclient" package.
	ClientsInverseTable = "clients"
	// ClientsColumn is the table column denoting the clients relation/edge.
	ClientsColumn = "node_id"
	// PendingClientsTable is the table that holds the pending_clients relation/edge.
	PendingClientsTable = "clients"
	// PendingClientsInverseTable is the table name for the ServerClient entity.
	// It exists in this package in order to avoid circular dependency with the "serverclient" package.
	PendingClientsInverseTable = "clients"
	// PendingClientsColumn is the table column denoting the pending_clients relation/edge.
	PendingClientsColumn = "pending_node_id"
	// AppliedClientsTable is the table that holds the applied_clients relation/edge.
	AppliedClientsTable = "clients"
	// AppliedClientsInverseTable is the table name for the ServerClient entity.
	// It exists in this package in order to avoid circular dependency with the "serverclient" package.
	AppliedClientsInverseTable = "clients"
	// AppliedClientsColumn is the table column denoting the applied_clients relation/edge.
	AppliedClientsColumn = "last_applied_node_id"
	// TunnelsTable is the table that holds the tunnels relation/edge.
	TunnelsTable = "tunnels"
	// TunnelsInverseTable is the table name for the Tunnel entity.
	// It exists in this package in order to avoid circular dependency with the "tunnel" package.
	TunnelsInverseTable = "tunnels"
	// TunnelsColumn is the table column denoting the tunnels relation/edge.
	TunnelsColumn = "node_id"
	// RemoteNodeTable is the table that holds the remote_node relation/edge.
	RemoteNodeTable = "remote_nodes"
	// RemoteNodeInverseTable is the table name for the RemoteNode entity.
	// It exists in this package in order to avoid circular dependency with the "remotenode" package.
	RemoteNodeInverseTable = "remote_nodes"
	// RemoteNodeColumn is the table column denoting the remote_node relation/edge.
	RemoteNodeColumn = "node_id"
	// PortPoolTable is the table that holds the port_pool relation/edge.
	PortPoolTable = "node_port_pools"
	// PortPoolInverseTable is the table name for the NodePortPool entity.
	// It exists in this package in order to avoid circular dependency with the "nodeportpool" package.
	PortPoolInverseTable = "node_port_pools"
	// PortPoolColumn is the table column denoting the port_pool relation/edge.
	PortPoolColumn = "node_id"
	// ManagementCandidateTable is the table that holds the management_candidate relation/edge.
	ManagementCandidateTable = "node_management_candidates"
	// ManagementCandidateInverseTable is the table name for the NodeManagementCandidate entity.
	// It exists in this package in order to avoid circular dependency with the "nodemanagementcandidate" package.
	ManagementCandidateInverseTable = "node_management_candidates"
	// ManagementCandidateColumn is the table column denoting the management_candidate relation/edge.
	ManagementCandidateColumn = "node_id"
	// ObservationTable is the table that holds the observation relation/edge.
	ObservationTable = "node_observations"
	// ObservationInverseTable is the table name for the NodeObservation entity.
	// It exists in this package in order to avoid circular dependency with the "nodeobservation" package.
	ObservationInverseTable = "node_observations"
	// ObservationColumn is the table column denoting the observation relation/edge.
	ObservationColumn = "node_id"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldKind,
	FieldName,
	FieldLifecycle,
	FieldAdvertisedFrpHost,
	FieldAdvertisedFrpPort,
	FieldHTTPIngressHost,
	FieldHTTPIngressPort,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindLocal  Kind = "local"
	KindRemote Kind = "remote"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindLocal, KindRemote:
		return nil
	default:
		return fmt.Errorf("node: invalid enum value for kind field: %q", k)
	}
}

// Lifecycle defines the type for the "lifecycle" enum field.
type Lifecycle string

// LifecycleActive is the default value of the Lifecycle enum.
const DefaultLifecycle = LifecycleActive

// Lifecycle values.
const (
	LifecycleActive   Lifecycle = "active"
	LifecycleRemoving Lifecycle = "removing"
)

func (l Lifecycle) String() string {
	return string(l)
}

// LifecycleValidator is a validator for the "lifecycle" field enum values. It is called by the builders before save.
func LifecycleValidator(l Lifecycle) error {
	switch l {
	case LifecycleActive, LifecycleRemoving:
		return nil
	default:
		return fmt.Errorf("node: invalid enum value for lifecycle field: %q", l)
	}
}

// OrderOption defines the ordering options for the Node queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLifecycle orders the results by the lifecycle field.
func ByLifecycle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifecycle, opts...).ToFunc()
}

// ByAdvertisedFrpHost orders the results by the advertised_frp_host field.
func ByAdvertisedFrpHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdvertisedFrpHost, opts...).ToFunc()
}

// ByAdvertisedFrpPort orders the results by the advertised_frp_port field.
func ByAdvertisedFrpPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdvertisedFrpPort, opts...).ToFunc()
}

// ByHTTPIngressHost orders the results by the http_ingress_host field.
func ByHTTPIngressHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPIngressHost, opts...).ToFunc()
}

// ByHTTPIngressPort orders the results by the http_ingress_port field.
func ByHTTPIngressPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPIngressPort, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByClientsCount orders the results by clients count.
func ByClientsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClientsStep(), opts...)
	}
}

// ByClients orders the results by clients terms.
func ByClients(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClientsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPendingClientsCount orders the results by pending_clients count.
func ByPendingClientsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPendingClientsStep(), opts...)
	}
}

// ByPendingClients orders the results by pending_clients terms.
func ByPendingClients(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPendingClientsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAppliedClientsCount orders the results by applied_clients count.
func ByAppliedClientsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAppliedClientsStep(), opts...)
	}
}

// ByAppliedClients orders the results by applied_clients terms.
func ByAppliedClients(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAppliedClientsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTunnelsCount orders the results by tunnels count.
func ByTunnelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTunnelsStep(), opts...)
	}
}

// ByTunnels orders the results by tunnels terms.
func ByTunnels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTunnelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRemoteNodeField orders the results by remote_node field.
func ByRemoteNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRemoteNodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByPortPoolField orders the results by port_pool field.
func ByPortPoolField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPortPoolStep(), sql.OrderByField(field, opts...))
	}
}

// ByManagementCandidateField orders the results by management_candidate field.
func ByManagementCandidateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagementCandidateStep(), sql.OrderByField(field, opts...))
	}
}

// ByObservationField orders the results by observation field.
func ByObservationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newObservationStep(), sql.OrderByField(field, opts...))
	}
}
func newClientsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClientsInverseTable, ServerClientFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ClientsTable, ClientsColumn),
	)
}
func newPendingClientsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PendingClientsInverseTable, ServerClientFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PendingClientsTable, PendingClientsColumn),
	)
}
func newAppliedClientsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AppliedClientsInverseTable, ServerClientFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AppliedClientsTable, AppliedClientsColumn),
	)
}
func newTunnelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TunnelsInverseTable, TunnelFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TunnelsTable, TunnelsColumn),
	)
}
func newRemoteNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RemoteNodeInverseTable, RemoteNodeFieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, RemoteNodeTable, RemoteNodeColumn),
	)
}
func newPortPoolStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PortPoolInverseTable, NodePortPoolFieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PortPoolTable, PortPoolColumn),
	)
}
func newManagementCandidateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagementCandidateInverseTable, NodeManagementCandidateFieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ManagementCandidateTable, ManagementCandidateColumn),
	)
}
func newObservationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ObservationInverseTable, NodeObservationFieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ObservationTable, ObservationColumn),
	)
}
