// Code generated by ent, DO NOT EDIT.

package node

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldName, v))
}

// AdvertisedFrpHost applies equality check predicate on the "advertised_frp_host" field. It's identical to AdvertisedFrpHostEQ.
func AdvertisedFrpHost(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpPort applies equality check predicate on the "advertised_frp_port" field. It's identical to AdvertisedFrpPortEQ.
func AdvertisedFrpPort(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldAdvertisedFrpPort, v))
}

// HTTPIngressHost applies equality check predicate on the "http_ingress_host" field. It's identical to HTTPIngressHostEQ.
func HTTPIngressHost(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldHTTPIngressHost, v))
}

// HTTPIngressPort applies equality check predicate on the "http_ingress_port" field. It's identical to HTTPIngressPortEQ.
func HTTPIngressPort(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldHTTPIngressPort, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldKind, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldName, v))
}

// LifecycleEQ applies the EQ predicate on the "lifecycle" field.
func LifecycleEQ(v Lifecycle) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldLifecycle, v))
}

// LifecycleNEQ applies the NEQ predicate on the "lifecycle" field.
func LifecycleNEQ(v Lifecycle) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldLifecycle, v))
}

// LifecycleIn applies the In predicate on the "lifecycle" field.
func LifecycleIn(vs ...Lifecycle) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldLifecycle, vs...))
}

// LifecycleNotIn applies the NotIn predicate on the "lifecycle" field.
func LifecycleNotIn(vs ...Lifecycle) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldLifecycle, vs...))
}

// AdvertisedFrpHostEQ applies the EQ predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostNEQ applies the NEQ predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostIn applies the In predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldAdvertisedFrpHost, vs...))
}

// AdvertisedFrpHostNotIn applies the NotIn predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldAdvertisedFrpHost, vs...))
}

// AdvertisedFrpHostGT applies the GT predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostGTE applies the GTE predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostLT applies the LT predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostLTE applies the LTE predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostContains applies the Contains predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostHasPrefix applies the HasPrefix predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostHasSuffix applies the HasSuffix predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostIsNil applies the IsNil predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldAdvertisedFrpHost))
}

// AdvertisedFrpHostNotNil applies the NotNil predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldAdvertisedFrpHost))
}

// AdvertisedFrpHostEqualFold applies the EqualFold predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpHostContainsFold applies the ContainsFold predicate on the "advertised_frp_host" field.
func AdvertisedFrpHostContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldAdvertisedFrpHost, v))
}

// AdvertisedFrpPortEQ applies the EQ predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldAdvertisedFrpPort, v))
}

// AdvertisedFrpPortNEQ applies the NEQ predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldAdvertisedFrpPort, v))
}

// AdvertisedFrpPortIn applies the In predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldAdvertisedFrpPort, vs...))
}

// AdvertisedFrpPortNotIn applies the NotIn predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldAdvertisedFrpPort, vs...))
}

// AdvertisedFrpPortGT applies the GT predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldAdvertisedFrpPort, v))
}

// AdvertisedFrpPortGTE applies the GTE predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldAdvertisedFrpPort, v))
}

// AdvertisedFrpPortLT applies the LT predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldAdvertisedFrpPort, v))
}

// AdvertisedFrpPortLTE applies the LTE predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldAdvertisedFrpPort, v))
}

// AdvertisedFrpPortIsNil applies the IsNil predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldAdvertisedFrpPort))
}

// AdvertisedFrpPortNotNil applies the NotNil predicate on the "advertised_frp_port" field.
func AdvertisedFrpPortNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldAdvertisedFrpPort))
}

// HTTPIngressHostEQ applies the EQ predicate on the "http_ingress_host" field.
func HTTPIngressHostEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldHTTPIngressHost, v))
}

// HTTPIngressHostNEQ applies the NEQ predicate on the "http_ingress_host" field.
func HTTPIngressHostNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldHTTPIngressHost, v))
}

// HTTPIngressHostIn applies the In predicate on the "http_ingress_host" field.
func HTTPIngressHostIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldHTTPIngressHost, vs...))
}

// HTTPIngressHostNotIn applies the NotIn predicate on the "http_ingress_host" field.
func HTTPIngressHostNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldHTTPIngressHost, vs...))
}

// HTTPIngressHostGT applies the GT predicate on the "http_ingress_host" field.
func HTTPIngressHostGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldHTTPIngressHost, v))
}

// HTTPIngressHostGTE applies the GTE predicate on the "http_ingress_host" field.
func HTTPIngressHostGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldHTTPIngressHost, v))
}

// HTTPIngressHostLT applies the LT predicate on the "http_ingress_host" field.
func HTTPIngressHostLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldHTTPIngressHost, v))
}

// HTTPIngressHostLTE applies the LTE predicate on the "http_ingress_host" field.
func HTTPIngressHostLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldHTTPIngressHost, v))
}

// HTTPIngressHostContains applies the Contains predicate on the "http_ingress_host" field.
func HTTPIngressHostContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldHTTPIngressHost, v))
}

// HTTPIngressHostHasPrefix applies the HasPrefix predicate on the "http_ingress_host" field.
func HTTPIngressHostHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldHTTPIngressHost, v))
}

// HTTPIngressHostHasSuffix applies the HasSuffix predicate on the "http_ingress_host" field.
func HTTPIngressHostHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldHTTPIngressHost, v))
}

// HTTPIngressHostIsNil applies the IsNil predicate on the "http_ingress_host" field.
func HTTPIngressHostIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldHTTPIngressHost))
}

// HTTPIngressHostNotNil applies the NotNil predicate on the "http_ingress_host" field.
func HTTPIngressHostNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldHTTPIngressHost))
}

// HTTPIngressHostEqualFold applies the EqualFold predicate on the "http_ingress_host" field.
func HTTPIngressHostEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldHTTPIngressHost, v))
}

// HTTPIngressHostContainsFold applies the ContainsFold predicate on the "http_ingress_host" field.
func HTTPIngressHostContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldHTTPIngressHost, v))
}

// HTTPIngressPortEQ applies the EQ predicate on the "http_ingress_port" field.
func HTTPIngressPortEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldHTTPIngressPort, v))
}

// HTTPIngressPortNEQ applies the NEQ predicate on the "http_ingress_port" field.
func HTTPIngressPortNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldHTTPIngressPort, v))
}

// HTTPIngressPortIn applies the In predicate on the "http_ingress_port" field.
func HTTPIngressPortIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldHTTPIngressPort, vs...))
}

// HTTPIngressPortNotIn applies the NotIn predicate on the "http_ingress_port" field.
func HTTPIngressPortNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldHTTPIngressPort, vs...))
}

// HTTPIngressPortGT applies the GT predicate on the "http_ingress_port" field.
func HTTPIngressPortGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldHTTPIngressPort, v))
}

// HTTPIngressPortGTE applies the GTE predicate on the "http_ingress_port" field.
func HTTPIngressPortGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldHTTPIngressPort, v))
}

// HTTPIngressPortLT applies the LT predicate on the "http_ingress_port" field.
func HTTPIngressPortLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldHTTPIngressPort, v))
}

// HTTPIngressPortLTE applies the LTE predicate on the "http_ingress_port" field.
func HTTPIngressPortLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldHTTPIngressPort, v))
}

// HTTPIngressPortIsNil applies the IsNil predicate on the "http_ingress_port" field.
func HTTPIngressPortIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldHTTPIngressPort))
}

// HTTPIngressPortNotNil applies the NotNil predicate on the "http_ingress_port" field.
func HTTPIngressPortNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldHTTPIngressPort))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtContains applies the Contains predicate on the "updated_at" field.
func UpdatedAtContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldUpdatedAt, v))
}

// UpdatedAtHasPrefix applies the HasPrefix predicate on the "updated_at" field.
func UpdatedAtHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldUpdatedAt, v))
}

// UpdatedAtHasSuffix applies the HasSuffix predicate on the "updated_at" field.
func UpdatedAtHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldUpdatedAt, v))
}

// UpdatedAtEqualFold applies the EqualFold predicate on the "updated_at" field.
func UpdatedAtEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldUpdatedAt, v))
}

// UpdatedAtContainsFold applies the ContainsFold predicate on the "updated_at" field.
func UpdatedAtContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldUpdatedAt, v))
}

// HasClients applies the HasEdge predicate on the "clients" edge.
func HasClients() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClientsTable, ClientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientsWith applies the HasEdge predicate on the "clients" edge with a given conditions (other predicates).
func HasClientsWith(preds ...predicate.ServerClient) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newClientsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPendingClients applies the HasEdge predicate on the "pending_clients" edge.
func HasPendingClients() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PendingClientsTable, PendingClientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPendingClientsWith applies the HasEdge predicate on the "pending_clients" edge with a given conditions (other predicates).
func HasPendingClientsWith(preds ...predicate.ServerClient) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newPendingClientsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAppliedClients applies the HasEdge predicate on the "applied_clients" edge.
func HasAppliedClients() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AppliedClientsTable, AppliedClientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAppliedClientsWith applies the HasEdge predicate on the "applied_clients" edge with a given conditions (other predicates).
func HasAppliedClientsWith(preds ...predicate.ServerClient) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newAppliedClientsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTunnels applies the HasEdge predicate on the "tunnels" edge.
func HasTunnels() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TunnelsTable, TunnelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTunnelsWith applies the HasEdge predicate on the "tunnels" edge with a given conditions (other predicates).
func HasTunnelsWith(preds ...predicate.Tunnel) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newTunnelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRemoteNode applies the HasEdge predicate on the "remote_node" edge.
func HasRemoteNode() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, RemoteNodeTable, RemoteNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRemoteNodeWith applies the HasEdge predicate on the "remote_node" edge with a given conditions (other predicates).
func HasRemoteNodeWith(preds ...predicate.RemoteNode) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newRemoteNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPortPool applies the HasEdge predicate on the "port_pool" edge.
func HasPortPool() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, PortPoolTable, PortPoolColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPortPoolWith applies the HasEdge predicate on the "port_pool" edge with a given conditions (other predicates).
func HasPortPoolWith(preds ...predicate.NodePortPool) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newPortPoolStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasManagementCandidate applies the HasEdge predicate on the "management_candidate" edge.
func HasManagementCandidate() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ManagementCandidateTable, ManagementCandidateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasManagementCandidateWith applies the HasEdge predicate on the "management_candidate" edge with a given conditions (other predicates).
func HasManagementCandidateWith(preds ...predicate.NodeManagementCandidate) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newManagementCandidateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasObservation applies the HasEdge predicate on the "observation" edge.
func HasObservation() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ObservationTable, ObservationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasObservationWith applies the HasEdge predicate on the "observation" edge with a given conditions (other predicates).
func HasObservationWith(preds ...predicate.NodeObservation) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newObservationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Node) predicate.Node {
	return predicate.Node(sql.NotPredicates(p))
}
