// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"example.com/tunnel-ent-prototype/ent/account"
	"example.com/tunnel-ent-prototype/ent/allocation"
)

// Allocation is the model entity for the Allocation schema.
type Allocation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID int `json:"owner_id,omitempty"`
	// Port holds the value of the "port" field.
	Port int `json:"port,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AllocationQuery when eager-loading is set.
	Edges        AllocationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AllocationEdges holds the relations/edges for other nodes in the graph.
type AllocationEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Account `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AllocationEdges) OwnerOrErr() (*Account, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Allocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case allocation.FieldEnabled:
			values[i] = new(sql.NullBool)
		case allocation.FieldID, allocation.FieldOwnerID, allocation.FieldPort:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Allocation fields.
func (_m *Allocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case allocation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case allocation.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = int(value.Int64)
			}
		case allocation.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case allocation.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Allocation.
// This includes values selected through modifiers, order, etc.
func (_m *Allocation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Allocation entity.
func (_m *Allocation) QueryOwner() *AccountQuery {
	return NewAllocationClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this Allocation.
// Note that you need to call Allocation.Unwrap() before calling this method if this Allocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Allocation) Update() *AllocationUpdateOne {
	return NewAllocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Allocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Allocation) Unwrap() *Allocation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Allocation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Allocation) String() string {
	var builder strings.Builder
	builder.WriteString("Allocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// Allocations is a parsable slice of Allocation.
type Allocations []*Allocation
