// Code generated by ent, DO NOT EDIT.

package nodeportpool

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldLTE(FieldID, id))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldEQ(FieldNodeID, v))
}

// PortStart applies equality check predicate on the "port_start" field. It's identical to PortStartEQ.
func PortStart(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldEQ(FieldPortStart, v))
}

// PortEnd applies equality check predicate on the "port_end" field. It's identical to PortEndEQ.
func PortEnd(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldEQ(FieldPortEnd, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldContainsFold(FieldNodeID, v))
}

// PortStartEQ applies the EQ predicate on the "port_start" field.
func PortStartEQ(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldEQ(FieldPortStart, v))
}

// PortStartNEQ applies the NEQ predicate on the "port_start" field.
func PortStartNEQ(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldNEQ(FieldPortStart, v))
}

// PortStartIn applies the In predicate on the "port_start" field.
func PortStartIn(vs ...int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldIn(FieldPortStart, vs...))
}

// PortStartNotIn applies the NotIn predicate on the "port_start" field.
func PortStartNotIn(vs ...int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldNotIn(FieldPortStart, vs...))
}

// PortStartGT applies the GT predicate on the "port_start" field.
func PortStartGT(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldGT(FieldPortStart, v))
}

// PortStartGTE applies the GTE predicate on the "port_start" field.
func PortStartGTE(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldGTE(FieldPortStart, v))
}

// PortStartLT applies the LT predicate on the "port_start" field.
func PortStartLT(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldLT(FieldPortStart, v))
}

// PortStartLTE applies the LTE predicate on the "port_start" field.
func PortStartLTE(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldLTE(FieldPortStart, v))
}

// PortEndEQ applies the EQ predicate on the "port_end" field.
func PortEndEQ(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldEQ(FieldPortEnd, v))
}

// PortEndNEQ applies the NEQ predicate on the "port_end" field.
func PortEndNEQ(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldNEQ(FieldPortEnd, v))
}

// PortEndIn applies the In predicate on the "port_end" field.
func PortEndIn(vs ...int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldIn(FieldPortEnd, vs...))
}

// PortEndNotIn applies the NotIn predicate on the "port_end" field.
func PortEndNotIn(vs ...int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldNotIn(FieldPortEnd, vs...))
}

// PortEndGT applies the GT predicate on the "port_end" field.
func PortEndGT(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldGT(FieldPortEnd, v))
}

// PortEndGTE applies the GTE predicate on the "port_end" field.
func PortEndGTE(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldGTE(FieldPortEnd, v))
}

// PortEndLT applies the LT predicate on the "port_end" field.
func PortEndLT(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldLT(FieldPortEnd, v))
}

// PortEndLTE applies the LTE predicate on the "port_end" field.
func PortEndLTE(v int) predicate.NodePortPool {
	return predicate.NodePortPool(sql.FieldLTE(FieldPortEnd, v))
}

// HasNode applies the HasEdge predicate on the "node" edge.
func HasNode() predicate.NodePortPool {
	return predicate.NodePortPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, NodeTable, NodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeWith applies the HasEdge predicate on the "node" edge with a given conditions (other predicates).
func HasNodeWith(preds ...predicate.Node) predicate.NodePortPool {
	return predicate.NodePortPool(func(s *sql.Selector) {
		step := newNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NodePortPool) predicate.NodePortPool {
	return predicate.NodePortPool(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NodePortPool) predicate.NodePortPool {
	return predicate.NodePortPool(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NodePortPool) predicate.NodePortPool {
	return predicate.NodePortPool(sql.NotPredicates(p))
}
