import type { FrpPlatform } from '../src/commands/tunnel/frp/archive'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { z } from 'zod'
import { extractFrpBinaries, sha256Bytes } from '../src/commands/tunnel/frp/archive'
import { FRP_VERSION } from '../src/commands/tunnel/frp/version'

const OUTPUT_PATH = path.resolve('src/commands/tunnel/frp/manifest.generated.ts')
const REPOSITORY = 'fatedier/frp'
const CHECKSUM_ASSET = 'frp_sha256_checksums.txt'

const PLATFORMS = [
  { platform: 'darwin', upstream: 'darwin', extension: 'tar.gz' },
  { platform: 'linux', upstream: 'linux', extension: 'tar.gz' },
  { platform: 'win32', upstream: 'windows', extension: 'zip' },
] as const satisfies readonly { platform: FrpPlatform, upstream: string, extension: string }[]

const ARCHITECTURES = [
  { architecture: 'x64', upstream: 'amd64' },
  { architecture: 'arm64', upstream: 'arm64' },
] as const

const releaseSchema = z.object({
  tag_name: z.string(),
  draft: z.boolean(),
  prerelease: z.boolean(),
  assets: z.array(z.object({
    name: z.string(),
    digest: z.string().nullable(),
    browser_download_url: z.url(),
  })),
})

interface SupportedTarget {
  platform: FrpPlatform
  architecture: 'x64' | 'arm64'
  archive: string
}

export interface GeneratedFrpArtifact extends SupportedTarget {
  sha256: string
  frpcSha256: string
  frpsSha256: string
}

function supportedTargets(): SupportedTarget[] {
  return PLATFORMS.flatMap(({ platform, upstream: operatingSystem, extension }) => ARCHITECTURES.map(({ architecture, upstream }) => ({
    platform,
    architecture,
    archive: `frp_${FRP_VERSION}_${operatingSystem}_${upstream}.${extension}`,
  })))
}

function expectedDownloadUrl(assetName: string): string {
  return `https://github.com/${REPOSITORY}/releases/download/v${FRP_VERSION}/${assetName}`
}

function assetSha256(digest: string | null, assetName: string): string {
  if (!digest)
    throw new Error(`Official release asset ${assetName} does not provide a SHA-256 digest`)
  const match = /^sha256:([a-f\d]{64})$/.exec(digest)
  if (!match)
    throw new Error(`Official release asset ${assetName} does not provide a SHA-256 digest`)
  return match[1]!
}

async function fetchBytes(fetchImpl: typeof globalThis.fetch, url: string, headers?: HeadersInit): Promise<Uint8Array> {
  const response = await fetchImpl(url, { headers, redirect: 'follow' })
  if (!response.ok)
    throw new Error(`${url} returned HTTP ${response.status}`)
  return new Uint8Array(await response.arrayBuffer())
}

export function parseFrpChecksums(contents: string): ReadonlyMap<string, string> {
  const checksums = new Map<string, string>()
  for (const line of contents.trim().split(/\r?\n/)) {
    const match = /^([a-f\d]{64})\s{2}(\S+)$/.exec(line)
    if (!match)
      throw new Error(`Invalid line in ${CHECKSUM_ASSET}: ${line}`)
    const [, digest, name] = match
    if (checksums.has(name!))
      throw new Error(`Duplicate asset in ${CHECKSUM_ASSET}: ${name}`)
    checksums.set(name!, digest!)
  }
  return checksums
}

export function renderFrpManifest(artifacts: readonly GeneratedFrpArtifact[]): string {
  const ordered = artifacts.toSorted((left, right) => `${left.platform}/${left.architecture}`.localeCompare(`${right.platform}/${right.architecture}`))
  const rows = ordered.map(artifact => [
    '  {',
    `    platform: '${artifact.platform}',`,
    `    architecture: '${artifact.architecture}',`,
    `    archive: '${artifact.archive}',`,
    `    sha256: '${artifact.sha256}',`,
    `    frpcSha256: '${artifact.frpcSha256}',`,
    `    frpsSha256: '${artifact.frpsSha256}',`,
    '  },',
  ].join('\n')).join('\n')
  return [
    '// Generated by `bun run generate:frp-manifest`. Do not edit manually.',
    'export const GENERATED_FRP_ARTIFACTS = [',
    rows,
    '] as const',
    '',
  ].join('\n')
}

export async function generateFrpManifest(fetchImpl: typeof globalThis.fetch = globalThis.fetch): Promise<string> {
  const apiUrl = `https://api.github.com/repos/${REPOSITORY}/releases/tags/v${FRP_VERSION}`
  const apiHeaders: Record<string, string> = {
    'Accept': 'application/vnd.github+json',
    'User-Agent': 'hackycy-cli-frp-manifest-generator',
    'X-GitHub-Api-Version': '2022-11-28',
  }
  if (process.env.GITHUB_TOKEN)
    apiHeaders.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`

  const release = releaseSchema.parse(JSON.parse(new TextDecoder().decode(await fetchBytes(fetchImpl, apiUrl, apiHeaders))))
  if (release.tag_name !== `v${FRP_VERSION}` || release.draft || release.prerelease)
    throw new Error(`Expected published FRP release v${FRP_VERSION}, received ${release.tag_name}`)

  const assets = new Map(release.assets.map(asset => [asset.name, asset]))
  const checksumAsset = assets.get(CHECKSUM_ASSET)
  if (!checksumAsset)
    throw new Error(`FRP v${FRP_VERSION} does not contain ${CHECKSUM_ASSET}`)
  if (checksumAsset.browser_download_url !== expectedDownloadUrl(CHECKSUM_ASSET))
    throw new Error(`Unexpected official download URL for ${CHECKSUM_ASSET}`)

  const checksumBytes = await fetchBytes(fetchImpl, checksumAsset.browser_download_url)
  if (sha256Bytes(checksumBytes) !== assetSha256(checksumAsset.digest, CHECKSUM_ASSET))
    throw new Error(`${CHECKSUM_ASSET} does not match its GitHub release digest`)
  const checksums = parseFrpChecksums(new TextDecoder().decode(checksumBytes))

  const artifacts: GeneratedFrpArtifact[] = []
  for (const target of supportedTargets()) {
    const asset = assets.get(target.archive)
    if (!asset)
      throw new Error(`FRP v${FRP_VERSION} does not contain ${target.archive}`)
    if (asset.browser_download_url !== expectedDownloadUrl(target.archive))
      throw new Error(`Unexpected official download URL for ${target.archive}`)

    const metadataSha256 = assetSha256(asset.digest, target.archive)
    const publishedSha256 = checksums.get(target.archive)
    if (!publishedSha256 || publishedSha256 !== metadataSha256)
      throw new Error(`${target.archive} has inconsistent official SHA-256 digests`)

    console.log(`Verifying ${target.archive}`)
    const archive = await fetchBytes(fetchImpl, asset.browser_download_url)
    if (sha256Bytes(archive) !== publishedSha256)
      throw new Error(`${target.archive} does not match its official SHA-256 digest`)
    const binaries = extractFrpBinaries(archive, target.archive, target.platform)
    artifacts.push({
      ...target,
      sha256: publishedSha256,
      frpcSha256: sha256Bytes(binaries.frpc),
      frpsSha256: sha256Bytes(binaries.frps),
    })
  }
  return renderFrpManifest(artifacts)
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check')
  const generated = await generateFrpManifest()
  if (check) {
    const current = await readFile(OUTPUT_PATH, 'utf8').catch(() => '')
    if (current !== generated)
      throw new Error(`FRP manifest is stale. Run: bun run generate:frp-manifest`)
    console.log(`FRP v${FRP_VERSION} manifest is current`)
    return
  }
  await writeFile(OUTPUT_PATH, generated)
  console.log(`Generated ${path.relative(process.cwd(), OUTPUT_PATH)} for FRP v${FRP_VERSION}`)
}

if (import.meta.main) {
  await main().catch((cause) => {
    console.error(cause instanceof Error ? cause.message : cause)
    process.exit(1)
  })
}
