// Code generated by ent, DO NOT EDIT.

package node

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hackycy/hackycy-cli/ent/node/controllerbinding"
)

// ControllerBinding is the model entity for the ControllerBinding schema.
type ControllerBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ControllerPublic holds the value of the "controller_public" field.
	ControllerPublic []byte `json:"controller_public,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ControllerBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case controllerbinding.FieldControllerPublic:
			values[i] = new([]byte)
		case controllerbinding.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ControllerBinding fields.
func (_m *ControllerBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case controllerbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case controllerbinding.FieldControllerPublic:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field controller_public", values[i])
			} else if value != nil {
				_m.ControllerPublic = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ControllerBinding.
// This includes values selected through modifiers, order, etc.
func (_m *ControllerBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ControllerBinding.
// Note that you need to call ControllerBinding.Unwrap() before calling this method if this ControllerBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ControllerBinding) Update() *ControllerBindingUpdateOne {
	return NewControllerBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ControllerBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ControllerBinding) Unwrap() *ControllerBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("node: ControllerBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ControllerBinding) String() string {
	var builder strings.Builder
	builder.WriteString("ControllerBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("controller_public=")
	builder.WriteString(fmt.Sprintf("%v", _m.ControllerPublic))
	builder.WriteByte(')')
	return builder.String()
}

// ControllerBindings is a parsable slice of ControllerBinding.
type ControllerBindings []*ControllerBinding
