// Code generated by ent, DO NOT EDIT.

package node

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/node/identity"
)

// IdentityCreate is the builder for creating a Identity entity.
type IdentityCreate struct {
	config
	mutation *IdentityMutation
	hooks    []Hook
}

// SetNodeID sets the "node_id" field.
func (_c *IdentityCreate) SetNodeID(v string) *IdentityCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetPrivateKey sets the "private_key" field.
func (_c *IdentityCreate) SetPrivateKey(v []byte) *IdentityCreate {
	_c.mutation.SetPrivateKey(v)
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *IdentityCreate) SetPublicKey(v []byte) *IdentityCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetID sets the "id" field.
func (_c *IdentityCreate) SetID(v int) *IdentityCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the IdentityMutation object of the builder.
func (_c *IdentityCreate) Mutation() *IdentityMutation {
	return _c.mutation
}

// Save creates the Identity in the database.
func (_c *IdentityCreate) Save(ctx context.Context) (*Identity, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdentityCreate) SaveX(ctx context.Context) *Identity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdentityCreate) check() error {
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`node: missing required field "Identity.node_id"`)}
	}
	if _, ok := _c.mutation.PrivateKey(); !ok {
		return &ValidationError{Name: "private_key", err: errors.New(`node: missing required field "Identity.private_key"`)}
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`node: missing required field "Identity.public_key"`)}
	}
	return nil
}

func (_c *IdentityCreate) sqlSave(ctx context.Context) (*Identity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdentityCreate) createSpec() (*Identity, *sqlgraph.CreateSpec) {
	var (
		_node = &Identity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(identity.Table, sqlgraph.NewFieldSpec(identity.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(identity.FieldNodeID, field.TypeString, value)
		_node.NodeID = value
	}
	if value, ok := _c.mutation.PrivateKey(); ok {
		_spec.SetField(identity.FieldPrivateKey, field.TypeBytes, value)
		_node.PrivateKey = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(identity.FieldPublicKey, field.TypeBytes, value)
		_node.PublicKey = value
	}
	return _node, _spec
}

// IdentityCreateBulk is the builder for creating many Identity entities in bulk.
type IdentityCreateBulk struct {
	config
	err      error
	builders []*IdentityCreate
}

// Save creates the Identity entities in the database.
func (_c *IdentityCreateBulk) Save(ctx context.Context) ([]*Identity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Identity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdentityCreateBulk) SaveX(ctx context.Context) []*Identity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
