// Code generated by ent, DO NOT EDIT.

package node

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/node/predicate"
	"github.com/hackycy/hackycy-cli/ent/node/runtimestate"
)

// RuntimeStateUpdate is the builder for updating RuntimeState entities.
type RuntimeStateUpdate struct {
	config
	hooks    []Hook
	mutation *RuntimeStateMutation
}

// Where appends a list predicates to the RuntimeStateUpdate builder.
func (_u *RuntimeStateUpdate) Where(ps ...predicate.RuntimeState) *RuntimeStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHighestRevision sets the "highest_revision" field.
func (_u *RuntimeStateUpdate) SetHighestRevision(v int64) *RuntimeStateUpdate {
	_u.mutation.ResetHighestRevision()
	_u.mutation.SetHighestRevision(v)
	return _u
}

// SetNillableHighestRevision sets the "highest_revision" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableHighestRevision(v *int64) *RuntimeStateUpdate {
	if v != nil {
		_u.SetHighestRevision(*v)
	}
	return _u
}

// AddHighestRevision adds value to the "highest_revision" field.
func (_u *RuntimeStateUpdate) AddHighestRevision(v int64) *RuntimeStateUpdate {
	_u.mutation.AddHighestRevision(v)
	return _u
}

// SetHighestDigest sets the "highest_digest" field.
func (_u *RuntimeStateUpdate) SetHighestDigest(v string) *RuntimeStateUpdate {
	_u.mutation.SetHighestDigest(v)
	return _u
}

// SetNillableHighestDigest sets the "highest_digest" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableHighestDigest(v *string) *RuntimeStateUpdate {
	if v != nil {
		_u.SetHighestDigest(*v)
	}
	return _u
}

// SetCandidate sets the "candidate" field.
func (_u *RuntimeStateUpdate) SetCandidate(v []byte) *RuntimeStateUpdate {
	_u.mutation.SetCandidate(v)
	return _u
}

// ClearCandidate clears the value of the "candidate" field.
func (_u *RuntimeStateUpdate) ClearCandidate() *RuntimeStateUpdate {
	_u.mutation.ClearCandidate()
	return _u
}

// SetPhase sets the "phase" field.
func (_u *RuntimeStateUpdate) SetPhase(v runtimestate.Phase) *RuntimeStateUpdate {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillablePhase(v *runtimestate.Phase) *RuntimeStateUpdate {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetAppliedRevision sets the "applied_revision" field.
func (_u *RuntimeStateUpdate) SetAppliedRevision(v int64) *RuntimeStateUpdate {
	_u.mutation.ResetAppliedRevision()
	_u.mutation.SetAppliedRevision(v)
	return _u
}

// SetNillableAppliedRevision sets the "applied_revision" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableAppliedRevision(v *int64) *RuntimeStateUpdate {
	if v != nil {
		_u.SetAppliedRevision(*v)
	}
	return _u
}

// AddAppliedRevision adds value to the "applied_revision" field.
func (_u *RuntimeStateUpdate) AddAppliedRevision(v int64) *RuntimeStateUpdate {
	_u.mutation.AddAppliedRevision(v)
	return _u
}

// SetLastGood sets the "last_good" field.
func (_u *RuntimeStateUpdate) SetLastGood(v []byte) *RuntimeStateUpdate {
	_u.mutation.SetLastGood(v)
	return _u
}

// ClearLastGood clears the value of the "last_good" field.
func (_u *RuntimeStateUpdate) ClearLastGood() *RuntimeStateUpdate {
	_u.mutation.ClearLastGood()
	return _u
}

// SetBootDisabled sets the "boot_disabled" field.
func (_u *RuntimeStateUpdate) SetBootDisabled(v bool) *RuntimeStateUpdate {
	_u.mutation.SetBootDisabled(v)
	return _u
}

// SetNillableBootDisabled sets the "boot_disabled" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableBootDisabled(v *bool) *RuntimeStateUpdate {
	if v != nil {
		_u.SetBootDisabled(*v)
	}
	return _u
}

// SetDisabledComplete sets the "disabled_complete" field.
func (_u *RuntimeStateUpdate) SetDisabledComplete(v bool) *RuntimeStateUpdate {
	_u.mutation.SetDisabledComplete(v)
	return _u
}

// SetNillableDisabledComplete sets the "disabled_complete" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableDisabledComplete(v *bool) *RuntimeStateUpdate {
	if v != nil {
		_u.SetDisabledComplete(*v)
	}
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *RuntimeStateUpdate) SetFailureCode(v string) *RuntimeStateUpdate {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableFailureCode(v *string) *RuntimeStateUpdate {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// SetOwnerPid sets the "owner_pid" field.
func (_u *RuntimeStateUpdate) SetOwnerPid(v int) *RuntimeStateUpdate {
	_u.mutation.ResetOwnerPid()
	_u.mutation.SetOwnerPid(v)
	return _u
}

// SetNillableOwnerPid sets the "owner_pid" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableOwnerPid(v *int) *RuntimeStateUpdate {
	if v != nil {
		_u.SetOwnerPid(*v)
	}
	return _u
}

// AddOwnerPid adds value to the "owner_pid" field.
func (_u *RuntimeStateUpdate) AddOwnerPid(v int) *RuntimeStateUpdate {
	_u.mutation.AddOwnerPid(v)
	return _u
}

// SetOwnerCreateTime sets the "owner_create_time" field.
func (_u *RuntimeStateUpdate) SetOwnerCreateTime(v int64) *RuntimeStateUpdate {
	_u.mutation.ResetOwnerCreateTime()
	_u.mutation.SetOwnerCreateTime(v)
	return _u
}

// SetNillableOwnerCreateTime sets the "owner_create_time" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableOwnerCreateTime(v *int64) *RuntimeStateUpdate {
	if v != nil {
		_u.SetOwnerCreateTime(*v)
	}
	return _u
}

// AddOwnerCreateTime adds value to the "owner_create_time" field.
func (_u *RuntimeStateUpdate) AddOwnerCreateTime(v int64) *RuntimeStateUpdate {
	_u.mutation.AddOwnerCreateTime(v)
	return _u
}

// SetOwnerBinary sets the "owner_binary" field.
func (_u *RuntimeStateUpdate) SetOwnerBinary(v string) *RuntimeStateUpdate {
	_u.mutation.SetOwnerBinary(v)
	return _u
}

// SetNillableOwnerBinary sets the "owner_binary" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableOwnerBinary(v *string) *RuntimeStateUpdate {
	if v != nil {
		_u.SetOwnerBinary(*v)
	}
	return _u
}

// SetOwnerConfig sets the "owner_config" field.
func (_u *RuntimeStateUpdate) SetOwnerConfig(v string) *RuntimeStateUpdate {
	_u.mutation.SetOwnerConfig(v)
	return _u
}

// SetNillableOwnerConfig sets the "owner_config" field if the given value is not nil.
func (_u *RuntimeStateUpdate) SetNillableOwnerConfig(v *string) *RuntimeStateUpdate {
	if v != nil {
		_u.SetOwnerConfig(*v)
	}
	return _u
}

// Mutation returns the RuntimeStateMutation object of the builder.
func (_u *RuntimeStateUpdate) Mutation() *RuntimeStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RuntimeStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuntimeStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RuntimeStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuntimeStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuntimeStateUpdate) check() error {
	if v, ok := _u.mutation.Phase(); ok {
		if err := runtimestate.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`node: validator failed for field "RuntimeState.phase": %w`, err)}
		}
	}
	return nil
}

func (_u *RuntimeStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runtimestate.Table, runtimestate.Columns, sqlgraph.NewFieldSpec(runtimestate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.HighestRevision(); ok {
		_spec.SetField(runtimestate.FieldHighestRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHighestRevision(); ok {
		_spec.AddField(runtimestate.FieldHighestRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.HighestDigest(); ok {
		_spec.SetField(runtimestate.FieldHighestDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Candidate(); ok {
		_spec.SetField(runtimestate.FieldCandidate, field.TypeBytes, value)
	}
	if _u.mutation.CandidateCleared() {
		_spec.ClearField(runtimestate.FieldCandidate, field.TypeBytes)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(runtimestate.FieldPhase, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AppliedRevision(); ok {
		_spec.SetField(runtimestate.FieldAppliedRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppliedRevision(); ok {
		_spec.AddField(runtimestate.FieldAppliedRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastGood(); ok {
		_spec.SetField(runtimestate.FieldLastGood, field.TypeBytes, value)
	}
	if _u.mutation.LastGoodCleared() {
		_spec.ClearField(runtimestate.FieldLastGood, field.TypeBytes)
	}
	if value, ok := _u.mutation.BootDisabled(); ok {
		_spec.SetField(runtimestate.FieldBootDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisabledComplete(); ok {
		_spec.SetField(runtimestate.FieldDisabledComplete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(runtimestate.FieldFailureCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerPid(); ok {
		_spec.SetField(runtimestate.FieldOwnerPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnerPid(); ok {
		_spec.AddField(runtimestate.FieldOwnerPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OwnerCreateTime(); ok {
		_spec.SetField(runtimestate.FieldOwnerCreateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerCreateTime(); ok {
		_spec.AddField(runtimestate.FieldOwnerCreateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerBinary(); ok {
		_spec.SetField(runtimestate.FieldOwnerBinary, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerConfig(); ok {
		_spec.SetField(runtimestate.FieldOwnerConfig, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runtimestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RuntimeStateUpdateOne is the builder for updating a single RuntimeState entity.
type RuntimeStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RuntimeStateMutation
}

// SetHighestRevision sets the "highest_revision" field.
func (_u *RuntimeStateUpdateOne) SetHighestRevision(v int64) *RuntimeStateUpdateOne {
	_u.mutation.ResetHighestRevision()
	_u.mutation.SetHighestRevision(v)
	return _u
}

// SetNillableHighestRevision sets the "highest_revision" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableHighestRevision(v *int64) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetHighestRevision(*v)
	}
	return _u
}

// AddHighestRevision adds value to the "highest_revision" field.
func (_u *RuntimeStateUpdateOne) AddHighestRevision(v int64) *RuntimeStateUpdateOne {
	_u.mutation.AddHighestRevision(v)
	return _u
}

// SetHighestDigest sets the "highest_digest" field.
func (_u *RuntimeStateUpdateOne) SetHighestDigest(v string) *RuntimeStateUpdateOne {
	_u.mutation.SetHighestDigest(v)
	return _u
}

// SetNillableHighestDigest sets the "highest_digest" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableHighestDigest(v *string) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetHighestDigest(*v)
	}
	return _u
}

// SetCandidate sets the "candidate" field.
func (_u *RuntimeStateUpdateOne) SetCandidate(v []byte) *RuntimeStateUpdateOne {
	_u.mutation.SetCandidate(v)
	return _u
}

// ClearCandidate clears the value of the "candidate" field.
func (_u *RuntimeStateUpdateOne) ClearCandidate() *RuntimeStateUpdateOne {
	_u.mutation.ClearCandidate()
	return _u
}

// SetPhase sets the "phase" field.
func (_u *RuntimeStateUpdateOne) SetPhase(v runtimestate.Phase) *RuntimeStateUpdateOne {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillablePhase(v *runtimestate.Phase) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetAppliedRevision sets the "applied_revision" field.
func (_u *RuntimeStateUpdateOne) SetAppliedRevision(v int64) *RuntimeStateUpdateOne {
	_u.mutation.ResetAppliedRevision()
	_u.mutation.SetAppliedRevision(v)
	return _u
}

// SetNillableAppliedRevision sets the "applied_revision" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableAppliedRevision(v *int64) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetAppliedRevision(*v)
	}
	return _u
}

// AddAppliedRevision adds value to the "applied_revision" field.
func (_u *RuntimeStateUpdateOne) AddAppliedRevision(v int64) *RuntimeStateUpdateOne {
	_u.mutation.AddAppliedRevision(v)
	return _u
}

// SetLastGood sets the "last_good" field.
func (_u *RuntimeStateUpdateOne) SetLastGood(v []byte) *RuntimeStateUpdateOne {
	_u.mutation.SetLastGood(v)
	return _u
}

// ClearLastGood clears the value of the "last_good" field.
func (_u *RuntimeStateUpdateOne) ClearLastGood() *RuntimeStateUpdateOne {
	_u.mutation.ClearLastGood()
	return _u
}

// SetBootDisabled sets the "boot_disabled" field.
func (_u *RuntimeStateUpdateOne) SetBootDisabled(v bool) *RuntimeStateUpdateOne {
	_u.mutation.SetBootDisabled(v)
	return _u
}

// SetNillableBootDisabled sets the "boot_disabled" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableBootDisabled(v *bool) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetBootDisabled(*v)
	}
	return _u
}

// SetDisabledComplete sets the "disabled_complete" field.
func (_u *RuntimeStateUpdateOne) SetDisabledComplete(v bool) *RuntimeStateUpdateOne {
	_u.mutation.SetDisabledComplete(v)
	return _u
}

// SetNillableDisabledComplete sets the "disabled_complete" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableDisabledComplete(v *bool) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetDisabledComplete(*v)
	}
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *RuntimeStateUpdateOne) SetFailureCode(v string) *RuntimeStateUpdateOne {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableFailureCode(v *string) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// SetOwnerPid sets the "owner_pid" field.
func (_u *RuntimeStateUpdateOne) SetOwnerPid(v int) *RuntimeStateUpdateOne {
	_u.mutation.ResetOwnerPid()
	_u.mutation.SetOwnerPid(v)
	return _u
}

// SetNillableOwnerPid sets the "owner_pid" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableOwnerPid(v *int) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetOwnerPid(*v)
	}
	return _u
}

// AddOwnerPid adds value to the "owner_pid" field.
func (_u *RuntimeStateUpdateOne) AddOwnerPid(v int) *RuntimeStateUpdateOne {
	_u.mutation.AddOwnerPid(v)
	return _u
}

// SetOwnerCreateTime sets the "owner_create_time" field.
func (_u *RuntimeStateUpdateOne) SetOwnerCreateTime(v int64) *RuntimeStateUpdateOne {
	_u.mutation.ResetOwnerCreateTime()
	_u.mutation.SetOwnerCreateTime(v)
	return _u
}

// SetNillableOwnerCreateTime sets the "owner_create_time" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableOwnerCreateTime(v *int64) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetOwnerCreateTime(*v)
	}
	return _u
}

// AddOwnerCreateTime adds value to the "owner_create_time" field.
func (_u *RuntimeStateUpdateOne) AddOwnerCreateTime(v int64) *RuntimeStateUpdateOne {
	_u.mutation.AddOwnerCreateTime(v)
	return _u
}

// SetOwnerBinary sets the "owner_binary" field.
func (_u *RuntimeStateUpdateOne) SetOwnerBinary(v string) *RuntimeStateUpdateOne {
	_u.mutation.SetOwnerBinary(v)
	return _u
}

// SetNillableOwnerBinary sets the "owner_binary" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableOwnerBinary(v *string) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetOwnerBinary(*v)
	}
	return _u
}

// SetOwnerConfig sets the "owner_config" field.
func (_u *RuntimeStateUpdateOne) SetOwnerConfig(v string) *RuntimeStateUpdateOne {
	_u.mutation.SetOwnerConfig(v)
	return _u
}

// SetNillableOwnerConfig sets the "owner_config" field if the given value is not nil.
func (_u *RuntimeStateUpdateOne) SetNillableOwnerConfig(v *string) *RuntimeStateUpdateOne {
	if v != nil {
		_u.SetOwnerConfig(*v)
	}
	return _u
}

// Mutation returns the RuntimeStateMutation object of the builder.
func (_u *RuntimeStateUpdateOne) Mutation() *RuntimeStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the RuntimeStateUpdate builder.
func (_u *RuntimeStateUpdateOne) Where(ps ...predicate.RuntimeState) *RuntimeStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RuntimeStateUpdateOne) Select(field string, fields ...string) *RuntimeStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RuntimeState entity.
func (_u *RuntimeStateUpdateOne) Save(ctx context.Context) (*RuntimeState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuntimeStateUpdateOne) SaveX(ctx context.Context) *RuntimeState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RuntimeStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuntimeStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuntimeStateUpdateOne) check() error {
	if v, ok := _u.mutation.Phase(); ok {
		if err := runtimestate.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`node: validator failed for field "RuntimeState.phase": %w`, err)}
		}
	}
	return nil
}

func (_u *RuntimeStateUpdateOne) sqlSave(ctx context.Context) (_node *RuntimeState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runtimestate.Table, runtimestate.Columns, sqlgraph.NewFieldSpec(runtimestate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`node: missing "RuntimeState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runtimestate.FieldID)
		for _, f := range fields {
			if !runtimestate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("node: invalid field %q for query", f)}
			}
			if f != runtimestate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.HighestRevision(); ok {
		_spec.SetField(runtimestate.FieldHighestRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHighestRevision(); ok {
		_spec.AddField(runtimestate.FieldHighestRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.HighestDigest(); ok {
		_spec.SetField(runtimestate.FieldHighestDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Candidate(); ok {
		_spec.SetField(runtimestate.FieldCandidate, field.TypeBytes, value)
	}
	if _u.mutation.CandidateCleared() {
		_spec.ClearField(runtimestate.FieldCandidate, field.TypeBytes)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(runtimestate.FieldPhase, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AppliedRevision(); ok {
		_spec.SetField(runtimestate.FieldAppliedRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAppliedRevision(); ok {
		_spec.AddField(runtimestate.FieldAppliedRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastGood(); ok {
		_spec.SetField(runtimestate.FieldLastGood, field.TypeBytes, value)
	}
	if _u.mutation.LastGoodCleared() {
		_spec.ClearField(runtimestate.FieldLastGood, field.TypeBytes)
	}
	if value, ok := _u.mutation.BootDisabled(); ok {
		_spec.SetField(runtimestate.FieldBootDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisabledComplete(); ok {
		_spec.SetField(runtimestate.FieldDisabledComplete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(runtimestate.FieldFailureCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerPid(); ok {
		_spec.SetField(runtimestate.FieldOwnerPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnerPid(); ok {
		_spec.AddField(runtimestate.FieldOwnerPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OwnerCreateTime(); ok {
		_spec.SetField(runtimestate.FieldOwnerCreateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerCreateTime(); ok {
		_spec.AddField(runtimestate.FieldOwnerCreateTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerBinary(); ok {
		_spec.SetField(runtimestate.FieldOwnerBinary, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerConfig(); ok {
		_spec.SetField(runtimestate.FieldOwnerConfig, field.TypeString, value)
	}
	_node = &RuntimeState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runtimestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
