// Code generated by ent, DO NOT EDIT.

package node

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/node/runtimestate"
)

// RuntimeStateCreate is the builder for creating a RuntimeState entity.
type RuntimeStateCreate struct {
	config
	mutation *RuntimeStateMutation
	hooks    []Hook
}

// SetHighestRevision sets the "highest_revision" field.
func (_c *RuntimeStateCreate) SetHighestRevision(v int64) *RuntimeStateCreate {
	_c.mutation.SetHighestRevision(v)
	return _c
}

// SetNillableHighestRevision sets the "highest_revision" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableHighestRevision(v *int64) *RuntimeStateCreate {
	if v != nil {
		_c.SetHighestRevision(*v)
	}
	return _c
}

// SetHighestDigest sets the "highest_digest" field.
func (_c *RuntimeStateCreate) SetHighestDigest(v string) *RuntimeStateCreate {
	_c.mutation.SetHighestDigest(v)
	return _c
}

// SetNillableHighestDigest sets the "highest_digest" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableHighestDigest(v *string) *RuntimeStateCreate {
	if v != nil {
		_c.SetHighestDigest(*v)
	}
	return _c
}

// SetCandidate sets the "candidate" field.
func (_c *RuntimeStateCreate) SetCandidate(v []byte) *RuntimeStateCreate {
	_c.mutation.SetCandidate(v)
	return _c
}

// SetPhase sets the "phase" field.
func (_c *RuntimeStateCreate) SetPhase(v runtimestate.Phase) *RuntimeStateCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillablePhase(v *runtimestate.Phase) *RuntimeStateCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetAppliedRevision sets the "applied_revision" field.
func (_c *RuntimeStateCreate) SetAppliedRevision(v int64) *RuntimeStateCreate {
	_c.mutation.SetAppliedRevision(v)
	return _c
}

// SetNillableAppliedRevision sets the "applied_revision" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableAppliedRevision(v *int64) *RuntimeStateCreate {
	if v != nil {
		_c.SetAppliedRevision(*v)
	}
	return _c
}

// SetLastGood sets the "last_good" field.
func (_c *RuntimeStateCreate) SetLastGood(v []byte) *RuntimeStateCreate {
	_c.mutation.SetLastGood(v)
	return _c
}

// SetBootDisabled sets the "boot_disabled" field.
func (_c *RuntimeStateCreate) SetBootDisabled(v bool) *RuntimeStateCreate {
	_c.mutation.SetBootDisabled(v)
	return _c
}

// SetNillableBootDisabled sets the "boot_disabled" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableBootDisabled(v *bool) *RuntimeStateCreate {
	if v != nil {
		_c.SetBootDisabled(*v)
	}
	return _c
}

// SetDisabledComplete sets the "disabled_complete" field.
func (_c *RuntimeStateCreate) SetDisabledComplete(v bool) *RuntimeStateCreate {
	_c.mutation.SetDisabledComplete(v)
	return _c
}

// SetNillableDisabledComplete sets the "disabled_complete" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableDisabledComplete(v *bool) *RuntimeStateCreate {
	if v != nil {
		_c.SetDisabledComplete(*v)
	}
	return _c
}

// SetFailureCode sets the "failure_code" field.
func (_c *RuntimeStateCreate) SetFailureCode(v string) *RuntimeStateCreate {
	_c.mutation.SetFailureCode(v)
	return _c
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableFailureCode(v *string) *RuntimeStateCreate {
	if v != nil {
		_c.SetFailureCode(*v)
	}
	return _c
}

// SetOwnerPid sets the "owner_pid" field.
func (_c *RuntimeStateCreate) SetOwnerPid(v int) *RuntimeStateCreate {
	_c.mutation.SetOwnerPid(v)
	return _c
}

// SetNillableOwnerPid sets the "owner_pid" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableOwnerPid(v *int) *RuntimeStateCreate {
	if v != nil {
		_c.SetOwnerPid(*v)
	}
	return _c
}

// SetOwnerCreateTime sets the "owner_create_time" field.
func (_c *RuntimeStateCreate) SetOwnerCreateTime(v int64) *RuntimeStateCreate {
	_c.mutation.SetOwnerCreateTime(v)
	return _c
}

// SetNillableOwnerCreateTime sets the "owner_create_time" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableOwnerCreateTime(v *int64) *RuntimeStateCreate {
	if v != nil {
		_c.SetOwnerCreateTime(*v)
	}
	return _c
}

// SetOwnerBinary sets the "owner_binary" field.
func (_c *RuntimeStateCreate) SetOwnerBinary(v string) *RuntimeStateCreate {
	_c.mutation.SetOwnerBinary(v)
	return _c
}

// SetNillableOwnerBinary sets the "owner_binary" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableOwnerBinary(v *string) *RuntimeStateCreate {
	if v != nil {
		_c.SetOwnerBinary(*v)
	}
	return _c
}

// SetOwnerConfig sets the "owner_config" field.
func (_c *RuntimeStateCreate) SetOwnerConfig(v string) *RuntimeStateCreate {
	_c.mutation.SetOwnerConfig(v)
	return _c
}

// SetNillableOwnerConfig sets the "owner_config" field if the given value is not nil.
func (_c *RuntimeStateCreate) SetNillableOwnerConfig(v *string) *RuntimeStateCreate {
	if v != nil {
		_c.SetOwnerConfig(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RuntimeStateCreate) SetID(v int) *RuntimeStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RuntimeStateMutation object of the builder.
func (_c *RuntimeStateCreate) Mutation() *RuntimeStateMutation {
	return _c.mutation
}

// Save creates the RuntimeState in the database.
func (_c *RuntimeStateCreate) Save(ctx context.Context) (*RuntimeState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RuntimeStateCreate) SaveX(ctx context.Context) *RuntimeState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuntimeStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuntimeStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RuntimeStateCreate) defaults() {
	if _, ok := _c.mutation.HighestRevision(); !ok {
		v := runtimestate.DefaultHighestRevision
		_c.mutation.SetHighestRevision(v)
	}
	if _, ok := _c.mutation.HighestDigest(); !ok {
		v := runtimestate.DefaultHighestDigest
		_c.mutation.SetHighestDigest(v)
	}
	if _, ok := _c.mutation.Phase(); !ok {
		v := runtimestate.DefaultPhase
		_c.mutation.SetPhase(v)
	}
	if _, ok := _c.mutation.AppliedRevision(); !ok {
		v := runtimestate.DefaultAppliedRevision
		_c.mutation.SetAppliedRevision(v)
	}
	if _, ok := _c.mutation.BootDisabled(); !ok {
		v := runtimestate.DefaultBootDisabled
		_c.mutation.SetBootDisabled(v)
	}
	if _, ok := _c.mutation.DisabledComplete(); !ok {
		v := runtimestate.DefaultDisabledComplete
		_c.mutation.SetDisabledComplete(v)
	}
	if _, ok := _c.mutation.FailureCode(); !ok {
		v := runtimestate.DefaultFailureCode
		_c.mutation.SetFailureCode(v)
	}
	if _, ok := _c.mutation.OwnerPid(); !ok {
		v := runtimestate.DefaultOwnerPid
		_c.mutation.SetOwnerPid(v)
	}
	if _, ok := _c.mutation.OwnerCreateTime(); !ok {
		v := runtimestate.DefaultOwnerCreateTime
		_c.mutation.SetOwnerCreateTime(v)
	}
	if _, ok := _c.mutation.OwnerBinary(); !ok {
		v := runtimestate.DefaultOwnerBinary
		_c.mutation.SetOwnerBinary(v)
	}
	if _, ok := _c.mutation.OwnerConfig(); !ok {
		v := runtimestate.DefaultOwnerConfig
		_c.mutation.SetOwnerConfig(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RuntimeStateCreate) check() error {
	if _, ok := _c.mutation.HighestRevision(); !ok {
		return &ValidationError{Name: "highest_revision", err: errors.New(`node: missing required field "RuntimeState.highest_revision"`)}
	}
	if _, ok := _c.mutation.HighestDigest(); !ok {
		return &ValidationError{Name: "highest_digest", err: errors.New(`node: missing required field "RuntimeState.highest_digest"`)}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`node: missing required field "RuntimeState.phase"`)}
	}
	if v, ok := _c.mutation.Phase(); ok {
		if err := runtimestate.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`node: validator failed for field "RuntimeState.phase": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppliedRevision(); !ok {
		return &ValidationError{Name: "applied_revision", err: errors.New(`node: missing required field "RuntimeState.applied_revision"`)}
	}
	if _, ok := _c.mutation.BootDisabled(); !ok {
		return &ValidationError{Name: "boot_disabled", err: errors.New(`node: missing required field "RuntimeState.boot_disabled"`)}
	}
	if _, ok := _c.mutation.DisabledComplete(); !ok {
		return &ValidationError{Name: "disabled_complete", err: errors.New(`node: missing required field "RuntimeState.disabled_complete"`)}
	}
	if _, ok := _c.mutation.FailureCode(); !ok {
		return &ValidationError{Name: "failure_code", err: errors.New(`node: missing required field "RuntimeState.failure_code"`)}
	}
	if _, ok := _c.mutation.OwnerPid(); !ok {
		return &ValidationError{Name: "owner_pid", err: errors.New(`node: missing required field "RuntimeState.owner_pid"`)}
	}
	if _, ok := _c.mutation.OwnerCreateTime(); !ok {
		return &ValidationError{Name: "owner_create_time", err: errors.New(`node: missing required field "RuntimeState.owner_create_time"`)}
	}
	if _, ok := _c.mutation.OwnerBinary(); !ok {
		return &ValidationError{Name: "owner_binary", err: errors.New(`node: missing required field "RuntimeState.owner_binary"`)}
	}
	if _, ok := _c.mutation.OwnerConfig(); !ok {
		return &ValidationError{Name: "owner_config", err: errors.New(`node: missing required field "RuntimeState.owner_config"`)}
	}
	return nil
}

func (_c *RuntimeStateCreate) sqlSave(ctx context.Context) (*RuntimeState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RuntimeStateCreate) createSpec() (*RuntimeState, *sqlgraph.CreateSpec) {
	var (
		_node = &RuntimeState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(runtimestate.Table, sqlgraph.NewFieldSpec(runtimestate.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.HighestRevision(); ok {
		_spec.SetField(runtimestate.FieldHighestRevision, field.TypeInt64, value)
		_node.HighestRevision = value
	}
	if value, ok := _c.mutation.HighestDigest(); ok {
		_spec.SetField(runtimestate.FieldHighestDigest, field.TypeString, value)
		_node.HighestDigest = value
	}
	if value, ok := _c.mutation.Candidate(); ok {
		_spec.SetField(runtimestate.FieldCandidate, field.TypeBytes, value)
		_node.Candidate = &value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(runtimestate.FieldPhase, field.TypeEnum, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.AppliedRevision(); ok {
		_spec.SetField(runtimestate.FieldAppliedRevision, field.TypeInt64, value)
		_node.AppliedRevision = value
	}
	if value, ok := _c.mutation.LastGood(); ok {
		_spec.SetField(runtimestate.FieldLastGood, field.TypeBytes, value)
		_node.LastGood = &value
	}
	if value, ok := _c.mutation.BootDisabled(); ok {
		_spec.SetField(runtimestate.FieldBootDisabled, field.TypeBool, value)
		_node.BootDisabled = value
	}
	if value, ok := _c.mutation.DisabledComplete(); ok {
		_spec.SetField(runtimestate.FieldDisabledComplete, field.TypeBool, value)
		_node.DisabledComplete = value
	}
	if value, ok := _c.mutation.FailureCode(); ok {
		_spec.SetField(runtimestate.FieldFailureCode, field.TypeString, value)
		_node.FailureCode = value
	}
	if value, ok := _c.mutation.OwnerPid(); ok {
		_spec.SetField(runtimestate.FieldOwnerPid, field.TypeInt, value)
		_node.OwnerPid = value
	}
	if value, ok := _c.mutation.OwnerCreateTime(); ok {
		_spec.SetField(runtimestate.FieldOwnerCreateTime, field.TypeInt64, value)
		_node.OwnerCreateTime = value
	}
	if value, ok := _c.mutation.OwnerBinary(); ok {
		_spec.SetField(runtimestate.FieldOwnerBinary, field.TypeString, value)
		_node.OwnerBinary = value
	}
	if value, ok := _c.mutation.OwnerConfig(); ok {
		_spec.SetField(runtimestate.FieldOwnerConfig, field.TypeString, value)
		_node.OwnerConfig = value
	}
	return _node, _spec
}

// RuntimeStateCreateBulk is the builder for creating many RuntimeState entities in bulk.
type RuntimeStateCreateBulk struct {
	config
	err      error
	builders []*RuntimeStateCreate
}

// Save creates the RuntimeState entities in the database.
func (_c *RuntimeStateCreateBulk) Save(ctx context.Context) ([]*RuntimeState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RuntimeState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RuntimeStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RuntimeStateCreateBulk) SaveX(ctx context.Context) []*RuntimeState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuntimeStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuntimeStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
