// Code generated by ent, DO NOT EDIT.

package node

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackycy/hackycy-cli/ent/node/predicate"
	"github.com/hackycy/hackycy-cli/ent/node/runtimestate"
)

// RuntimeStateDelete is the builder for deleting a RuntimeState entity.
type RuntimeStateDelete struct {
	config
	hooks    []Hook
	mutation *RuntimeStateMutation
}

// Where appends a list predicates to the RuntimeStateDelete builder.
func (_d *RuntimeStateDelete) Where(ps ...predicate.RuntimeState) *RuntimeStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RuntimeStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RuntimeStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RuntimeStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(runtimestate.Table, sqlgraph.NewFieldSpec(runtimestate.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RuntimeStateDeleteOne is the builder for deleting a single RuntimeState entity.
type RuntimeStateDeleteOne struct {
	_d *RuntimeStateDelete
}

// Where appends a list predicates to the RuntimeStateDelete builder.
func (_d *RuntimeStateDeleteOne) Where(ps ...predicate.RuntimeState) *RuntimeStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RuntimeStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{runtimestate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RuntimeStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
