// Code generated by ent, DO NOT EDIT.

package nodeobservation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the nodeobservation type in the database.
	Label = "node_observation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldStatusJSON holds the string denoting the status_json field in the database.
	FieldStatusJSON = "status_json"
	// FieldStatusObservedAt holds the string denoting the status_observed_at field in the database.
	FieldStatusObservedAt = "status_observed_at"
	// FieldFailureCode holds the string denoting the failure_code field in the database.
	FieldFailureCode = "failure_code"
	// FieldAttemptedAt holds the string denoting the attempted_at field in the database.
	FieldAttemptedAt = "attempted_at"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// NodeFieldID holds the string denoting the ID field of the Node.
	NodeFieldID = "node_id"
	// Table holds the table name of the nodeobservation in the database.
	Table = "node_observations"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "node_observations"
	// NodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	NodeInverseTable = "nodes"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "node_id"
)

// Columns holds all SQL columns for nodeobservation fields.
var Columns = []string{
	FieldID,
	FieldNodeID,
	FieldStatusJSON,
	FieldStatusObservedAt,
	FieldFailureCode,
	FieldAttemptedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFailureCode holds the default value on creation for the "failure_code" field.
	DefaultFailureCode string
)

// OrderOption defines the ordering options for the NodeObservation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByStatusJSON orders the results by the status_json field.
func ByStatusJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusJSON, opts...).ToFunc()
}

// ByStatusObservedAt orders the results by the status_observed_at field.
func ByStatusObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusObservedAt, opts...).ToFunc()
}

// ByFailureCode orders the results by the failure_code field.
func ByFailureCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureCode, opts...).ToFunc()
}

// ByAttemptedAt orders the results by the attempted_at field.
func ByAttemptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptedAt, opts...).ToFunc()
}

// ByNodeField orders the results by node field.
func ByNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeStep(), sql.OrderByField(field, opts...))
	}
}
func newNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodeInverseTable, NodeFieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, NodeTable, NodeColumn),
	)
}
