// Code generated by ent, DO NOT EDIT.

package nodeobservation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLTE(FieldID, id))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldNodeID, v))
}

// StatusJSON applies equality check predicate on the "status_json" field. It's identical to StatusJSONEQ.
func StatusJSON(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldStatusJSON, v))
}

// StatusObservedAt applies equality check predicate on the "status_observed_at" field. It's identical to StatusObservedAtEQ.
func StatusObservedAt(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldStatusObservedAt, v))
}

// FailureCode applies equality check predicate on the "failure_code" field. It's identical to FailureCodeEQ.
func FailureCode(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldFailureCode, v))
}

// AttemptedAt applies equality check predicate on the "attempted_at" field. It's identical to AttemptedAtEQ.
func AttemptedAt(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldAttemptedAt, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContainsFold(FieldNodeID, v))
}

// StatusJSONEQ applies the EQ predicate on the "status_json" field.
func StatusJSONEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldStatusJSON, v))
}

// StatusJSONNEQ applies the NEQ predicate on the "status_json" field.
func StatusJSONNEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNEQ(FieldStatusJSON, v))
}

// StatusJSONIn applies the In predicate on the "status_json" field.
func StatusJSONIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldIn(FieldStatusJSON, vs...))
}

// StatusJSONNotIn applies the NotIn predicate on the "status_json" field.
func StatusJSONNotIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNotIn(FieldStatusJSON, vs...))
}

// StatusJSONGT applies the GT predicate on the "status_json" field.
func StatusJSONGT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGT(FieldStatusJSON, v))
}

// StatusJSONGTE applies the GTE predicate on the "status_json" field.
func StatusJSONGTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGTE(FieldStatusJSON, v))
}

// StatusJSONLT applies the LT predicate on the "status_json" field.
func StatusJSONLT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLT(FieldStatusJSON, v))
}

// StatusJSONLTE applies the LTE predicate on the "status_json" field.
func StatusJSONLTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLTE(FieldStatusJSON, v))
}

// StatusJSONContains applies the Contains predicate on the "status_json" field.
func StatusJSONContains(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContains(FieldStatusJSON, v))
}

// StatusJSONHasPrefix applies the HasPrefix predicate on the "status_json" field.
func StatusJSONHasPrefix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasPrefix(FieldStatusJSON, v))
}

// StatusJSONHasSuffix applies the HasSuffix predicate on the "status_json" field.
func StatusJSONHasSuffix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasSuffix(FieldStatusJSON, v))
}

// StatusJSONIsNil applies the IsNil predicate on the "status_json" field.
func StatusJSONIsNil() predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldIsNull(FieldStatusJSON))
}

// StatusJSONNotNil applies the NotNil predicate on the "status_json" field.
func StatusJSONNotNil() predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNotNull(FieldStatusJSON))
}

// StatusJSONEqualFold applies the EqualFold predicate on the "status_json" field.
func StatusJSONEqualFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEqualFold(FieldStatusJSON, v))
}

// StatusJSONContainsFold applies the ContainsFold predicate on the "status_json" field.
func StatusJSONContainsFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContainsFold(FieldStatusJSON, v))
}

// StatusObservedAtEQ applies the EQ predicate on the "status_observed_at" field.
func StatusObservedAtEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldStatusObservedAt, v))
}

// StatusObservedAtNEQ applies the NEQ predicate on the "status_observed_at" field.
func StatusObservedAtNEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNEQ(FieldStatusObservedAt, v))
}

// StatusObservedAtIn applies the In predicate on the "status_observed_at" field.
func StatusObservedAtIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldIn(FieldStatusObservedAt, vs...))
}

// StatusObservedAtNotIn applies the NotIn predicate on the "status_observed_at" field.
func StatusObservedAtNotIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNotIn(FieldStatusObservedAt, vs...))
}

// StatusObservedAtGT applies the GT predicate on the "status_observed_at" field.
func StatusObservedAtGT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGT(FieldStatusObservedAt, v))
}

// StatusObservedAtGTE applies the GTE predicate on the "status_observed_at" field.
func StatusObservedAtGTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGTE(FieldStatusObservedAt, v))
}

// StatusObservedAtLT applies the LT predicate on the "status_observed_at" field.
func StatusObservedAtLT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLT(FieldStatusObservedAt, v))
}

// StatusObservedAtLTE applies the LTE predicate on the "status_observed_at" field.
func StatusObservedAtLTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLTE(FieldStatusObservedAt, v))
}

// StatusObservedAtContains applies the Contains predicate on the "status_observed_at" field.
func StatusObservedAtContains(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContains(FieldStatusObservedAt, v))
}

// StatusObservedAtHasPrefix applies the HasPrefix predicate on the "status_observed_at" field.
func StatusObservedAtHasPrefix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasPrefix(FieldStatusObservedAt, v))
}

// StatusObservedAtHasSuffix applies the HasSuffix predicate on the "status_observed_at" field.
func StatusObservedAtHasSuffix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasSuffix(FieldStatusObservedAt, v))
}

// StatusObservedAtIsNil applies the IsNil predicate on the "status_observed_at" field.
func StatusObservedAtIsNil() predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldIsNull(FieldStatusObservedAt))
}

// StatusObservedAtNotNil applies the NotNil predicate on the "status_observed_at" field.
func StatusObservedAtNotNil() predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNotNull(FieldStatusObservedAt))
}

// StatusObservedAtEqualFold applies the EqualFold predicate on the "status_observed_at" field.
func StatusObservedAtEqualFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEqualFold(FieldStatusObservedAt, v))
}

// StatusObservedAtContainsFold applies the ContainsFold predicate on the "status_observed_at" field.
func StatusObservedAtContainsFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContainsFold(FieldStatusObservedAt, v))
}

// FailureCodeEQ applies the EQ predicate on the "failure_code" field.
func FailureCodeEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldFailureCode, v))
}

// FailureCodeNEQ applies the NEQ predicate on the "failure_code" field.
func FailureCodeNEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNEQ(FieldFailureCode, v))
}

// FailureCodeIn applies the In predicate on the "failure_code" field.
func FailureCodeIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldIn(FieldFailureCode, vs...))
}

// FailureCodeNotIn applies the NotIn predicate on the "failure_code" field.
func FailureCodeNotIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNotIn(FieldFailureCode, vs...))
}

// FailureCodeGT applies the GT predicate on the "failure_code" field.
func FailureCodeGT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGT(FieldFailureCode, v))
}

// FailureCodeGTE applies the GTE predicate on the "failure_code" field.
func FailureCodeGTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGTE(FieldFailureCode, v))
}

// FailureCodeLT applies the LT predicate on the "failure_code" field.
func FailureCodeLT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLT(FieldFailureCode, v))
}

// FailureCodeLTE applies the LTE predicate on the "failure_code" field.
func FailureCodeLTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLTE(FieldFailureCode, v))
}

// FailureCodeContains applies the Contains predicate on the "failure_code" field.
func FailureCodeContains(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContains(FieldFailureCode, v))
}

// FailureCodeHasPrefix applies the HasPrefix predicate on the "failure_code" field.
func FailureCodeHasPrefix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasPrefix(FieldFailureCode, v))
}

// FailureCodeHasSuffix applies the HasSuffix predicate on the "failure_code" field.
func FailureCodeHasSuffix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasSuffix(FieldFailureCode, v))
}

// FailureCodeEqualFold applies the EqualFold predicate on the "failure_code" field.
func FailureCodeEqualFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEqualFold(FieldFailureCode, v))
}

// FailureCodeContainsFold applies the ContainsFold predicate on the "failure_code" field.
func FailureCodeContainsFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContainsFold(FieldFailureCode, v))
}

// AttemptedAtEQ applies the EQ predicate on the "attempted_at" field.
func AttemptedAtEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEQ(FieldAttemptedAt, v))
}

// AttemptedAtNEQ applies the NEQ predicate on the "attempted_at" field.
func AttemptedAtNEQ(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNEQ(FieldAttemptedAt, v))
}

// AttemptedAtIn applies the In predicate on the "attempted_at" field.
func AttemptedAtIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldIn(FieldAttemptedAt, vs...))
}

// AttemptedAtNotIn applies the NotIn predicate on the "attempted_at" field.
func AttemptedAtNotIn(vs ...string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldNotIn(FieldAttemptedAt, vs...))
}

// AttemptedAtGT applies the GT predicate on the "attempted_at" field.
func AttemptedAtGT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGT(FieldAttemptedAt, v))
}

// AttemptedAtGTE applies the GTE predicate on the "attempted_at" field.
func AttemptedAtGTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldGTE(FieldAttemptedAt, v))
}

// AttemptedAtLT applies the LT predicate on the "attempted_at" field.
func AttemptedAtLT(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLT(FieldAttemptedAt, v))
}

// AttemptedAtLTE applies the LTE predicate on the "attempted_at" field.
func AttemptedAtLTE(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldLTE(FieldAttemptedAt, v))
}

// AttemptedAtContains applies the Contains predicate on the "attempted_at" field.
func AttemptedAtContains(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContains(FieldAttemptedAt, v))
}

// AttemptedAtHasPrefix applies the HasPrefix predicate on the "attempted_at" field.
func AttemptedAtHasPrefix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasPrefix(FieldAttemptedAt, v))
}

// AttemptedAtHasSuffix applies the HasSuffix predicate on the "attempted_at" field.
func AttemptedAtHasSuffix(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldHasSuffix(FieldAttemptedAt, v))
}

// AttemptedAtEqualFold applies the EqualFold predicate on the "attempted_at" field.
func AttemptedAtEqualFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldEqualFold(FieldAttemptedAt, v))
}

// AttemptedAtContainsFold applies the ContainsFold predicate on the "attempted_at" field.
func AttemptedAtContainsFold(v string) predicate.NodeObservation {
	return predicate.NodeObservation(sql.FieldContainsFold(FieldAttemptedAt, v))
}

// HasNode applies the HasEdge predicate on the "node" edge.
func HasNode() predicate.NodeObservation {
	return predicate.NodeObservation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, NodeTable, NodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeWith applies the HasEdge predicate on the "node" edge with a given conditions (other predicates).
func HasNodeWith(preds ...predicate.Node) predicate.NodeObservation {
	return predicate.NodeObservation(func(s *sql.Selector) {
		step := newNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NodeObservation) predicate.NodeObservation {
	return predicate.NodeObservation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NodeObservation) predicate.NodeObservation {
	return predicate.NodeObservation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NodeObservation) predicate.NodeObservation {
	return predicate.NodeObservation(sql.NotPredicates(p))
}
