// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Meta is the predicate function for meta builders.
type Meta func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// NodeManagementCandidate is the predicate function for nodemanagementcandidate builders.
type NodeManagementCandidate func(*sql.Selector)

// NodeObservation is the predicate function for nodeobservation builders.
type NodeObservation func(*sql.Selector)

// NodePortPool is the predicate function for nodeportpool builders.
type NodePortPool func(*sql.Selector)

// RemoteNode is the predicate function for remotenode builders.
type RemoteNode func(*sql.Selector)

// ServerClient is the predicate function for serverclient builders.
type ServerClient func(*sql.Selector)

// Tunnel is the predicate function for tunnel builders.
type Tunnel func(*sql.Selector)

// TunnelHTTPRoute is the predicate function for tunnelhttproute builders.
type TunnelHTTPRoute func(*sql.Selector)
