// Code generated by ent, DO NOT EDIT.

package tunnelhttproute

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tunnelhttproute type in the database.
	Label = "tunnel_http_route"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTunnelID holds the string denoting the tunnel_id field in the database.
	FieldTunnelID = "tunnel_id"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// EdgeTunnel holds the string denoting the tunnel edge name in mutations.
	EdgeTunnel = "tunnel"
	// Table holds the table name of the tunnelhttproute in the database.
	Table = "tunnel_http_routes"
	// TunnelTable is the table that holds the tunnel relation/edge.
	TunnelTable = "tunnel_http_routes"
	// TunnelInverseTable is the table name for the Tunnel entity.
	// It exists in this package in order to avoid circular dependency with the "tunnel" package.
	TunnelInverseTable = "tunnels"
	// TunnelColumn is the table column denoting the tunnel relation/edge.
	TunnelColumn = "tunnel_id"
)

// Columns holds all SQL columns for tunnelhttproute fields.
var Columns = []string{
	FieldID,
	FieldTunnelID,
	FieldHostname,
	FieldLocation,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TunnelHTTPRoute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTunnelID orders the results by the tunnel_id field.
func ByTunnelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTunnelID, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByTunnelField orders the results by tunnel field.
func ByTunnelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTunnelStep(), sql.OrderByField(field, opts...))
	}
}
func newTunnelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TunnelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TunnelTable, TunnelColumn),
	)
}
