// Code generated by ent, DO NOT EDIT.

package remotenode

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the remotenode type in the database.
	Label = "remote_node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldNodePublicKey holds the string denoting the node_public_key field in the database.
	FieldNodePublicKey = "node_public_key"
	// FieldManagementAddress holds the string denoting the management_address field in the database.
	FieldManagementAddress = "management_address"
	// FieldFrpBindPort holds the string denoting the frp_bind_port field in the database.
	FieldFrpBindPort = "frp_bind_port"
	// FieldHTTPVhostPort holds the string denoting the http_vhost_port field in the database.
	FieldHTTPVhostPort = "http_vhost_port"
	// FieldPortStart holds the string denoting the port_start field in the database.
	FieldPortStart = "port_start"
	// FieldPortEnd holds the string denoting the port_end field in the database.
	FieldPortEnd = "port_end"
	// FieldDesiredRevision holds the string denoting the desired_revision field in the database.
	FieldDesiredRevision = "desired_revision"
	// FieldDesiredHash holds the string denoting the desired_hash field in the database.
	FieldDesiredHash = "desired_hash"
	// FieldDesiredSnapshot holds the string denoting the desired_snapshot field in the database.
	FieldDesiredSnapshot = "desired_snapshot"
	// FieldActiveToken holds the string denoting the active_token field in the database.
	FieldActiveToken = "active_token"
	// FieldStagedToken holds the string denoting the staged_token field in the database.
	FieldStagedToken = "staged_token"
	// FieldStagedTokenRevision holds the string denoting the staged_token_revision field in the database.
	FieldStagedTokenRevision = "staged_token_revision"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// NodeFieldID holds the string denoting the ID field of the Node.
	NodeFieldID = "node_id"
	// Table holds the table name of the remotenode in the database.
	Table = "remote_nodes"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "remote_nodes"
	// NodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	NodeInverseTable = "nodes"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "node_id"
)

// Columns holds all SQL columns for remotenode fields.
var Columns = []string{
	FieldID,
	FieldNodeID,
	FieldNodePublicKey,
	FieldManagementAddress,
	FieldFrpBindPort,
	FieldHTTPVhostPort,
	FieldPortStart,
	FieldPortEnd,
	FieldDesiredRevision,
	FieldDesiredHash,
	FieldDesiredSnapshot,
	FieldActiveToken,
	FieldStagedToken,
	FieldStagedTokenRevision,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDesiredRevision holds the default value on creation for the "desired_revision" field.
	DefaultDesiredRevision int64
)

// OrderOption defines the ordering options for the RemoteNode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByNodePublicKey orders the results by the node_public_key field.
func ByNodePublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodePublicKey, opts...).ToFunc()
}

// ByManagementAddress orders the results by the management_address field.
func ByManagementAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagementAddress, opts...).ToFunc()
}

// ByFrpBindPort orders the results by the frp_bind_port field.
func ByFrpBindPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrpBindPort, opts...).ToFunc()
}

// ByHTTPVhostPort orders the results by the http_vhost_port field.
func ByHTTPVhostPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPVhostPort, opts...).ToFunc()
}

// ByPortStart orders the results by the port_start field.
func ByPortStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPortStart, opts...).ToFunc()
}

// ByPortEnd orders the results by the port_end field.
func ByPortEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPortEnd, opts...).ToFunc()
}

// ByDesiredRevision orders the results by the desired_revision field.
func ByDesiredRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesiredRevision, opts...).ToFunc()
}

// ByDesiredHash orders the results by the desired_hash field.
func ByDesiredHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesiredHash, opts...).ToFunc()
}

// ByDesiredSnapshot orders the results by the desired_snapshot field.
func ByDesiredSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesiredSnapshot, opts...).ToFunc()
}

// ByActiveToken orders the results by the active_token field.
func ByActiveToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveToken, opts...).ToFunc()
}

// ByStagedToken orders the results by the staged_token field.
func ByStagedToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStagedToken, opts...).ToFunc()
}

// ByStagedTokenRevision orders the results by the staged_token_revision field.
func ByStagedTokenRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStagedTokenRevision, opts...).ToFunc()
}

// ByNodeField orders the results by node field.
func ByNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeStep(), sql.OrderByField(field, opts...))
	}
}
func newNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodeInverseTable, NodeFieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, NodeTable, NodeColumn),
	)
}
