import { describe, expect, test } from 'bun:test'
import { parseFrpChecksums, renderFrpManifest } from '../../../../scripts/generate-frp-manifest'

const DIGEST = 'a'.repeat(64)

describe('FRP manifest generator', () => {
  test('parses the official checksum format and rejects duplicate assets', () => {
    expect(parseFrpChecksums(`${DIGEST}  first.tar.gz\n${'b'.repeat(64)}  second.zip\n`)).toEqual(new Map([
      ['first.tar.gz', DIGEST],
      ['second.zip', 'b'.repeat(64)],
    ]))
    expect(() => parseFrpChecksums(`${DIGEST}  repeated.zip\n${DIGEST}  repeated.zip`)).toThrow('Duplicate asset')
  })

  test('renders artifacts in a deterministic target order', () => {
    const artifact = {
      platform: 'linux' as const,
      architecture: 'x64' as const,
      archive: 'frp_test_linux_amd64.tar.gz',
      sha256: DIGEST,
      frpcSha256: DIGEST,
      frpsSha256: DIGEST,
    }
    const rendered = renderFrpManifest([
      artifact,
      { ...artifact, platform: 'darwin', architecture: 'arm64', archive: 'frp_test_darwin_arm64.tar.gz' },
    ])
    expect(rendered.indexOf('platform: \'darwin\'')).toBeLessThan(rendered.indexOf('platform: \'linux\''))
    expect(rendered).toStartWith('// Generated by `bun run generate:frp-manifest`. Do not edit manually.')
  })
})
