// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// AllocationsColumns holds the columns for the "allocations" table.
	AllocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "port", Type: field.TypeInt},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "owner_id", Type: field.TypeInt},
	}
	// AllocationsTable holds the schema information for the "allocations" table.
	AllocationsTable = &schema.Table{
		Name:       "allocations",
		Columns:    AllocationsColumns,
		PrimaryKey: []*schema.Column{AllocationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "allocations_accounts_allocations",
				Columns:    []*schema.Column{AllocationsColumns[3]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "allocation_owner_id_port",
				Unique:  true,
				Columns: []*schema.Column{AllocationsColumns[3], AllocationsColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					Where: "enabled = 1",
				},
			},
		},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "node_id", Type: field.TypeString, Unique: true},
		{Name: "controller_public", Type: field.TypeString, Nullable: true},
		{Name: "highest_revision", Type: field.TypeInt64, Default: 0},
		{Name: "phase", Type: field.TypeString, Default: "idle"},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		AllocationsTable,
		NodesTable,
	}
)

func init() {
	AllocationsTable.ForeignKeys[0].RefTable = AccountsTable
	AllocationsTable.Annotation = &entsql.Annotation{}
	AllocationsTable.Annotation.Checks = map[string]string{
		"port_range": "port BETWEEN 1 AND 65535",
	}
	NodesTable.Annotation = &entsql.Annotation{}
	NodesTable.Annotation.Checks = map[string]string{
		"revision_nonnegative": "highest_revision >= 0",
	}
}
