// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "internal_id", Type: field.TypeString},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"environment", "local"}},
		{Name: "username", Type: field.TypeString},
		{Name: "username_key", Type: field.TypeString, Unique: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeString},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "accounts_single_environment",
				Unique:  true,
				Columns: []*schema.Column{AccountsColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					Where: "kind = 'environment'",
				},
			},
		},
	}
	// MetaColumns holds the columns for the "meta" table.
	MetaColumns = []*schema.Column{
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
	}
	// MetaTable holds the schema information for the "meta" table.
	MetaTable = &schema.Table{
		Name:       "meta",
		Columns:    MetaColumns,
		PrimaryKey: []*schema.Column{MetaColumns[0]},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "node_id", Type: field.TypeString},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"local", "remote"}},
		{Name: "name", Type: field.TypeString},
		{Name: "lifecycle", Type: field.TypeEnum, Enums: []string{"active", "removing"}, Default: "active"},
		{Name: "advertised_frp_host", Type: field.TypeString, Nullable: true},
		{Name: "advertised_frp_port", Type: field.TypeInt, Nullable: true},
		{Name: "http_ingress_host", Type: field.TypeString, Nullable: true},
		{Name: "http_ingress_port", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeString},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "nodes_one_local",
				Unique:  true,
				Columns: []*schema.Column{NodesColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					Where: "kind = 'local'",
				},
			},
			{
				Name:    "nodes_frp_endpoint",
				Unique:  true,
				Columns: []*schema.Column{NodesColumns[4], NodesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					Where: "lifecycle = 'active' AND advertised_frp_host IS NOT NULL",
				},
			},
		},
	}
	// NodeManagementCandidatesColumns holds the columns for the "node_management_candidates" table.
	NodeManagementCandidatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "candidate_address", Type: field.TypeString},
		{Name: "failure_code", Type: field.TypeString, Default: ""},
		{Name: "node_id", Type: field.TypeString, Unique: true},
	}
	// NodeManagementCandidatesTable holds the schema information for the "node_management_candidates" table.
	NodeManagementCandidatesTable = &schema.Table{
		Name:       "node_management_candidates",
		Columns:    NodeManagementCandidatesColumns,
		PrimaryKey: []*schema.Column{NodeManagementCandidatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "node_management_candidates_nodes_management_candidate",
				Columns:    []*schema.Column{NodeManagementCandidatesColumns[3]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// NodeObservationsColumns holds the columns for the "node_observations" table.
	NodeObservationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status_json", Type: field.TypeString, Nullable: true},
		{Name: "status_observed_at", Type: field.TypeString, Nullable: true},
		{Name: "failure_code", Type: field.TypeString, Default: ""},
		{Name: "attempted_at", Type: field.TypeString},
		{Name: "node_id", Type: field.TypeString, Unique: true},
	}
	// NodeObservationsTable holds the schema information for the "node_observations" table.
	NodeObservationsTable = &schema.Table{
		Name:       "node_observations",
		Columns:    NodeObservationsColumns,
		PrimaryKey: []*schema.Column{NodeObservationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "node_observations_nodes_observation",
				Columns:    []*schema.Column{NodeObservationsColumns[5]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// NodePortPoolsColumns holds the columns for the "node_port_pools" table.
	NodePortPoolsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "port_start", Type: field.TypeInt},
		{Name: "port_end", Type: field.TypeInt},
		{Name: "node_id", Type: field.TypeString, Unique: true},
	}
	// NodePortPoolsTable holds the schema information for the "node_port_pools" table.
	NodePortPoolsTable = &schema.Table{
		Name:       "node_port_pools",
		Columns:    NodePortPoolsColumns,
		PrimaryKey: []*schema.Column{NodePortPoolsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "node_port_pools_nodes_port_pool",
				Columns:    []*schema.Column{NodePortPoolsColumns[3]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RemoteNodesColumns holds the columns for the "remote_nodes" table.
	RemoteNodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "node_public_key", Type: field.TypeString, Unique: true},
		{Name: "management_address", Type: field.TypeString, Unique: true},
		{Name: "frp_bind_port", Type: field.TypeInt},
		{Name: "http_vhost_port", Type: field.TypeInt},
		{Name: "port_start", Type: field.TypeInt},
		{Name: "port_end", Type: field.TypeInt},
		{Name: "desired_revision", Type: field.TypeInt64, Default: 0},
		{Name: "desired_hash", Type: field.TypeString, Nullable: true},
		{Name: "desired_snapshot", Type: field.TypeString, Nullable: true},
		{Name: "active_token", Type: field.TypeString},
		{Name: "staged_token", Type: field.TypeString, Nullable: true},
		{Name: "staged_token_revision", Type: field.TypeInt64, Nullable: true},
		{Name: "node_id", Type: field.TypeString, Unique: true},
	}
	// RemoteNodesTable holds the schema information for the "remote_nodes" table.
	RemoteNodesTable = &schema.Table{
		Name:       "remote_nodes",
		Columns:    RemoteNodesColumns,
		PrimaryKey: []*schema.Column{RemoteNodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "remote_nodes_nodes_remote_node",
				Columns:    []*schema.Column{RemoteNodesColumns[13]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ClientsColumns holds the columns for the "clients" table.
	ClientsColumns = []*schema.Column{
		{Name: "internal_id", Type: field.TypeString},
		{Name: "pending_since", Type: field.TypeString, Nullable: true},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "desired_revision", Type: field.TypeInt64, Default: 0},
		{Name: "last_applied_revision", Type: field.TypeInt64, Default: 0},
		{Name: "revocation_pending", Type: field.TypeBool, Default: false},
		{Name: "desired_restart_generation", Type: field.TypeInt64, Default: 0},
		{Name: "completed_restart_generation", Type: field.TypeInt64, Default: 0},
		{Name: "restart_error_generation", Type: field.TypeInt64, Nullable: true},
		{Name: "restart_error_code", Type: field.TypeString, Nullable: true},
		{Name: "restart_error_message", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeString},
		{Name: "rotated_at", Type: field.TypeString, Nullable: true},
		{Name: "owner_account_id", Type: field.TypeString},
		{Name: "node_id", Type: field.TypeString, Default: "local"},
		{Name: "pending_node_id", Type: field.TypeString, Nullable: true},
		{Name: "last_applied_node_id", Type: field.TypeString, Nullable: true},
	}
	// ClientsTable holds the schema information for the "clients" table.
	ClientsTable = &schema.Table{
		Name:       "clients",
		Columns:    ClientsColumns,
		PrimaryKey: []*schema.Column{ClientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "clients_accounts_clients",
				Columns:    []*schema.Column{ClientsColumns[14]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.Restrict,
			},
			{
				Symbol:     "clients_nodes_clients",
				Columns:    []*schema.Column{ClientsColumns[15]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.Restrict,
			},
			{
				Symbol:     "clients_nodes_pending_clients",
				Columns:    []*schema.Column{ClientsColumns[16]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.Restrict,
			},
			{
				Symbol:     "clients_nodes_applied_clients",
				Columns:    []*schema.Column{ClientsColumns[17]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "clients_by_owner",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[14], ClientsColumns[12], ClientsColumns[0]},
			},
		},
	}
	// TunnelsColumns holds the columns for the "tunnels" table.
	TunnelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "label", Type: field.TypeString, Default: ""},
		{Name: "protocol", Type: field.TypeEnum, Enums: []string{"http", "tcp", "udp"}},
		{Name: "custom_domains", Type: field.TypeString, Nullable: true},
		{Name: "location", Type: field.TypeString, Nullable: true},
		{Name: "server_port", Type: field.TypeInt, Nullable: true},
		{Name: "local_host", Type: field.TypeString},
		{Name: "local_port", Type: field.TypeInt},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "options_json", Type: field.TypeString, Default: "{}"},
		{Name: "created_at", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeString},
		{Name: "node_id", Type: field.TypeString, Default: "local"},
		{Name: "client_internal_id", Type: field.TypeString},
	}
	// TunnelsTable holds the schema information for the "tunnels" table.
	TunnelsTable = &schema.Table{
		Name:       "tunnels",
		Columns:    TunnelsColumns,
		PrimaryKey: []*schema.Column{TunnelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tunnels_nodes_tunnels",
				Columns:    []*schema.Column{TunnelsColumns[12]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.Restrict,
			},
			{
				Symbol:     "tunnels_clients_tunnels",
				Columns:    []*schema.Column{TunnelsColumns[13]},
				RefColumns: []*schema.Column{ClientsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tunnels_unique_transport_port",
				Unique:  true,
				Columns: []*schema.Column{TunnelsColumns[12], TunnelsColumns[2], TunnelsColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					Where: "protocol IN ('tcp', 'udp')",
				},
			},
			{
				Name:    "tunnels_by_client",
				Unique:  false,
				Columns: []*schema.Column{TunnelsColumns[13], TunnelsColumns[10], TunnelsColumns[0]},
			},
		},
	}
	// TunnelHTTPRoutesColumns holds the columns for the "tunnel_http_routes" table.
	TunnelHTTPRoutesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "hostname", Type: field.TypeString, Collation: "NOCASE"},
		{Name: "location", Type: field.TypeString},
		{Name: "tunnel_id", Type: field.TypeString},
	}
	// TunnelHTTPRoutesTable holds the schema information for the "tunnel_http_routes" table.
	TunnelHTTPRoutesTable = &schema.Table{
		Name:       "tunnel_http_routes",
		Columns:    TunnelHTTPRoutesColumns,
		PrimaryKey: []*schema.Column{TunnelHTTPRoutesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tunnel_http_routes_tunnels_routes",
				Columns:    []*schema.Column{TunnelHTTPRoutesColumns[3]},
				RefColumns: []*schema.Column{TunnelsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tunnel_http_routes_host_location",
				Unique:  true,
				Columns: []*schema.Column{TunnelHTTPRoutesColumns[1], TunnelHTTPRoutesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		MetaTable,
		NodesTable,
		NodeManagementCandidatesTable,
		NodeObservationsTable,
		NodePortPoolsTable,
		RemoteNodesTable,
		ClientsTable,
		TunnelsTable,
		TunnelHTTPRoutesTable,
	}
)

func init() {
	AccountsTable.Annotation = &entsql.Annotation{
		Table: "accounts",
	}
	AccountsTable.Annotation.Checks = map[string]string{
		"account_kind_role": "(kind = 'environment' AND role = 'admin' AND password_hash IS NULL) OR (kind = 'local' AND password_hash IS NOT NULL)",
	}
	MetaTable.Annotation = &entsql.Annotation{
		Table: "meta",
	}
	NodesTable.Annotation = &entsql.Annotation{
		Table: "nodes",
	}
	NodesTable.Annotation.Checks = map[string]string{
		"node_frp_pair":     "(advertised_frp_host IS NULL) = (advertised_frp_port IS NULL)",
		"node_frp_port":     "advertised_frp_port BETWEEN 1 AND 65535",
		"node_http_pair":    "(http_ingress_host IS NULL) = (http_ingress_port IS NULL)",
		"node_http_port":    "http_ingress_port BETWEEN 1 AND 65535",
		"node_local_active": "node_id <> 'local' OR lifecycle = 'active'",
		"node_local_kind":   "(node_id = 'local') = (kind = 'local')",
	}
	NodeManagementCandidatesTable.ForeignKeys[0].RefTable = NodesTable
	NodeManagementCandidatesTable.Annotation = &entsql.Annotation{
		Table: "node_management_candidates",
	}
	NodeObservationsTable.ForeignKeys[0].RefTable = NodesTable
	NodeObservationsTable.Annotation = &entsql.Annotation{
		Table: "node_observations",
	}
	NodePortPoolsTable.ForeignKeys[0].RefTable = NodesTable
	NodePortPoolsTable.Annotation = &entsql.Annotation{
		Table: "node_port_pools",
	}
	NodePortPoolsTable.Annotation.Checks = map[string]string{
		"pool_port_end_range":   "port_end BETWEEN port_start AND 65535",
		"pool_port_start_range": "port_start BETWEEN 1 AND 65535",
	}
	RemoteNodesTable.ForeignKeys[0].RefTable = NodesTable
	RemoteNodesTable.Annotation = &entsql.Annotation{
		Table: "remote_nodes",
	}
	RemoteNodesTable.Annotation.Checks = map[string]string{
		"frp_bind_port_range":         "frp_bind_port BETWEEN 1 AND 65535",
		"http_vhost_port_range":       "http_vhost_port BETWEEN 1 AND 65535",
		"remote_port_end_range":       "port_end BETWEEN port_start AND 65535",
		"remote_port_start_range":     "port_start BETWEEN 1 AND 65535",
		"remote_revision_nonnegative": "desired_revision >= 0",
		"staged_revision_nonnegative": "staged_token_revision IS NULL OR staged_token_revision >= 0",
	}
	ClientsTable.ForeignKeys[0].RefTable = AccountsTable
	ClientsTable.ForeignKeys[1].RefTable = NodesTable
	ClientsTable.ForeignKeys[2].RefTable = NodesTable
	ClientsTable.ForeignKeys[3].RefTable = NodesTable
	ClientsTable.Annotation = &entsql.Annotation{
		Table: "clients",
	}
	ClientsTable.Annotation.Checks = map[string]string{
		"client_applied_revision":     "last_applied_revision >= 0",
		"client_completed_generation": "completed_restart_generation >= 0",
		"client_desired_revision":     "desired_revision >= 0",
		"client_error_generation":     "restart_error_generation IS NULL OR restart_error_generation >= 0",
		"client_remark_length":        "length(remark) <= 100",
		"client_restart_generation":   "desired_restart_generation >= 0",
	}
	TunnelsTable.ForeignKeys[0].RefTable = NodesTable
	TunnelsTable.ForeignKeys[1].RefTable = ClientsTable
	TunnelsTable.Annotation = &entsql.Annotation{
		Table: "tunnels",
	}
	TunnelsTable.Annotation.Checks = map[string]string{
		"tunnel_label_length":      "length(label) <= 100",
		"tunnel_local_port_range":  "local_port BETWEEN 1 AND 65535",
		"tunnel_options_json":      "json_valid(options_json)",
		"tunnel_protocol_shape":    "(protocol = 'http' AND custom_domains IS NOT NULL AND server_port IS NULL) OR (protocol IN ('tcp', 'udp') AND custom_domains IS NULL AND location IS NULL AND server_port IS NOT NULL)",
		"tunnel_server_port_range": "server_port IS NULL OR server_port BETWEEN 1 AND 65535",
	}
	TunnelHTTPRoutesTable.ForeignKeys[0].RefTable = TunnelsTable
	TunnelHTTPRoutesTable.Annotation = &entsql.Annotation{
		Table: "tunnel_http_routes",
	}
	TunnelHTTPRoutesTable.Annotation.Checks = map[string]string{
		"route_hostname_lowercase": "hostname COLLATE BINARY = lower(hostname)",
	}
}
