// Code generated by ent, DO NOT EDIT.

package serverclient

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hackycy/hackycy-cli/ent/server/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldID, id))
}

// OwnerAccountID applies equality check predicate on the "owner_account_id" field. It's identical to OwnerAccountIDEQ.
func OwnerAccountID(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldOwnerAccountID, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldNodeID, v))
}

// PendingNodeID applies equality check predicate on the "pending_node_id" field. It's identical to PendingNodeIDEQ.
func PendingNodeID(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldPendingNodeID, v))
}

// PendingSince applies equality check predicate on the "pending_since" field. It's identical to PendingSinceEQ.
func PendingSince(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldPendingSince, v))
}

// LastAppliedNodeID applies equality check predicate on the "last_applied_node_id" field. It's identical to LastAppliedNodeIDEQ.
func LastAppliedNodeID(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldLastAppliedNodeID, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRemark, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldToken, v))
}

// DesiredRevision applies equality check predicate on the "desired_revision" field. It's identical to DesiredRevisionEQ.
func DesiredRevision(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldDesiredRevision, v))
}

// LastAppliedRevision applies equality check predicate on the "last_applied_revision" field. It's identical to LastAppliedRevisionEQ.
func LastAppliedRevision(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldLastAppliedRevision, v))
}

// RevocationPending applies equality check predicate on the "revocation_pending" field. It's identical to RevocationPendingEQ.
func RevocationPending(v bool) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRevocationPending, v))
}

// DesiredRestartGeneration applies equality check predicate on the "desired_restart_generation" field. It's identical to DesiredRestartGenerationEQ.
func DesiredRestartGeneration(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldDesiredRestartGeneration, v))
}

// CompletedRestartGeneration applies equality check predicate on the "completed_restart_generation" field. It's identical to CompletedRestartGenerationEQ.
func CompletedRestartGeneration(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldCompletedRestartGeneration, v))
}

// RestartErrorGeneration applies equality check predicate on the "restart_error_generation" field. It's identical to RestartErrorGenerationEQ.
func RestartErrorGeneration(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRestartErrorGeneration, v))
}

// RestartErrorCode applies equality check predicate on the "restart_error_code" field. It's identical to RestartErrorCodeEQ.
func RestartErrorCode(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRestartErrorCode, v))
}

// RestartErrorMessage applies equality check predicate on the "restart_error_message" field. It's identical to RestartErrorMessageEQ.
func RestartErrorMessage(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRestartErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldCreatedAt, v))
}

// RotatedAt applies equality check predicate on the "rotated_at" field. It's identical to RotatedAtEQ.
func RotatedAt(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRotatedAt, v))
}

// OwnerAccountIDEQ applies the EQ predicate on the "owner_account_id" field.
func OwnerAccountIDEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDNEQ applies the NEQ predicate on the "owner_account_id" field.
func OwnerAccountIDNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDIn applies the In predicate on the "owner_account_id" field.
func OwnerAccountIDIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldOwnerAccountID, vs...))
}

// OwnerAccountIDNotIn applies the NotIn predicate on the "owner_account_id" field.
func OwnerAccountIDNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldOwnerAccountID, vs...))
}

// OwnerAccountIDGT applies the GT predicate on the "owner_account_id" field.
func OwnerAccountIDGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldOwnerAccountID, v))
}

// OwnerAccountIDGTE applies the GTE predicate on the "owner_account_id" field.
func OwnerAccountIDGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldOwnerAccountID, v))
}

// OwnerAccountIDLT applies the LT predicate on the "owner_account_id" field.
func OwnerAccountIDLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldOwnerAccountID, v))
}

// OwnerAccountIDLTE applies the LTE predicate on the "owner_account_id" field.
func OwnerAccountIDLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldOwnerAccountID, v))
}

// OwnerAccountIDContains applies the Contains predicate on the "owner_account_id" field.
func OwnerAccountIDContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldOwnerAccountID, v))
}

// OwnerAccountIDHasPrefix applies the HasPrefix predicate on the "owner_account_id" field.
func OwnerAccountIDHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldOwnerAccountID, v))
}

// OwnerAccountIDHasSuffix applies the HasSuffix predicate on the "owner_account_id" field.
func OwnerAccountIDHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldOwnerAccountID, v))
}

// OwnerAccountIDEqualFold applies the EqualFold predicate on the "owner_account_id" field.
func OwnerAccountIDEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldOwnerAccountID, v))
}

// OwnerAccountIDContainsFold applies the ContainsFold predicate on the "owner_account_id" field.
func OwnerAccountIDContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldOwnerAccountID, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldNodeID, v))
}

// PendingNodeIDEQ applies the EQ predicate on the "pending_node_id" field.
func PendingNodeIDEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldPendingNodeID, v))
}

// PendingNodeIDNEQ applies the NEQ predicate on the "pending_node_id" field.
func PendingNodeIDNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldPendingNodeID, v))
}

// PendingNodeIDIn applies the In predicate on the "pending_node_id" field.
func PendingNodeIDIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldPendingNodeID, vs...))
}

// PendingNodeIDNotIn applies the NotIn predicate on the "pending_node_id" field.
func PendingNodeIDNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldPendingNodeID, vs...))
}

// PendingNodeIDGT applies the GT predicate on the "pending_node_id" field.
func PendingNodeIDGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldPendingNodeID, v))
}

// PendingNodeIDGTE applies the GTE predicate on the "pending_node_id" field.
func PendingNodeIDGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldPendingNodeID, v))
}

// PendingNodeIDLT applies the LT predicate on the "pending_node_id" field.
func PendingNodeIDLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldPendingNodeID, v))
}

// PendingNodeIDLTE applies the LTE predicate on the "pending_node_id" field.
func PendingNodeIDLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldPendingNodeID, v))
}

// PendingNodeIDContains applies the Contains predicate on the "pending_node_id" field.
func PendingNodeIDContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldPendingNodeID, v))
}

// PendingNodeIDHasPrefix applies the HasPrefix predicate on the "pending_node_id" field.
func PendingNodeIDHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldPendingNodeID, v))
}

// PendingNodeIDHasSuffix applies the HasSuffix predicate on the "pending_node_id" field.
func PendingNodeIDHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldPendingNodeID, v))
}

// PendingNodeIDIsNil applies the IsNil predicate on the "pending_node_id" field.
func PendingNodeIDIsNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIsNull(FieldPendingNodeID))
}

// PendingNodeIDNotNil applies the NotNil predicate on the "pending_node_id" field.
func PendingNodeIDNotNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotNull(FieldPendingNodeID))
}

// PendingNodeIDEqualFold applies the EqualFold predicate on the "pending_node_id" field.
func PendingNodeIDEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldPendingNodeID, v))
}

// PendingNodeIDContainsFold applies the ContainsFold predicate on the "pending_node_id" field.
func PendingNodeIDContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldPendingNodeID, v))
}

// PendingSinceEQ applies the EQ predicate on the "pending_since" field.
func PendingSinceEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldPendingSince, v))
}

// PendingSinceNEQ applies the NEQ predicate on the "pending_since" field.
func PendingSinceNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldPendingSince, v))
}

// PendingSinceIn applies the In predicate on the "pending_since" field.
func PendingSinceIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldPendingSince, vs...))
}

// PendingSinceNotIn applies the NotIn predicate on the "pending_since" field.
func PendingSinceNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldPendingSince, vs...))
}

// PendingSinceGT applies the GT predicate on the "pending_since" field.
func PendingSinceGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldPendingSince, v))
}

// PendingSinceGTE applies the GTE predicate on the "pending_since" field.
func PendingSinceGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldPendingSince, v))
}

// PendingSinceLT applies the LT predicate on the "pending_since" field.
func PendingSinceLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldPendingSince, v))
}

// PendingSinceLTE applies the LTE predicate on the "pending_since" field.
func PendingSinceLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldPendingSince, v))
}

// PendingSinceContains applies the Contains predicate on the "pending_since" field.
func PendingSinceContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldPendingSince, v))
}

// PendingSinceHasPrefix applies the HasPrefix predicate on the "pending_since" field.
func PendingSinceHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldPendingSince, v))
}

// PendingSinceHasSuffix applies the HasSuffix predicate on the "pending_since" field.
func PendingSinceHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldPendingSince, v))
}

// PendingSinceIsNil applies the IsNil predicate on the "pending_since" field.
func PendingSinceIsNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIsNull(FieldPendingSince))
}

// PendingSinceNotNil applies the NotNil predicate on the "pending_since" field.
func PendingSinceNotNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotNull(FieldPendingSince))
}

// PendingSinceEqualFold applies the EqualFold predicate on the "pending_since" field.
func PendingSinceEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldPendingSince, v))
}

// PendingSinceContainsFold applies the ContainsFold predicate on the "pending_since" field.
func PendingSinceContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldPendingSince, v))
}

// LastAppliedNodeIDEQ applies the EQ predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDNEQ applies the NEQ predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDIn applies the In predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldLastAppliedNodeID, vs...))
}

// LastAppliedNodeIDNotIn applies the NotIn predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldLastAppliedNodeID, vs...))
}

// LastAppliedNodeIDGT applies the GT predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDGTE applies the GTE predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDLT applies the LT predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDLTE applies the LTE predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDContains applies the Contains predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDHasPrefix applies the HasPrefix predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDHasSuffix applies the HasSuffix predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDIsNil applies the IsNil predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDIsNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIsNull(FieldLastAppliedNodeID))
}

// LastAppliedNodeIDNotNil applies the NotNil predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDNotNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotNull(FieldLastAppliedNodeID))
}

// LastAppliedNodeIDEqualFold applies the EqualFold predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldLastAppliedNodeID, v))
}

// LastAppliedNodeIDContainsFold applies the ContainsFold predicate on the "last_applied_node_id" field.
func LastAppliedNodeIDContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldLastAppliedNodeID, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldRemark, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldToken, v))
}

// DesiredRevisionEQ applies the EQ predicate on the "desired_revision" field.
func DesiredRevisionEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldDesiredRevision, v))
}

// DesiredRevisionNEQ applies the NEQ predicate on the "desired_revision" field.
func DesiredRevisionNEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldDesiredRevision, v))
}

// DesiredRevisionIn applies the In predicate on the "desired_revision" field.
func DesiredRevisionIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldDesiredRevision, vs...))
}

// DesiredRevisionNotIn applies the NotIn predicate on the "desired_revision" field.
func DesiredRevisionNotIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldDesiredRevision, vs...))
}

// DesiredRevisionGT applies the GT predicate on the "desired_revision" field.
func DesiredRevisionGT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldDesiredRevision, v))
}

// DesiredRevisionGTE applies the GTE predicate on the "desired_revision" field.
func DesiredRevisionGTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldDesiredRevision, v))
}

// DesiredRevisionLT applies the LT predicate on the "desired_revision" field.
func DesiredRevisionLT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldDesiredRevision, v))
}

// DesiredRevisionLTE applies the LTE predicate on the "desired_revision" field.
func DesiredRevisionLTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldDesiredRevision, v))
}

// LastAppliedRevisionEQ applies the EQ predicate on the "last_applied_revision" field.
func LastAppliedRevisionEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldLastAppliedRevision, v))
}

// LastAppliedRevisionNEQ applies the NEQ predicate on the "last_applied_revision" field.
func LastAppliedRevisionNEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldLastAppliedRevision, v))
}

// LastAppliedRevisionIn applies the In predicate on the "last_applied_revision" field.
func LastAppliedRevisionIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldLastAppliedRevision, vs...))
}

// LastAppliedRevisionNotIn applies the NotIn predicate on the "last_applied_revision" field.
func LastAppliedRevisionNotIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldLastAppliedRevision, vs...))
}

// LastAppliedRevisionGT applies the GT predicate on the "last_applied_revision" field.
func LastAppliedRevisionGT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldLastAppliedRevision, v))
}

// LastAppliedRevisionGTE applies the GTE predicate on the "last_applied_revision" field.
func LastAppliedRevisionGTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldLastAppliedRevision, v))
}

// LastAppliedRevisionLT applies the LT predicate on the "last_applied_revision" field.
func LastAppliedRevisionLT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldLastAppliedRevision, v))
}

// LastAppliedRevisionLTE applies the LTE predicate on the "last_applied_revision" field.
func LastAppliedRevisionLTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldLastAppliedRevision, v))
}

// RevocationPendingEQ applies the EQ predicate on the "revocation_pending" field.
func RevocationPendingEQ(v bool) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRevocationPending, v))
}

// RevocationPendingNEQ applies the NEQ predicate on the "revocation_pending" field.
func RevocationPendingNEQ(v bool) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldRevocationPending, v))
}

// DesiredRestartGenerationEQ applies the EQ predicate on the "desired_restart_generation" field.
func DesiredRestartGenerationEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldDesiredRestartGeneration, v))
}

// DesiredRestartGenerationNEQ applies the NEQ predicate on the "desired_restart_generation" field.
func DesiredRestartGenerationNEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldDesiredRestartGeneration, v))
}

// DesiredRestartGenerationIn applies the In predicate on the "desired_restart_generation" field.
func DesiredRestartGenerationIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldDesiredRestartGeneration, vs...))
}

// DesiredRestartGenerationNotIn applies the NotIn predicate on the "desired_restart_generation" field.
func DesiredRestartGenerationNotIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldDesiredRestartGeneration, vs...))
}

// DesiredRestartGenerationGT applies the GT predicate on the "desired_restart_generation" field.
func DesiredRestartGenerationGT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldDesiredRestartGeneration, v))
}

// DesiredRestartGenerationGTE applies the GTE predicate on the "desired_restart_generation" field.
func DesiredRestartGenerationGTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldDesiredRestartGeneration, v))
}

// DesiredRestartGenerationLT applies the LT predicate on the "desired_restart_generation" field.
func DesiredRestartGenerationLT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldDesiredRestartGeneration, v))
}

// DesiredRestartGenerationLTE applies the LTE predicate on the "desired_restart_generation" field.
func DesiredRestartGenerationLTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldDesiredRestartGeneration, v))
}

// CompletedRestartGenerationEQ applies the EQ predicate on the "completed_restart_generation" field.
func CompletedRestartGenerationEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldCompletedRestartGeneration, v))
}

// CompletedRestartGenerationNEQ applies the NEQ predicate on the "completed_restart_generation" field.
func CompletedRestartGenerationNEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldCompletedRestartGeneration, v))
}

// CompletedRestartGenerationIn applies the In predicate on the "completed_restart_generation" field.
func CompletedRestartGenerationIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldCompletedRestartGeneration, vs...))
}

// CompletedRestartGenerationNotIn applies the NotIn predicate on the "completed_restart_generation" field.
func CompletedRestartGenerationNotIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldCompletedRestartGeneration, vs...))
}

// CompletedRestartGenerationGT applies the GT predicate on the "completed_restart_generation" field.
func CompletedRestartGenerationGT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldCompletedRestartGeneration, v))
}

// CompletedRestartGenerationGTE applies the GTE predicate on the "completed_restart_generation" field.
func CompletedRestartGenerationGTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldCompletedRestartGeneration, v))
}

// CompletedRestartGenerationLT applies the LT predicate on the "completed_restart_generation" field.
func CompletedRestartGenerationLT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldCompletedRestartGeneration, v))
}

// CompletedRestartGenerationLTE applies the LTE predicate on the "completed_restart_generation" field.
func CompletedRestartGenerationLTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldCompletedRestartGeneration, v))
}

// RestartErrorGenerationEQ applies the EQ predicate on the "restart_error_generation" field.
func RestartErrorGenerationEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRestartErrorGeneration, v))
}

// RestartErrorGenerationNEQ applies the NEQ predicate on the "restart_error_generation" field.
func RestartErrorGenerationNEQ(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldRestartErrorGeneration, v))
}

// RestartErrorGenerationIn applies the In predicate on the "restart_error_generation" field.
func RestartErrorGenerationIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldRestartErrorGeneration, vs...))
}

// RestartErrorGenerationNotIn applies the NotIn predicate on the "restart_error_generation" field.
func RestartErrorGenerationNotIn(vs ...int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldRestartErrorGeneration, vs...))
}

// RestartErrorGenerationGT applies the GT predicate on the "restart_error_generation" field.
func RestartErrorGenerationGT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldRestartErrorGeneration, v))
}

// RestartErrorGenerationGTE applies the GTE predicate on the "restart_error_generation" field.
func RestartErrorGenerationGTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldRestartErrorGeneration, v))
}

// RestartErrorGenerationLT applies the LT predicate on the "restart_error_generation" field.
func RestartErrorGenerationLT(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldRestartErrorGeneration, v))
}

// RestartErrorGenerationLTE applies the LTE predicate on the "restart_error_generation" field.
func RestartErrorGenerationLTE(v int64) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldRestartErrorGeneration, v))
}

// RestartErrorGenerationIsNil applies the IsNil predicate on the "restart_error_generation" field.
func RestartErrorGenerationIsNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIsNull(FieldRestartErrorGeneration))
}

// RestartErrorGenerationNotNil applies the NotNil predicate on the "restart_error_generation" field.
func RestartErrorGenerationNotNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotNull(FieldRestartErrorGeneration))
}

// RestartErrorCodeEQ applies the EQ predicate on the "restart_error_code" field.
func RestartErrorCodeEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRestartErrorCode, v))
}

// RestartErrorCodeNEQ applies the NEQ predicate on the "restart_error_code" field.
func RestartErrorCodeNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldRestartErrorCode, v))
}

// RestartErrorCodeIn applies the In predicate on the "restart_error_code" field.
func RestartErrorCodeIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldRestartErrorCode, vs...))
}

// RestartErrorCodeNotIn applies the NotIn predicate on the "restart_error_code" field.
func RestartErrorCodeNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldRestartErrorCode, vs...))
}

// RestartErrorCodeGT applies the GT predicate on the "restart_error_code" field.
func RestartErrorCodeGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldRestartErrorCode, v))
}

// RestartErrorCodeGTE applies the GTE predicate on the "restart_error_code" field.
func RestartErrorCodeGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldRestartErrorCode, v))
}

// RestartErrorCodeLT applies the LT predicate on the "restart_error_code" field.
func RestartErrorCodeLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldRestartErrorCode, v))
}

// RestartErrorCodeLTE applies the LTE predicate on the "restart_error_code" field.
func RestartErrorCodeLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldRestartErrorCode, v))
}

// RestartErrorCodeContains applies the Contains predicate on the "restart_error_code" field.
func RestartErrorCodeContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldRestartErrorCode, v))
}

// RestartErrorCodeHasPrefix applies the HasPrefix predicate on the "restart_error_code" field.
func RestartErrorCodeHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldRestartErrorCode, v))
}

// RestartErrorCodeHasSuffix applies the HasSuffix predicate on the "restart_error_code" field.
func RestartErrorCodeHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldRestartErrorCode, v))
}

// RestartErrorCodeIsNil applies the IsNil predicate on the "restart_error_code" field.
func RestartErrorCodeIsNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIsNull(FieldRestartErrorCode))
}

// RestartErrorCodeNotNil applies the NotNil predicate on the "restart_error_code" field.
func RestartErrorCodeNotNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotNull(FieldRestartErrorCode))
}

// RestartErrorCodeEqualFold applies the EqualFold predicate on the "restart_error_code" field.
func RestartErrorCodeEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldRestartErrorCode, v))
}

// RestartErrorCodeContainsFold applies the ContainsFold predicate on the "restart_error_code" field.
func RestartErrorCodeContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldRestartErrorCode, v))
}

// RestartErrorMessageEQ applies the EQ predicate on the "restart_error_message" field.
func RestartErrorMessageEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRestartErrorMessage, v))
}

// RestartErrorMessageNEQ applies the NEQ predicate on the "restart_error_message" field.
func RestartErrorMessageNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldRestartErrorMessage, v))
}

// RestartErrorMessageIn applies the In predicate on the "restart_error_message" field.
func RestartErrorMessageIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldRestartErrorMessage, vs...))
}

// RestartErrorMessageNotIn applies the NotIn predicate on the "restart_error_message" field.
func RestartErrorMessageNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldRestartErrorMessage, vs...))
}

// RestartErrorMessageGT applies the GT predicate on the "restart_error_message" field.
func RestartErrorMessageGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldRestartErrorMessage, v))
}

// RestartErrorMessageGTE applies the GTE predicate on the "restart_error_message" field.
func RestartErrorMessageGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldRestartErrorMessage, v))
}

// RestartErrorMessageLT applies the LT predicate on the "restart_error_message" field.
func RestartErrorMessageLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldRestartErrorMessage, v))
}

// RestartErrorMessageLTE applies the LTE predicate on the "restart_error_message" field.
func RestartErrorMessageLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldRestartErrorMessage, v))
}

// RestartErrorMessageContains applies the Contains predicate on the "restart_error_message" field.
func RestartErrorMessageContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldRestartErrorMessage, v))
}

// RestartErrorMessageHasPrefix applies the HasPrefix predicate on the "restart_error_message" field.
func RestartErrorMessageHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldRestartErrorMessage, v))
}

// RestartErrorMessageHasSuffix applies the HasSuffix predicate on the "restart_error_message" field.
func RestartErrorMessageHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldRestartErrorMessage, v))
}

// RestartErrorMessageIsNil applies the IsNil predicate on the "restart_error_message" field.
func RestartErrorMessageIsNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIsNull(FieldRestartErrorMessage))
}

// RestartErrorMessageNotNil applies the NotNil predicate on the "restart_error_message" field.
func RestartErrorMessageNotNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotNull(FieldRestartErrorMessage))
}

// RestartErrorMessageEqualFold applies the EqualFold predicate on the "restart_error_message" field.
func RestartErrorMessageEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldRestartErrorMessage, v))
}

// RestartErrorMessageContainsFold applies the ContainsFold predicate on the "restart_error_message" field.
func RestartErrorMessageContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldRestartErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldCreatedAt, v))
}

// RotatedAtEQ applies the EQ predicate on the "rotated_at" field.
func RotatedAtEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEQ(FieldRotatedAt, v))
}

// RotatedAtNEQ applies the NEQ predicate on the "rotated_at" field.
func RotatedAtNEQ(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNEQ(FieldRotatedAt, v))
}

// RotatedAtIn applies the In predicate on the "rotated_at" field.
func RotatedAtIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIn(FieldRotatedAt, vs...))
}

// RotatedAtNotIn applies the NotIn predicate on the "rotated_at" field.
func RotatedAtNotIn(vs ...string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotIn(FieldRotatedAt, vs...))
}

// RotatedAtGT applies the GT predicate on the "rotated_at" field.
func RotatedAtGT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGT(FieldRotatedAt, v))
}

// RotatedAtGTE applies the GTE predicate on the "rotated_at" field.
func RotatedAtGTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldGTE(FieldRotatedAt, v))
}

// RotatedAtLT applies the LT predicate on the "rotated_at" field.
func RotatedAtLT(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLT(FieldRotatedAt, v))
}

// RotatedAtLTE applies the LTE predicate on the "rotated_at" field.
func RotatedAtLTE(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldLTE(FieldRotatedAt, v))
}

// RotatedAtContains applies the Contains predicate on the "rotated_at" field.
func RotatedAtContains(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContains(FieldRotatedAt, v))
}

// RotatedAtHasPrefix applies the HasPrefix predicate on the "rotated_at" field.
func RotatedAtHasPrefix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasPrefix(FieldRotatedAt, v))
}

// RotatedAtHasSuffix applies the HasSuffix predicate on the "rotated_at" field.
func RotatedAtHasSuffix(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldHasSuffix(FieldRotatedAt, v))
}

// RotatedAtIsNil applies the IsNil predicate on the "rotated_at" field.
func RotatedAtIsNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldIsNull(FieldRotatedAt))
}

// RotatedAtNotNil applies the NotNil predicate on the "rotated_at" field.
func RotatedAtNotNil() predicate.ServerClient {
	return predicate.ServerClient(sql.FieldNotNull(FieldRotatedAt))
}

// RotatedAtEqualFold applies the EqualFold predicate on the "rotated_at" field.
func RotatedAtEqualFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldEqualFold(FieldRotatedAt, v))
}

// RotatedAtContainsFold applies the ContainsFold predicate on the "rotated_at" field.
func RotatedAtContainsFold(v string) predicate.ServerClient {
	return predicate.ServerClient(sql.FieldContainsFold(FieldRotatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Account) predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNode applies the HasEdge predicate on the "node" edge.
func HasNode() predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeWith applies the HasEdge predicate on the "node" edge with a given conditions (other predicates).
func HasNodeWith(preds ...predicate.Node) predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := newNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPendingNode applies the HasEdge predicate on the "pending_node" edge.
func HasPendingNode() predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PendingNodeTable, PendingNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPendingNodeWith applies the HasEdge predicate on the "pending_node" edge with a given conditions (other predicates).
func HasPendingNodeWith(preds ...predicate.Node) predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := newPendingNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLastAppliedNode applies the HasEdge predicate on the "last_applied_node" edge.
func HasLastAppliedNode() predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LastAppliedNodeTable, LastAppliedNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLastAppliedNodeWith applies the HasEdge predicate on the "last_applied_node" edge with a given conditions (other predicates).
func HasLastAppliedNodeWith(preds ...predicate.Node) predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := newLastAppliedNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTunnels applies the HasEdge predicate on the "tunnels" edge.
func HasTunnels() predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TunnelsTable, TunnelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTunnelsWith applies the HasEdge predicate on the "tunnels" edge with a given conditions (other predicates).
func HasTunnelsWith(preds ...predicate.Tunnel) predicate.ServerClient {
	return predicate.ServerClient(func(s *sql.Selector) {
		step := newTunnelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServerClient) predicate.ServerClient {
	return predicate.ServerClient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServerClient) predicate.ServerClient {
	return predicate.ServerClient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServerClient) predicate.ServerClient {
	return predicate.ServerClient(sql.NotPredicates(p))
}
