// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/hackycy/hackycy-cli/ent/node"
)

// The ControllerBindingFunc type is an adapter to allow the use of ordinary
// function as ControllerBinding mutator.
type ControllerBindingFunc func(context.Context, *node.ControllerBindingMutation) (node.Value, error)

// Mutate calls f(ctx, m).
func (f ControllerBindingFunc) Mutate(ctx context.Context, m node.Mutation) (node.Value, error) {
	if mv, ok := m.(*node.ControllerBindingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *node.ControllerBindingMutation", m)
}

// The IdentityFunc type is an adapter to allow the use of ordinary
// function as Identity mutator.
type IdentityFunc func(context.Context, *node.IdentityMutation) (node.Value, error)

// Mutate calls f(ctx, m).
func (f IdentityFunc) Mutate(ctx context.Context, m node.Mutation) (node.Value, error) {
	if mv, ok := m.(*node.IdentityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *node.IdentityMutation", m)
}

// The RuntimeStateFunc type is an adapter to allow the use of ordinary
// function as RuntimeState mutator.
type RuntimeStateFunc func(context.Context, *node.RuntimeStateMutation) (node.Value, error)

// Mutate calls f(ctx, m).
func (f RuntimeStateFunc) Mutate(ctx context.Context, m node.Mutation) (node.Value, error) {
	if mv, ok := m.(*node.RuntimeStateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *node.RuntimeStateMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, node.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m node.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m node.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m node.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op node.Op) Condition {
	return func(_ context.Context, m node.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m node.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m node.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m node.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk node.Hook, cond Condition) node.Hook {
	return func(next node.Mutator) node.Mutator {
		return node.MutateFunc(func(ctx context.Context, m node.Mutation) (node.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, node.Delete|node.Create)
func On(hk node.Hook, op node.Op) node.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, node.Update|node.UpdateOne)
func Unless(hk node.Hook, op node.Op) node.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) node.Hook {
	return func(node.Mutator) node.Mutator {
		return node.MutateFunc(func(context.Context, node.Mutation) (node.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []node.Hook {
//		return []node.Hook{
//			Reject(node.Delete|node.Update),
//		}
//	}
func Reject(op node.Op) node.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []node.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...node.Hook) Chain {
	return Chain{append([]node.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() node.Hook {
	return func(mutator node.Mutator) node.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...node.Hook) Chain {
	newHooks := make([]node.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
