// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/hackycy/hackycy-cli/ent/server"
)

// The AccountFunc type is an adapter to allow the use of ordinary
// function as Account mutator.
type AccountFunc func(context.Context, *server.AccountMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f AccountFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.AccountMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.AccountMutation", m)
}

// The MetaFunc type is an adapter to allow the use of ordinary
// function as Meta mutator.
type MetaFunc func(context.Context, *server.MetaMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f MetaFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.MetaMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.MetaMutation", m)
}

// The NodeFunc type is an adapter to allow the use of ordinary
// function as Node mutator.
type NodeFunc func(context.Context, *server.NodeMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f NodeFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.NodeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.NodeMutation", m)
}

// The NodeManagementCandidateFunc type is an adapter to allow the use of ordinary
// function as NodeManagementCandidate mutator.
type NodeManagementCandidateFunc func(context.Context, *server.NodeManagementCandidateMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f NodeManagementCandidateFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.NodeManagementCandidateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.NodeManagementCandidateMutation", m)
}

// The NodeObservationFunc type is an adapter to allow the use of ordinary
// function as NodeObservation mutator.
type NodeObservationFunc func(context.Context, *server.NodeObservationMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f NodeObservationFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.NodeObservationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.NodeObservationMutation", m)
}

// The NodePortPoolFunc type is an adapter to allow the use of ordinary
// function as NodePortPool mutator.
type NodePortPoolFunc func(context.Context, *server.NodePortPoolMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f NodePortPoolFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.NodePortPoolMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.NodePortPoolMutation", m)
}

// The RemoteNodeFunc type is an adapter to allow the use of ordinary
// function as RemoteNode mutator.
type RemoteNodeFunc func(context.Context, *server.RemoteNodeMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f RemoteNodeFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.RemoteNodeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.RemoteNodeMutation", m)
}

// The ServerClientFunc type is an adapter to allow the use of ordinary
// function as ServerClient mutator.
type ServerClientFunc func(context.Context, *server.ServerClientMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f ServerClientFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.ServerClientMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.ServerClientMutation", m)
}

// The TunnelFunc type is an adapter to allow the use of ordinary
// function as Tunnel mutator.
type TunnelFunc func(context.Context, *server.TunnelMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f TunnelFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.TunnelMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.TunnelMutation", m)
}

// The TunnelHTTPRouteFunc type is an adapter to allow the use of ordinary
// function as TunnelHTTPRoute mutator.
type TunnelHTTPRouteFunc func(context.Context, *server.TunnelHTTPRouteMutation) (server.Value, error)

// Mutate calls f(ctx, m).
func (f TunnelHTTPRouteFunc) Mutate(ctx context.Context, m server.Mutation) (server.Value, error) {
	if mv, ok := m.(*server.TunnelHTTPRouteMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *server.TunnelHTTPRouteMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, server.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m server.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m server.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m server.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op server.Op) Condition {
	return func(_ context.Context, m server.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m server.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m server.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m server.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk server.Hook, cond Condition) server.Hook {
	return func(next server.Mutator) server.Mutator {
		return server.MutateFunc(func(ctx context.Context, m server.Mutation) (server.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, server.Delete|server.Create)
func On(hk server.Hook, op server.Op) server.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, server.Update|server.UpdateOne)
func Unless(hk server.Hook, op server.Op) server.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) server.Hook {
	return func(server.Mutator) server.Mutator {
		return server.MutateFunc(func(context.Context, server.Mutation) (server.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []server.Hook {
//		return []server.Hook{
//			Reject(server.Delete|server.Update),
//		}
//	}
func Reject(op server.Op) server.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []server.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...server.Hook) Chain {
	return Chain{append([]server.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() server.Hook {
	return func(mutator server.Mutator) server.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...server.Hook) Chain {
	newHooks := make([]server.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
